-- CANDIDATE ONLY. Never execute automatically. Require exact tenant/database/Registry owner+generation, stop all writers, verify B1 parents. Existing table => stop, do not IF NOT EXISTS.
-- New seven-table subset only; no approval definitions, grants or environment changes.
CREATE TABLE finance_invoice_request (
    id                          BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    code                        VARCHAR(64)  NOT NULL COMMENT 'IR-xxxxxx',
    source_app                  VARCHAR(30)  NOT NULL DEFAULT 'finance' COMMENT 'altoc/finance',
    source_biz_type             VARCHAR(50)  DEFAULT NULL COMMENT 'billing_schedule/manual',
    source_biz_code             VARCHAR(100) DEFAULT NULL,
    customer_code               VARCHAR(64)  DEFAULT NULL COMMENT 'altoc_customer.code',
    customer_name               VARCHAR(200) DEFAULT NULL COMMENT '申请时快照',
    contract_code               VARCHAR(64)  DEFAULT NULL COMMENT 'altoc_contract.code',
    billing_schedule_code       VARCHAR(64)  DEFAULT NULL COMMENT 'altoc_billing_schedule.code（原 receivable_plan_code）',
    invoice_profile_code        VARCHAR(64)  DEFAULT NULL COMMENT 'altoc_customer_invoice_profile.code',
    invoice_type                VARCHAR(30)  DEFAULT NULL COMMENT 'special_vat/general_vat/electronic/other',
    invoice_medium              VARCHAR(20)  NOT NULL DEFAULT 'electronic' COMMENT 'electronic/paper',
    invoice_item                VARCHAR(500) DEFAULT NULL,
    requested_amount            DECIMAL(18,2) NOT NULL,
    currency_code               CHAR(3) NOT NULL DEFAULT 'CNY',
    tax_rate                    DECIMAL(5,2) DEFAULT NULL,
    taxpayer_name               VARCHAR(200) DEFAULT NULL,
    taxpayer_no                 VARCHAR(50)  DEFAULT NULL,
    billing_info_json           JSON DEFAULT NULL COMMENT '申请时冻结的开票资料快照',
    status                      VARCHAR(30)  NOT NULL DEFAULT 'draft' COMMENT 'draft/pending_approval/approved/rejected/issued/canceled',
    workflow_instance_id        VARCHAR(100) DEFAULT NULL,
    requested_by                VARCHAR(64)  DEFAULT NULL COMMENT '申请人（职责分离比较基准）',
    submitted_at                DATETIME(3) DEFAULT NULL,
    approved_at                 DATETIME(3) DEFAULT NULL,
    rejected_at                 DATETIME(3) DEFAULT NULL,
    reject_reason               VARCHAR(500) DEFAULT NULL,
    issued_invoice_id           BIGINT UNSIGNED DEFAULT NULL,
    issued_by                   VARCHAR(64)  DEFAULT NULL COMMENT '实际开票人（D-01 若采用则 ≠ requested_by）',
    issuance_responsible_uid    VARCHAR(64)  DEFAULT NULL,
    issuance_due_at             DATETIME(3)  DEFAULT NULL,
    idempotency_key             VARCHAR(191) DEFAULT NULL COMMENT '创建幂等键（Altoc 来源 = operation idempotency_key）',
    remark                      VARCHAR(500) DEFAULT NULL,
    row_version                 INT UNSIGNED NOT NULL DEFAULT 1,
    created_by                  VARCHAR(64) DEFAULT NULL,
    updated_by                  VARCHAR(64) DEFAULT NULL,
    created_at                  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at                  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at                  DATETIME(3) DEFAULT NULL,
    UNIQUE KEY uk_finance_invoice_request_code (code),
    UNIQUE KEY uk_finance_invoice_request_idempotency (idempotency_key),
    KEY idx_finance_invoice_request_contract (contract_code),
    KEY idx_finance_invoice_request_schedule (billing_schedule_code, status),
    KEY idx_finance_invoice_request_source (source_app, source_biz_type, source_biz_code),
    KEY idx_finance_invoice_request_status (status, submitted_at),
    KEY idx_finance_invoice_request_requester (requested_by, status),
    KEY idx_finance_invoice_request_workflow (workflow_instance_id),
    KEY idx_finance_invoice_request_issuance_due (status, issuance_due_at, id),
    KEY idx_finance_invoice_request_issuance_responsible (issuance_responsible_uid, status, issuance_due_at),
    CONSTRAINT ck_finance_invoice_request_issuance_responsibility CHECK (
      (issuance_responsible_uid IS NULL AND issuance_due_at IS NULL)
      OR (issuance_responsible_uid IS NOT NULL AND issuance_due_at IS NOT NULL
          AND issuance_responsible_uid = TRIM(issuance_responsible_uid) AND issuance_responsible_uid <> ''
          AND LOWER(issuance_responsible_uid) <> '@all' AND issuance_responsible_uid NOT REGEXP '[[:cntrl:]]'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='开票申请（原 invoice_request）';

CREATE TABLE finance_invoice (
    id                      BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    code                    VARCHAR(64)  NOT NULL COMMENT 'IV-xxxxxx；唯一正式发票事实源',
    invoice_no              VARCHAR(80)  DEFAULT NULL COMMENT '税务发票号码',
    invoice_request_id      BIGINT UNSIGNED DEFAULT NULL,
    customer_code           VARCHAR(64)  DEFAULT NULL,
    customer_name           VARCHAR(200) DEFAULT NULL,
    contract_code           VARCHAR(64)  DEFAULT NULL,
    project_code            VARCHAR(64)  DEFAULT NULL,
    billing_schedule_code   VARCHAR(64)  DEFAULT NULL,
    invoice_type            VARCHAR(30)  DEFAULT NULL,
    invoice_medium          VARCHAR(20)  NOT NULL DEFAULT 'electronic',
    invoice_item            VARCHAR(500) DEFAULT NULL,
    invoice_amount          DECIMAL(18,2) NOT NULL COMMENT '价税合计（正数；红冲由状态 + reversal_of_invoice_id 表达）',
    currency_code           CHAR(3) NOT NULL DEFAULT 'CNY',
    tax_rate                DECIMAL(5,2) DEFAULT NULL,
    tax_amount              DECIMAL(18,2) DEFAULT NULL,
    amount_tax_exclusive    DECIMAL(18,2) DEFAULT NULL,
    invoice_date            DATE DEFAULT NULL,
    status                  VARCHAR(30)  NOT NULL DEFAULT 'issued' COMMENT 'draft/issued/red_reversed/canceled',
    reconciled_amount       DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '有效核销分配累计（核销事务维护）',
    unreconciled_amount     DECIMAL(18,2) GENERATED ALWAYS AS (GREATEST(invoice_amount - reconciled_amount, 0)) STORED,
    taxpayer_name           VARCHAR(200) DEFAULT NULL,
    taxpayer_no             VARCHAR(50)  DEFAULT NULL,
    receiver_name           VARCHAR(200) DEFAULT NULL,
    invoice_file_key        VARCHAR(500) DEFAULT NULL COMMENT 'OSS key（原 invoice_file_url；不存签名 URL）',
    invoice_file_name       VARCHAR(255) DEFAULT NULL,
    invoice_file_mime_type  VARCHAR(100) DEFAULT NULL,
    invoice_file_size       BIGINT UNSIGNED DEFAULT NULL,
    reversal_of_invoice_id  BIGINT UNSIGNED DEFAULT NULL COMMENT '红字发票指向被冲蓝票',
    reversed_at             DATETIME(3) DEFAULT NULL,
    reversed_by             VARCHAR(64)  DEFAULT NULL,
    reverse_reason          VARCHAR(500) DEFAULT NULL,
    issued_by               VARCHAR(64)  DEFAULT NULL,
    remark                  VARCHAR(500) DEFAULT NULL,
    row_version             INT UNSIGNED NOT NULL DEFAULT 1,
    created_by              VARCHAR(64) DEFAULT NULL,
    updated_by              VARCHAR(64) DEFAULT NULL,
    created_at              DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at              DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at              DATETIME(3) DEFAULT NULL,
    UNIQUE KEY uk_finance_invoice_code (code),
    UNIQUE KEY uk_finance_invoice_no (invoice_no),
    KEY idx_finance_invoice_request (invoice_request_id),
    KEY idx_finance_invoice_contract (contract_code, status),
    KEY idx_finance_invoice_customer (customer_code),
    KEY idx_finance_invoice_project (project_code),
    KEY idx_finance_invoice_schedule (billing_schedule_code),
    KEY idx_finance_invoice_date (invoice_date),
    KEY idx_finance_invoice_status (status, deleted_at),
    KEY idx_finance_invoice_reversal (reversal_of_invoice_id),
    CONSTRAINT fk_finance_invoice_request FOREIGN KEY (invoice_request_id) REFERENCES finance_invoice_request(id),
    CONSTRAINT fk_finance_invoice_reversal FOREIGN KEY (reversal_of_invoice_id) REFERENCES finance_invoice(id),
    CONSTRAINT ck_finance_invoice_amounts CHECK (invoice_amount >= 0 AND reconciled_amount >= 0 AND reconciled_amount <= invoice_amount)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='正式发票（唯一事实源；Altoc 只读）';

CREATE TABLE finance_receipt (
    id                              BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    code                            VARCHAR(64)  NOT NULL COMMENT 'RC-xxxxxx',
    receipt_no                      VARCHAR(80)  DEFAULT NULL COMMENT '银行流水/外部收款编号',
    customer_code                   VARCHAR(64)  DEFAULT NULL,
    customer_name                   VARCHAR(200) DEFAULT NULL,
    contract_code                   VARCHAR(64)  DEFAULT NULL,
    project_code                    VARCHAR(64)  DEFAULT NULL,
    billing_schedule_code           VARCHAR(64)  DEFAULT NULL COMMENT '登记时的预期结算计划；最终归属以核销分配为准',
    receipt_source_type             VARCHAR(30)  NOT NULL DEFAULT 'contract' COMMENT 'contract/no_contract/pre_contract/other',
    accounting_object_code          VARCHAR(64)  DEFAULT NULL,
    bank_account_id                 BIGINT UNSIGNED DEFAULT NULL,
    income_type_id                  BIGINT UNSIGNED DEFAULT NULL,
    received_amount                 DECIMAL(18,2) NOT NULL,
    currency_code                   CHAR(3) NOT NULL DEFAULT 'CNY',
    reconciled_amount               DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '有效核销分配累计（核销事务在同一行锁下维护）',
    unreconciled_amount             DECIMAL(18,2) GENERATED ALWAYS AS (GREATEST(received_amount - reconciled_amount, 0)) STORED,
    received_at                     DATE NOT NULL,
    channel                         VARCHAR(30)  DEFAULT NULL COMMENT 'cash/bank_transfer/third_party/other',
    payer_name                      VARCHAR(200) DEFAULT NULL,
    handler_uid                     VARCHAR(64)  DEFAULT NULL COMMENT '经办人（原 handler_user_id）',
    reconciliation_responsible_uid  VARCHAR(64)  DEFAULT NULL,
    reconciliation_due_at           DATETIME(3)  DEFAULT NULL,
    status                          VARCHAR(30)  NOT NULL DEFAULT 'draft' COMMENT 'draft/confirmed/partially_reconciled/reconciled/canceled（建议调整 F-03：默认 draft，须显式 confirm）',
    confirmed_by                    VARCHAR(64)  DEFAULT NULL,
    confirmed_at                    DATETIME(3)  DEFAULT NULL,
    note                            VARCHAR(500) DEFAULT NULL,
    row_version                     INT UNSIGNED NOT NULL DEFAULT 1,
    created_by                      VARCHAR(64) DEFAULT NULL,
    updated_by                      VARCHAR(64) DEFAULT NULL,
    created_at                      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at                      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at                      DATETIME(3) DEFAULT NULL,
    UNIQUE KEY uk_finance_receipt_code (code),
    KEY idx_finance_receipt_contract (contract_code, status),
    KEY idx_finance_receipt_customer (customer_code),
    KEY idx_finance_receipt_project (project_code),
    KEY idx_finance_receipt_schedule (billing_schedule_code),
    KEY idx_finance_receipt_bank_account (bank_account_id, received_at),
    KEY idx_finance_receipt_income_type (income_type_id),
    KEY idx_finance_receipt_received_at (received_at),
    KEY idx_finance_receipt_status (status, deleted_at),
    KEY idx_finance_receipt_reconciliation_due (status, reconciliation_due_at, id),
    KEY idx_finance_receipt_reconciliation_responsible (reconciliation_responsible_uid, status, reconciliation_due_at),
    CONSTRAINT fk_finance_receipt_bank_account FOREIGN KEY (bank_account_id) REFERENCES finance_bank_account(id),
    CONSTRAINT fk_finance_receipt_income_type FOREIGN KEY (income_type_id) REFERENCES finance_income_type(id),
    CONSTRAINT ck_finance_receipt_amounts CHECK (received_amount > 0 AND reconciled_amount >= 0 AND reconciled_amount <= received_amount),
    CONSTRAINT ck_finance_receipt_reconciliation_responsibility CHECK (
      (reconciliation_responsible_uid IS NULL AND reconciliation_due_at IS NULL)
      OR (reconciliation_responsible_uid IS NOT NULL AND reconciliation_due_at IS NOT NULL
          AND reconciliation_responsible_uid = TRIM(reconciliation_responsible_uid) AND reconciliation_responsible_uid <> ''
          AND LOWER(reconciliation_responsible_uid) <> '@all' AND reconciliation_responsible_uid NOT REGEXP '[[:cntrl:]]'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='到账/收款记录';

CREATE TABLE finance_reconciliation (
    id                      BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    code                    VARCHAR(64)  NOT NULL COMMENT 'RL-xxxxxx；核销分配行（一笔到账 → 一个目标 → 一个金额）',
    receipt_id              BIGINT UNSIGNED NOT NULL,
    target_type             VARCHAR(30)  NOT NULL COMMENT 'invoice/billing_schedule/contract/advance/unclassified/manual',
    invoice_id              BIGINT UNSIGNED DEFAULT NULL,
    customer_code           VARCHAR(64)  DEFAULT NULL,
    contract_code           VARCHAR(64)  DEFAULT NULL,
    project_code            VARCHAR(64)  DEFAULT NULL,
    billing_schedule_code   VARCHAR(64)  DEFAULT NULL COMMENT '目标结算计划（Altoc 共享事务回写键）',
    reconciled_amount       DECIMAL(18,2) NOT NULL,
    currency_code           CHAR(3) NOT NULL DEFAULT 'CNY',
    reconciled_at           DATETIME(3) NOT NULL,
    status                  VARCHAR(30)  NOT NULL DEFAULT 'active' COMMENT 'active/reversed',
    reversed_at             DATETIME(3) DEFAULT NULL,
    reversed_by             VARCHAR(64)  DEFAULT NULL,
    reverse_reason          VARCHAR(500) DEFAULT NULL,
    idempotency_key         VARCHAR(191) NOT NULL COMMENT '创建幂等键：Idempotency-Key 或 receipt_code+target+amount 派生',
    reconciled_by           VARCHAR(64)  DEFAULT NULL COMMENT '核销人（D-02 若采用则 ≠ receipt.confirmed_by）',
    note                    VARCHAR(500) DEFAULT NULL,
    row_version             INT UNSIGNED NOT NULL DEFAULT 1,
    created_by              VARCHAR(64) DEFAULT NULL,
    created_at              DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at              DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_finance_reconciliation_code (code),
    UNIQUE KEY uk_finance_reconciliation_idempotency (idempotency_key),
    KEY idx_finance_reconciliation_receipt (receipt_id, status),
    KEY idx_finance_reconciliation_invoice (invoice_id, status),
    KEY idx_finance_reconciliation_contract (contract_code),
    KEY idx_finance_reconciliation_schedule (billing_schedule_code, status),
    KEY idx_finance_reconciliation_project (project_code),
    KEY idx_finance_reconciliation_at (reconciled_at),
    CONSTRAINT fk_finance_reconciliation_receipt FOREIGN KEY (receipt_id) REFERENCES finance_receipt(id),
    CONSTRAINT fk_finance_reconciliation_invoice FOREIGN KEY (invoice_id) REFERENCES finance_invoice(id),
    CONSTRAINT ck_finance_reconciliation_amount CHECK (reconciled_amount > 0),
    CONSTRAINT ck_finance_reconciliation_reversal CHECK (
      (status = 'active' AND reversed_at IS NULL AND reversed_by IS NULL)
      OR (status = 'reversed' AND reversed_at IS NOT NULL AND reversed_by IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='收款核销分配（撤销为原地 reversed，不删除；汇总列由同事务重算）';

CREATE TABLE finance_contract_summary (
 contract_code VARCHAR(64) PRIMARY KEY, currency_code CHAR(3) NOT NULL,
 invoice_amount DECIMAL(18,2) NOT NULL DEFAULT 0, received_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
 reconciled_amount DECIMAL(18,2) NOT NULL DEFAULT 0, billing_schedule_count INT NOT NULL DEFAULT 0,
 input_sha256 CHAR(64) NOT NULL, row_version INT UNSIGNED NOT NULL DEFAULT 1,
 updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE finance_unclassified_income (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, code VARCHAR(64) NOT NULL UNIQUE,
 receipt_id BIGINT UNSIGNED NOT NULL UNIQUE, income_type_id BIGINT UNSIGNED DEFAULT NULL,
 resolution_status VARCHAR(30) NOT NULL, note VARCHAR(500) DEFAULT NULL,
 row_version INT UNSIGNED NOT NULL DEFAULT 1, created_by VARCHAR(64), updated_by VARCHAR(64),
 created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3), updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 CONSTRAINT fk_finance_unclassified_receipt FOREIGN KEY(receipt_id) REFERENCES finance_receipt(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE finance_attachment (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, code VARCHAR(64) NOT NULL UNIQUE,
 entity_type VARCHAR(30) NOT NULL, entity_code VARCHAR(64) NOT NULL, file_key VARCHAR(500) NOT NULL,
 file_name VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, file_size BIGINT UNSIGNED NOT NULL,
 file_sha256 CHAR(64) NOT NULL, row_version INT UNSIGNED NOT NULL DEFAULT 1,
 created_by VARCHAR(64) NOT NULL, created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3), deleted_at DATETIME(3),
 UNIQUE KEY uk_finance_attachment_key(file_key), KEY idx_finance_attachment_object(entity_type,entity_code,deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
