import { handleEnterpriseAccessibleProjectDocumentsService } from '~~/server/utils/enterpriseAccessibleProjectDocumentsService'

export default defineEventHandler(handleEnterpriseAccessibleProjectDocumentsService)
