import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { test } from 'node:test'

const source = (path: string) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')

test('DingTalk login uses a single-use external transaction and typed Connector exchange', () => {
  const start = source('server/api/auth/dingtalk-login.get.ts')
  const callback = source('server/api/auth/dingtalk-callback.get.ts')
  const client = source('server/utils/dingtalk.ts')
  const state = source('server/utils/externalLoginState.ts')
  const runtimeState = source('../data-runtime/internal/apps/console/auth_external_login.go')

  assert.match(start, /issueExternalLoginTransaction\(event, \{[\s\S]*provider: 'dingtalk'/)
  assert.match(start, /login\.dingtalk\.com\/oauth2\/auth/)
  assert.match(start, /scope: 'openid corpid Contact\.User\.Read'/)
  assert.match(start, /clientId, integrationCode[\s\S]*getDingTalkOAuthPublicConfig\(event\)[\s\S]*issueExternalLoginTransaction/)
  assert.match(callback, /consumeExternalLoginTransaction\(event, \{ provider: 'dingtalk', state \}\)[\s\S]*getDingTalkUserByCode\(code, event, transaction\.integrationCode\)/)
  assert.match(state, /type ExternalLoginProvider = 'wecom' \| 'dingtalk'/)
  assert.match(client, /audience: 'connector-runtime'/)
  assert.match(client, /connector-runtime:identity:dingtalk:exchange/)
  assert.match(client, /\/v1\/identity\/dingtalk\/exchange/)
  assert.match(client, /dingtalk_identity_exchange_rejected[\s\S]*网页登录应用版本已发布/)
  assert.match(client, /dingtalk_identity_profile_failed[\s\S]*用户身份信息权限/)
  assert.match(client, /dingtalk_identity_mapping_failed[\s\S]*通讯录成员查询权限/)
  assert.match(callback, /safeFailureCode[\s\S]*failureReason: safeFailureCode/)
  assert.match(callback, /projectedMessage \|\|/)
  assert.match(client, /root\.data, response\._data, response\.data, cause\.data/)
  assert.match(client, /Exchange failed:', failure\.code \|\| 'unclassified'/)
  assert.match(client, /connector\.dingtalkIdentityEnabled/)
  assert.match(client, /'oauthClientId'[\s\S]*'loginClientId'[\s\S]*'appKey'/)
  assert.match(client, /IDENTITY_INTEGRATION_CODE = 'dingtalk\.identity'/)
  assert.match(state, /integrationCode/)
  assert.match(runtimeState, /integration_code/)
  assert.match(runtimeState, /"integrationCode": nullableVaultString\(integrationCode\)/)
  assert.doesNotMatch(state, /server\/utils\/db|queryRow|execute|withTransaction/)
  assert.doesNotMatch(client, /unifiedAppId/)
  assert.doesNotMatch(client, /api\.dingtalk\.com|oapi\.dingtalk\.com|appSecret|accessToken/)
  assert.doesNotMatch(callback, /authCode.*sessionId|code.*sessionId/)
})

test('DingTalk identity migration adds only a non-secret transaction binding and exact grants', () => {
  const migration = source('../console/docs/sql/Console-SQL-Migration-v1.77-dingtalk-identity-integration.sql')
  const schema = source('docs/hzy_console_schema.sql')

  assert.match(migration, /information_schema\.COLUMNS/)
  assert.match(migration, /ADD COLUMN `integration_code` VARCHAR\(128\) NULL/)
  assert.match(migration, /JSON_ARRAY\('dingtalk\.default','dingtalk\.identity'\)/)
  assert.match(migration, /JSON_ARRAY\('wecom\.default','dingtalk\.default','dingtalk\.identity'\)/)
  assert.match(schema, /auth_external_login_transactions[\s\S]*`integration_code` VARCHAR\(128\) NULL/)
  assert.doesNotMatch(migration, /client_secret|appSecret|app_secret\s*=/i)
})

test('DingTalk integration secret stays in Vault and activation uses an exact capability', () => {
  const page = source('app/pages/integrations.vue')
  const loginPage = source('app/pages/login.vue')
  const activation = source('server/utils/connectorRuntimeActivation.ts')
  const enrollment = source('../data-runtime/internal/apps/console/connector_runtime.go')
  const serviceIdentity = source('../data-runtime/internal/apps/console/auth_service_tokens.go')
  const seed = source('../console/docs/sql/Console-SQL-Seed-v1.72-connector-runtime-dingtalk.sql')

  assert.match(page, /integration\.dingtalk\.default\.app_secret/)
  assert.match(page, /dingtalk\.default/)
  const defaultIntegration = page.slice(page.indexOf('  dingtalk: {'), page.indexOf('  dingtalk_identity: {'))
  assert.match(defaultIntegration, /key: 'appKey', label: 'Client ID（原 AppKey）'/)
  assert.match(defaultIntegration, /key: 'agentId', label: 'Agent ID（People 花名册）'/)
  assert.doesNotMatch(defaultIntegration, /key: 'oauthClientId'/)
  assert.doesNotMatch(defaultIntegration, /key: 'robotCode'/)
  assert.match(page, /payload: Record<string, unknown> = \{ \.\.\.\(selectedIntegration\.value\?\.config \|\| \{\}\) \}/)
  assert.match(page, /\^\\d\+\$\/[.]test\(oauthClientId\)[\s\S]*delete payload\.oauthClientId/)
  assert.match(page, /robotCode === appKey[\s\S]*delete payload\.robotCode/)
  assert.match(page, /defaultStorageBackend\?: StorageBackend/)
  assert.match(page, /type: 'dingtalk'[\s\S]*defaultStorageBackend: 'db_encrypted'/)
  assert.match(page, /type: 'wecom'[\s\S]*defaultStorageBackend: 'db_encrypted'/)
  assert.match(page, /storageBackend: definition\.defaultStorageBackend \|\| 'env_ref'/)
  assert.match(page, /i-lucide-message-circle/)
  assert.match(loginPage, /dingtalk: \{ label: '钉钉登录', icon: 'i-lucide-message-circle' \}/)
  assert.doesNotMatch(`${page}\n${loginPage}`, /i-simple-icons-dingtalk/)
  assert.match(activation, /identity\.dingtalk\.exchange/)
  assert.match(activation, /connector-runtime:identity:dingtalk:exchange/)
  assert.match(activation, /connector\.dingtalkIdentityEnabled/)
  assert.match(enrollment, /"integrationCodes": \[\]string\{"wecom\.default", "dingtalk\.default", "dingtalk\.identity"\}/)
  assert.match(serviceIdentity, /"connector-runtime:identity:dingtalk:exchange"/)
  assert.match(seed, /JSON_ARRAY\('wecom\.default','dingtalk\.default','dingtalk\.identity'\)/)
  assert.doesNotMatch(seed, /appSecret\s*=|app_secret\s*=|VALUES\s*\([^)]*ding[a-zA-Z0-9]{20,}/)
})

test('DingTalk identity activation prefers its dedicated integration with a compatible default fallback', () => {
  const activation = source('server/utils/connectorRuntimeActivation.ts')
  const client = source('server/utils/dingtalk.ts')
  const page = source('app/pages/integrations.vue')
  const runtime = source('../data-runtime/internal/apps/console/integrations.go')

  assert.match(activation, /getDingTalkOAuthPublicConfig/)
  assert.match(client, /dedicated\?\.status === 'active'[\s\S]*IDENTITY_INTEGRATION_CODE[\s\S]*DEFAULT_INTEGRATION_CODE/)
  assert.match(client, /hasActiveIntegrationCredentialBinding\(event, integrationCode\)/)
  assert.match(client, /isPlausibleDingTalkOAuthClientId\(clientId\)/)
  assert.match(page, /integrationCode: 'dingtalk\.identity'/)
  assert.match(page, /integration\.dingtalk\.identity\.client_secret/)
  assert.match(page, /不要填写 AgentId 或 UnifiedAppId/)
  assert.match(runtime, /func plausibleDingTalkOAuthClientID[\s\S]*regexp\.MustCompile\(`\^\[0-9\]\+\$`\)/)
  assert.match(runtime, /AgentId and UnifiedAppId/)
  assert.doesNotMatch(activation, /unifiedAppId/)
  assert.match(runtime, /INNER JOIN vault_secret_versions bound_v[\s\S]*bound_v\.status='active'/)
  assert.doesNotMatch(activation, /resolveVaultSecret/)
})

test('DingTalk settings use one card and default login to the shared application', () => {
  const page = source('app/pages/integrations.vue')
  const saveStart = page.indexOf('async function saveSharedDingTalkLogin()')
  const saveEnd = page.indexOf('\nasync function rotateCredential', saveStart)
  const saveBlock = page.slice(saveStart, saveEnd)

  assert.match(page, /const visibleIntegrationTypes = integrationTypes\.filter\(type => type !== 'dingtalk_identity'\)/)
  assert.match(page, /v-for="type in visibleIntegrationTypes"/)
  assert.match(page, /aria-label="钉钉集成配置"[\s\S]*通知与 People[\s\S]*登录/)
  assert.match(page, /const dingtalkLoginMode = ref<DingTalkLoginMode>\('shared'\)/)
  assert.match(page, /复用当前钉钉应用[\s\S]*使用独立登录应用/)
  assert.match(page, /v-if="selectedType !== 'dingtalk_identity'"[\s\S]*label="状态"/)
  assert.match(saveBlock, /const sharedConfig = normalizeDingTalkDefaultConfig\(defaultIntegration\.config\)[\s\S]*delete sharedConfig\.oauthClientId/)
  assert.match(saveBlock, /identityIntegration\?\.status === 'active'[\s\S]*body: \{ status: 'inactive' \}/)
  assert.ok(
    saveBlock.indexOf('body: { config: sharedConfig }') < saveBlock.indexOf('body: { status: \'inactive\' }'),
    'shared config must be normalized before the independent login override is disabled'
  )
})

test('DingTalk notification acceptance uses the typed Connector route and proves durable replay', () => {
  const route = source('server/api/v1/console/connector-runtime/dingtalk-test.post.ts')
  const integrations = source('server/utils/integrations.ts')
  const page = source('app/pages/integrations.vue')
  const start = integrations.indexOf('async function sendIntegrationTestMessage')
  const end = integrations.indexOf('\nexport async function sendWecomIntegrationTestMessage', start)
  const block = integrations.slice(start, end)

  assert.match(route, /requireIntegrationAccess\(event, 'edit'\)/)
  assert.match(route, /integrationCode = stringValue\(body\.integrationCode\) \|\| 'dingtalk\.default'/)
  assert.match(route, /const result = await sendDingTalkIntegrationTestMessage\(/)
  assert.match(route, /const replay = await sendDingTalkIntegrationTestMessage\(/)
  assert.match(route, /isConfirmedRuntimeReplay\(replay\)/)
  assert.match(route, /replayVerified: true/)
  assert.match(block, /row\.integrationType !== provider/)
  assert.match(block, /provider === 'dingtalk' && target\.deliveryMode !== 'connector-runtime'/)
  assert.match(block, /channel: provider/)
  assert.match(block, /`console:connector-runtime:dingtalk-test:\$\{requestKey\}`/)
  assert.match(integrations, /sendDingTalkIntegrationTestMessage[\s\S]*sendIntegrationTestMessage\(input, 'dingtalk'\)/)
  assert.match(page, /\/api\/v1\/console\/connector-runtime\/dingtalk-test/)
  assert.match(page, /integrationCode: 'dingtalk\.default'/)
  assert.match(page, /requestKey: globalThis\.crypto\.randomUUID\(\)/)
  assert.match(page, /if \(!response\.data\.replayVerified\)/)
  assert.match(page, /幂等重放已验证/)
  assert.match(page, /!canEditIntegrations \|\| !selectedIntegration/)
  assert.doesNotMatch(route, /api\.dingtalk\.com|oapi\.dingtalk\.com|appSecret|resolveVaultSecret/)
  assert.doesNotMatch(page, /appSecret|api\.dingtalk\.com\/v1\.0\/robot/)
})
