import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { test } from 'node:test'

const source = (path: string) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')

test('connector runtime install command contains only a short-lived enrollment code', () => {
  const content = source('server/utils/connectorRuntimeEnrollment.ts')
  const runtime = source('../data-runtime/internal/apps/console/connector_runtime.go')
  assert.match(runtime, /connectorRuntimeEnrollmentTTL = 15 \* time\.Minute/)
  assert.match(runtime, /"hzy_cre_" \+ base64\.RawURLEncoding/)
  assert.match(runtime, /enrollment_token_sha256/)
  assert.match(runtime, /sha256\.Sum256\(\[\]byte\(code\)\)/)
  assert.match(content, /HZY_CONNECTOR_RUNTIME_ENROLLMENT_CODE=/)
  assert.match(content, /HZY_CONNECTOR_RUNTIME_RELEASE_PUBLIC_KEY_PEM_BASE64/)
  assert.match(content, /HZY_CONNECTOR_RUNTIME_DATA_RUNTIME_URL=/)
  assert.match(content, /resolveDataRuntimeParameters\(event\)/)
  assert.match(content, /Data Runtime 地址未配置或不安全/)
  assert.match(content, /openssl pkeyutl -verify -rawin/)
  assert.doesNotMatch(content.slice(content.indexOf('function installCommand'), content.indexOf('export async function getConnectorRuntimeMetadata')), /CLIENT_SECRET|clientSecret/)
  const installer = source('../connector-runtime/deploy/install.sh')
  const packager = source('../connector-runtime/scripts/package-release.sh')
  assert.match(installer, /verify_signature "\$manifest" "\$manifest_signature"/)
  assert.match(installer, /verify_signature "\$archive" "\$archive_signature"/)
  assert.match(packager, /HZY_CONNECTOR_RUNTIME_RELEASE_SIGNING_KEY_FILE/)
  assert.match(packager, /pkeyutl -sign -rawin/)
})

test('enrollment is binding-scoped, single use and encrypts the issued credential', () => {
  const bff = source('server/utils/connectorRuntimeEnrollment.ts')
  const runtime = source('../data-runtime/internal/apps/console/connector_runtime.go')
  const foundation = source('../foundation/server/utils/consoleTenantRuntimeClient.ts')
  assert.doesNotMatch(bff, /server\/utils\/db|queryRow|queryRows|execute|withTransaction/)
  assert.match(foundation, /\/v1\/console\/connector-runtime\/enroll/)
  assert.match(runtime, /LIMIT 1 FOR UPDATE/)
  assert.match(runtime, /status != "issued"/)
  assert.match(runtime, /tenantCode != a\.tenant \|\| boundDeployment != deploymentCode/)
  assert.match(runtime, /status='redeemed'.*WHERE enrollment_id=\? AND status='issued'/s)
  assert.match(runtime, /publicKey\.N\.BitLen\(\) < 3072/)
  assert.match(runtime, /rsa\.EncryptOAEP/)
  assert.match(runtime, /sha256\.New\(\)/)
  assert.match(runtime, /hzy-connector-runtime-enrollment\.v1/)
  assert.match(runtime, /"integrationCodes": \[\]string\{"wecom\.default", "dingtalk\.default", "dingtalk\.identity"\}/)
  assert.match(runtime, /\{"credential_vault", "resolve"/)
  assert.match(runtime, /\{"console:connector-runtime", "heartbeat"/)
  assert.match(runtime, /resource_code='connector_runtime'[\s\S]*action='heartbeat'[\s\S]*status='active'/)
  assert.match(runtime, /backend_secret_ref,content_hash,encryption_scheme[\s\S]*'hash-only'[\s\S]*'sha256-only'/)
  assert.doesNotMatch(runtime, /ciphertext_blob[\s\S]*clientSecret/)
})

test('connector runtime enrollment schema stores only token hashes and one instance per binding', () => {
  const migration = source('../console/docs/sql/Console-SQL-Migration-v1.68-connector-runtime-enrollment.sql')
  assert.match(migration, /connector_runtime_enrollments/)
  assert.match(migration, /enrollment_token_sha256/)
  assert.doesNotMatch(migration, /`enrollment_token`\s/)
  assert.match(migration, /UNIQUE KEY `uk_connector_runtime_binding` \(`tenant_code`, `deployment_code`\)/)
})

test('only an authenticated system administrator can issue an install command', () => {
  const issueRoute = source('server/api/v1/console/connector-runtime/install-command.post.ts')
  const metadataRoute = source('server/api/v1/console/connector-runtime/install-command.get.ts')
  assert.match(issueRoute, /requireSystemSettingsAccess\(event, 'admin'\)/)
  assert.match(issueRoute, /requireIdempotencyKey\(event/)
  assert.match(metadataRoute, /requireSystemSettingsAccess\(event, 'view'\)/)
})

test('connector runtime page separates view, edit and one-time enrollment administration', () => {
  const page = source('app/pages/connector-runtime.vue')
  const permissions = source('app/config/permissions.ts')
  const settingSeed = source('../console/docs/sql/Console-SQL-Seed-v1.69-connector-runtime-setting.sql')
  assert.match(page, /hasPermission\('system_settings', 'edit'\)/)
  assert.match(page, /hasPermission\('system_settings', 'admin'\)/)
  assert.match(page, /connector\.runtimeApiUrl/)
  assert.match(page, /安装码 15 分钟内有效且只能使用一次/)
  assert.match(page, /headers: \{ 'Idempotency-Key': crypto\.randomUUID\(\) \}/)
  assert.match(page, /metadata\.dataRuntimeApiUrl/)
  assert.match(page, /分机部署时，必须先在“数据运行时”页面配置 HTTPS origin/)
  assert.match(page, /企业微信消息测试/)
  assert.match(page, /notification-runtime\/wecom-check/)
  assert.match(page, /notification-runtime\/wecom-test/)
  assert.match(page, /hasPermission\('integration_config', 'edit'\)/)
  assert.doesNotMatch(page, /回退旧通道/)
  assert.doesNotMatch(page, /现有 Notification Runtime 需要显式迁移/)
  assert.match(permissions, /to: '\/connector-runtime'/)
  assert.doesNotMatch(permissions, /to: '\/notification-runtime'/)
  assert.match(permissions, /pattern: '\/connector-runtime\/\*\*'/)
  assert.match(settingSeed, /connector\.runtimeApiUrl/)
  assert.match(settingSeed, /connector-runtime:notifications/)
  assert.match(settingSeed, /connector\.notificationsEnabled/)
  assert.match(settingSeed, /CAST\('false' AS JSON\)/)
  assert.match(settingSeed, /legacy_notification_grant[\s\S]*resource_code`='notification-runtime'/)
  assert.match(settingSeed, /legacy_notification_grant[\s\S]*action`='send'/)
})

test('notification cutover is explicit and verifies the typed runtime before changing the setting', () => {
  const activation = source('server/utils/connectorRuntimeActivation.ts')
  const route = source('server/api/v1/console/connector-runtime/notification-activation.post.ts')
  const settings = source('server/utils/systemParameters.ts')
  const foundationNotify = source('../foundation/server/utils/notify.ts')
  const integrations = source('server/utils/integrations.ts')
  const migrationScript = source('../connector-runtime/deploy/migrate-notification-runtime.sh')
  assert.match(route, /requireSystemSettingsAccess\(event, 'admin'\)[\s\S]*readBody/)
  assert.match(activation, /hzy-connector-runtime/)
  assert.match(activation, /hzy\.connector-capabilities\.v1/)
  assert.match(activation, /arbitraryHttpProxy !== false/)
  assert.match(activation, /connector-runtime:notifications:send/)
  assert.match(activation, /updateManagedSettingValue\([\s\S]*connector\.notificationsEnabled[\s\S]*value: true/)
  assert.doesNotMatch(activation, /\bupdateSettingValue\b/)
  assert.match(route, /getHeader\(event, 'idempotency-key'\)/)
  assert.match(settings, /getConsoleSettingValues/)
  assert.match(settings, /updateConsoleManagedSettingValue/)
  assert.match(settings, /expectedRevision: current\.revision/)
  assert.doesNotMatch(settings, /server\/utils\/db|queryRow|queryRows|execute|withTransaction/)
  assert.match(foundationNotify, /connector\.notificationsEnabled/)
  assert.match(foundationNotify, /audience: 'connector-runtime'/)
  assert.match(foundationNotify, /scope: 'connector-runtime:notifications:send'/)
  assert.match(integrations, /resolveNotificationDeliveryTarget/)
  assert.match(integrations, /deliveryMode: 'connector-runtime'/)
  assert.match(migrationScript, /systemctl stop "\$SOURCE_SERVICE\.service"/)
  assert.match(migrationScript, /install -m 0600 "\$source_db" "\$target_db"/)
  assert.match(migrationScript, /"\$TARGET_BINARY" -check-store/)
  assert.match(migrationScript, /arbitraryHttpProxy/)
  assert.match(migrationScript, /Connector cutover failed; Notification Runtime was restored/)
})
