import test from 'node:test'
import assert from 'node:assert/strict'
import { createServer } from 'node:http'
import { registerHooks } from 'node:module'
import { existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { createApp, createRouter, defineEventHandler, toNodeListener } from 'h3'

test('Aims requirement bridge keeps tenant, actor, project and object boundaries', async () => {
  const root = resolve(import.meta.dirname, '../..'); const calls = []; const session = { authenticated: true, tokenUse: 'access', subjectType: 'user', uid: 'person-a', tenant: 'tenant-a', deployment: 'enterprise-test' }
  const oldConfig = globalThis.useRuntimeConfig; globalThis.useRuntimeConfig = () => ({ public: { appCode: 'enterprise' } })
  globalThis.__reqAllowed = true; globalThis.__reqTransport = async (_event, path, options) => { calls.push({ path, options }); return { handled: true, data: { code: 0, data: path.endsWith(':list') ? { items: [] } : { id: 34, projectId: 12 } } } }
  const hooks = registerHooks({ resolve(specifier, context, next) { let source; if (specifier.endsWith('/consoleSessionBridge')) source = 'export const resolveConsoleAuthWithSessionBridge=async()=>globalThis.__reqSession'; if (specifier.endsWith('/tenantRuntimeClient')) source = 'export const maybeCallTenantRuntime=(...args)=>globalThis.__reqTransport(...args);export const verifiedServiceCommandActor=()=>null;export const prepareTenantRuntime=async()=>true'; if (specifier.endsWith('/platformBundleAuthorization')) source = "export const loadAuthorizationSnapshotFromConsoleRuntime=async()=>({resources:globalThis.__reqAllowed?{requirements:['view']}:{},actionPolicies:{}});export const loadScopedAuthorizationFromConsoleRuntime=async()=>({grants:[{permissions:[{appCode:'aims',resourceCode:'projects',action:'admin'}],scopes:[{dimension:'project',predicate:'code',value:'PRJ-1'}]}]})"; if (specifier.endsWith('/directoryApi')) source = "export const fetchDirectoryApi=async()=>({code:0,data:{tree:[],flat:[]}})"; if (source) return { url:`data:text/javascript,${encodeURIComponent(source)}`,shortCircuit:true }; let candidate; if(specifier.startsWith('@hzy/foundation/'))candidate=resolve(root,'foundation',specifier.slice('@hzy/foundation/'.length));else if(specifier.startsWith('.')&&context.parentURL?.startsWith('file:'))candidate=resolve(dirname(fileURLToPath(context.parentURL)),specifier);if(candidate&&!existsSync(candidate)&&existsSync(`${candidate}.ts`))return{url:pathToFileURL(`${candidate}.ts`).href,shortCircuit:true};return next(specifier,context) } })
  globalThis.__reqSession=session; let server
  try { const app=createApp(),router=createRouter();app.use(defineEventHandler(event=>{event.context.consoleAuth=session}));router.get('/projects/:id/requirements',(await import('../server/routes/aims/api/v1/projects/[id]/requirements/index.get.ts')).default);router.get('/projects/:id/requirements/:requirementId',(await import('../server/routes/aims/api/v1/projects/[id]/requirements/[requirementId].get.ts')).default);app.use(router);server=createServer(toNodeListener(app));await new Promise(done=>server.listen(0,'127.0.0.1',done));const base=`http://127.0.0.1:${server.address().port}`
    globalThis.__reqAllowed=false;assert.equal((await fetch(`${base}/projects/12/requirements`)).status,403);assert.equal(calls.length,0);globalThis.__reqAllowed=true
    assert.equal((await fetch(`${base}/projects/12/requirements?search=login`)).status,200);const list=calls.at(-1);assert.equal(list.path,'/v1/enterprise/aims/project-requirements:list');assert.equal(list.options.scope,'aims:requirements:view');assert.equal(list.options.body.tenant,'tenant-a');assert.equal(list.options.body.authorization.actorUid,'person-a');assert.equal(list.options.body.query.current_user_project_admin_project_codes,'PRJ-1')
    assert.equal((await fetch(`${base}/projects/12/requirements/34`)).status,200);const detail=calls.at(-1);assert.equal(detail.options.body.projectId,'12');assert.equal(detail.options.body.requirementId,'34')
    for(const path of ['/projects/12/requirements?tenant=other','/projects/0/requirements','/projects/12/requirements/0','/projects/12/requirements/34?projectId=13']){const before=calls.length;assert.equal((await fetch(base+path)).status,400);assert.equal(calls.length,before)}
  } finally { if(server)await new Promise(done=>server.close(done));hooks.deregister();globalThis.useRuntimeConfig=oldConfig;delete globalThis.__reqSession;delete globalThis.__reqAllowed;delete globalThis.__reqTransport }
})
