-- Generated by aims/scripts/generate-product-center-grants.mjs; edit the generator, not this file.
-- Run only against the intended Console tenant database. This file does not access secrets.
-- Set @pc_aims_client_code / @pc_assets_client_code / @pc_codocs_client_code / @pc_altoc_client_code / @pc_finance_client_code to the actual enrolled client codes before execution.
-- Defaults select exact runtime clients, never every client sharing an app_code.
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
SET @pc_aims_client_code = COALESCE(@pc_aims_client_code, 'aims.runtime');
SET @pc_assets_client_code = COALESCE(@pc_assets_client_code, 'assets.runtime');
SET @pc_codocs_client_code = COALESCE(@pc_codocs_client_code, 'codocs.runtime');
SET @pc_altoc_client_code = COALESCE(@pc_altoc_client_code, 'altoc.runtime');
SET @pc_finance_client_code = COALESCE(@pc_finance_client_code, 'finance.runtime');

-- Read-only: returns one result per required client/audience/scope, even when
-- the client is absent. A PASS proves row/credential eligibility, not signing.
-- Both runtime audiences and existing transport scopes must pass. Afterwards
-- probe actual token issuance for every combined scope used by the BFF.
SELECT chosen.client_code,expected.audience,CONCAT(expected.resource_code,':',expected.action) capability,
 CASE WHEN sc.id IS NULL THEN 'FAIL: missing client'
 WHEN sc.app_code IS NULL OR sc.app_code<>expected.app_code OR sc.status<>'active' THEN 'FAIL: client binding/status'
 WHEN cr.id IS NULL OR cr.status<>'active' OR (cr.expires_at IS NOT NULL AND cr.expires_at<=UTC_TIMESTAMP()) THEN 'FAIL: current credential'
 WHEN g.id IS NULL OR g.status<>'active' THEN 'FAIL: missing/inactive exact grant'
 ELSE 'PASS' END result
FROM (SELECT 'altoc' app_code, 'data-runtime' audience, 'data-runtime:altoc:integration_operation' resource_code, 'execute' action, 1 install_grant
UNION ALL
SELECT 'altoc' app_code, 'data-runtime' audience, 'data-runtime:altoc:product-feedback' resource_code, 'update-status' action, 1 install_grant
UNION ALL
SELECT 'altoc' app_code, 'data-runtime' audience, 'data-runtime:altoc:product-feedback' resource_code, 'update-progress' action, 1 install_grant
UNION ALL
SELECT 'altoc' app_code, 'data-runtime' audience, 'data-runtime:altoc:service_ticket' resource_code, 'edit' action, 1 install_grant
UNION ALL
SELECT 'altoc' app_code, 'data-runtime' audience, 'data-runtime:altoc' resource_code, 'read' action, 0 install_grant
UNION ALL
SELECT 'altoc' app_code, 'data-runtime' audience, 'data-runtime:altoc' resource_code, 'write' action, 0 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:integration_operation' resource_code, 'execute' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-version-summary' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-cost-rules' resource_code, 'freeze' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-cost-rules' resource_code, 'status' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-request' resource_code, 'create-from-feedback' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:products' resource_code, 'authorization-object' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:products' resource_code, 'view' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:products' resource_code, 'edit' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:products' resource_code, 'onboard' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:products' resource_code, 'archive' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:products' resource_code, 'restore' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:products' resource_code, 'admin' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-versions' resource_code, 'create' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-versions' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-versions' resource_code, 'edit' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-versions' resource_code, 'scope-create' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-versions' resource_code, 'scope-edit' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-versions' resource_code, 'scope-deliver' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-versions' resource_code, 'scope-reopen' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-versions' resource_code, 'scope-visibility' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-versions' resource_code, 'scope-legacy-criteria' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-versions' resource_code, 'accept' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-versions' resource_code, 'publish' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-versions' resource_code, 'reopen' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-versions' resource_code, 'archive' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-versions' resource_code, 'delete' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-objectives' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-objectives' resource_code, 'create' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-objectives' resource_code, 'edit' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-objectives' resource_code, 'item-link' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-objectives' resource_code, 'cycle-map' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-objectives' resource_code, 'cycle-revoke' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-objectives' resource_code, 'observe' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-objectives' resource_code, 'activate' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-objectives' resource_code, 'close' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-objectives' resource_code, 'reopen' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-objectives' resource_code, 'archive' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-roadmaps' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-roadmaps' resource_code, 'window-edit' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-roadmaps' resource_code, 'commit' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-roadmaps' resource_code, 'view-create' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-roadmaps' resource_code, 'view-update' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-roadmaps' resource_code, 'view-delete' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-components' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-components' resource_code, 'create' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-components' resource_code, 'move' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-components' resource_code, 'edit' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-components' resource_code, 'delete' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-features' resource_code, 'create' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-features' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-features' resource_code, 'edit' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-features' resource_code, 'delete' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-features' resource_code, 'request-link' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-features' resource_code, 'lifecycle' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-features' resource_code, 'component-assign' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-requests' resource_code, 'create' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-requests' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-requests' resource_code, 'edit' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-requests' resource_code, 'decide' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-requests' resource_code, 'source-create' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-requests' resource_code, 'source-delete' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-requests' resource_code, 'merge' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-priorities' resource_code, 'create' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-priorities' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-priorities' resource_code, 'edit' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-priorities' resource_code, 'cycle-open' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-priorities' resource_code, 'cycle-close' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-priorities' resource_code, 'cycle-review' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-priorities' resource_code, 'budget-change' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-priorities' resource_code, 'withdraw' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-priorities' resource_code, 'consumption-confirm' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-priorities' resource_code, 'comment' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-priorities' resource_code, 'observe' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-priorities' resource_code, 'assess' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-priorities' resource_code, 'move' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-priorities' resource_code, 'select' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-priorities' resource_code, 'feature-link' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-priorities' resource_code, 'model-create' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-priorities' resource_code, 'reach-record' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-priorities' resource_code, 'rice-assess' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-priorities' resource_code, 'cycle-model-select' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-priorities' resource_code, 'cross-dependency-create' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-priorities' resource_code, 'cross-dependency-remove' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-priorities' resource_code, 'project-authorization' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-priorities' resource_code, 'handoff' action, 1 install_grant
UNION ALL
SELECT 'assets' app_code, 'data-runtime' audience, 'data-runtime:assets:product' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'assets' app_code, 'data-runtime' audience, 'data-runtime:assets:product-adoption' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'finance' app_code, 'data-runtime' audience, 'data-runtime:finance:product-cost' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'finance' app_code, 'data-runtime' audience, 'data-runtime:finance:product-cost' resource_code, 'replace-rules' action, 1 install_grant
UNION ALL
SELECT 'finance' app_code, 'data-runtime' audience, 'data-runtime:finance:product-cost' resource_code, 'read-rules' action, 1 install_grant
UNION ALL
SELECT 'finance' app_code, 'data-runtime' audience, 'data-runtime:finance' resource_code, 'read' action, 0 install_grant
UNION ALL
SELECT 'finance' app_code, 'data-runtime' audience, 'data-runtime:finance' resource_code, 'write' action, 0 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-documents' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-documents' resource_code, 'remove' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-documents' resource_code, 'edit' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-documents' resource_code, 'restore' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims:product-documents' resource_code, 'create' action, 1 install_grant
UNION ALL
SELECT 'codocs' app_code, 'data-runtime' audience, 'data-runtime:codocs:product-document' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'codocs' app_code, 'data-runtime' audience, 'data-runtime:codocs:product-document' resource_code, 'create' action, 1 install_grant
UNION ALL
SELECT 'codocs' app_code, 'data-runtime' audience, 'data-runtime:codocs' resource_code, 'read' action, 0 install_grant
UNION ALL
SELECT 'codocs' app_code, 'data-runtime' audience, 'data-runtime:codocs' resource_code, 'write' action, 0 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims' resource_code, 'read' action, 0 install_grant
UNION ALL
SELECT 'aims' app_code, 'data-runtime' audience, 'data-runtime:aims' resource_code, 'write' action, 0 install_grant
UNION ALL
SELECT 'assets' app_code, 'data-runtime' audience, 'data-runtime:assets' resource_code, 'read' action, 0 install_grant
UNION ALL
SELECT 'altoc' app_code, 'tenant-runtime' audience, 'tenant-runtime:altoc:integration_operation' resource_code, 'execute' action, 1 install_grant
UNION ALL
SELECT 'altoc' app_code, 'tenant-runtime' audience, 'tenant-runtime:altoc:product-feedback' resource_code, 'update-status' action, 1 install_grant
UNION ALL
SELECT 'altoc' app_code, 'tenant-runtime' audience, 'tenant-runtime:altoc:product-feedback' resource_code, 'update-progress' action, 1 install_grant
UNION ALL
SELECT 'altoc' app_code, 'tenant-runtime' audience, 'tenant-runtime:altoc:service_ticket' resource_code, 'edit' action, 1 install_grant
UNION ALL
SELECT 'altoc' app_code, 'tenant-runtime' audience, 'tenant-runtime:altoc' resource_code, 'read' action, 0 install_grant
UNION ALL
SELECT 'altoc' app_code, 'tenant-runtime' audience, 'tenant-runtime:altoc' resource_code, 'write' action, 0 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:integration_operation' resource_code, 'execute' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-version-summary' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-cost-rules' resource_code, 'freeze' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-cost-rules' resource_code, 'status' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-request' resource_code, 'create-from-feedback' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:products' resource_code, 'authorization-object' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:products' resource_code, 'view' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:products' resource_code, 'edit' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:products' resource_code, 'onboard' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:products' resource_code, 'archive' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:products' resource_code, 'restore' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:products' resource_code, 'admin' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-versions' resource_code, 'create' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-versions' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-versions' resource_code, 'edit' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-versions' resource_code, 'scope-create' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-versions' resource_code, 'scope-edit' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-versions' resource_code, 'scope-deliver' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-versions' resource_code, 'scope-reopen' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-versions' resource_code, 'scope-visibility' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-versions' resource_code, 'scope-legacy-criteria' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-versions' resource_code, 'accept' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-versions' resource_code, 'publish' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-versions' resource_code, 'reopen' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-versions' resource_code, 'archive' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-versions' resource_code, 'delete' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-objectives' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-objectives' resource_code, 'create' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-objectives' resource_code, 'edit' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-objectives' resource_code, 'item-link' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-objectives' resource_code, 'cycle-map' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-objectives' resource_code, 'cycle-revoke' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-objectives' resource_code, 'observe' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-objectives' resource_code, 'activate' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-objectives' resource_code, 'close' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-objectives' resource_code, 'reopen' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-objectives' resource_code, 'archive' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-roadmaps' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-roadmaps' resource_code, 'window-edit' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-roadmaps' resource_code, 'commit' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-roadmaps' resource_code, 'view-create' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-roadmaps' resource_code, 'view-update' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-roadmaps' resource_code, 'view-delete' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-components' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-components' resource_code, 'create' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-components' resource_code, 'move' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-components' resource_code, 'edit' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-components' resource_code, 'delete' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-features' resource_code, 'create' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-features' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-features' resource_code, 'edit' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-features' resource_code, 'delete' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-features' resource_code, 'request-link' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-features' resource_code, 'lifecycle' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-features' resource_code, 'component-assign' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-requests' resource_code, 'create' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-requests' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-requests' resource_code, 'edit' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-requests' resource_code, 'decide' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-requests' resource_code, 'source-create' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-requests' resource_code, 'source-delete' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-requests' resource_code, 'merge' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-priorities' resource_code, 'create' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-priorities' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-priorities' resource_code, 'edit' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-priorities' resource_code, 'cycle-open' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-priorities' resource_code, 'cycle-close' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-priorities' resource_code, 'cycle-review' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-priorities' resource_code, 'budget-change' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-priorities' resource_code, 'withdraw' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-priorities' resource_code, 'consumption-confirm' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-priorities' resource_code, 'comment' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-priorities' resource_code, 'observe' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-priorities' resource_code, 'assess' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-priorities' resource_code, 'move' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-priorities' resource_code, 'select' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-priorities' resource_code, 'feature-link' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-priorities' resource_code, 'model-create' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-priorities' resource_code, 'reach-record' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-priorities' resource_code, 'rice-assess' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-priorities' resource_code, 'cycle-model-select' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-priorities' resource_code, 'cross-dependency-create' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-priorities' resource_code, 'cross-dependency-remove' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-priorities' resource_code, 'project-authorization' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-priorities' resource_code, 'handoff' action, 1 install_grant
UNION ALL
SELECT 'assets' app_code, 'tenant-runtime' audience, 'tenant-runtime:assets:product' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'assets' app_code, 'tenant-runtime' audience, 'tenant-runtime:assets:product-adoption' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'finance' app_code, 'tenant-runtime' audience, 'tenant-runtime:finance:product-cost' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'finance' app_code, 'tenant-runtime' audience, 'tenant-runtime:finance:product-cost' resource_code, 'replace-rules' action, 1 install_grant
UNION ALL
SELECT 'finance' app_code, 'tenant-runtime' audience, 'tenant-runtime:finance:product-cost' resource_code, 'read-rules' action, 1 install_grant
UNION ALL
SELECT 'finance' app_code, 'tenant-runtime' audience, 'tenant-runtime:finance' resource_code, 'read' action, 0 install_grant
UNION ALL
SELECT 'finance' app_code, 'tenant-runtime' audience, 'tenant-runtime:finance' resource_code, 'write' action, 0 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-documents' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-documents' resource_code, 'remove' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-documents' resource_code, 'edit' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-documents' resource_code, 'restore' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims:product-documents' resource_code, 'create' action, 1 install_grant
UNION ALL
SELECT 'codocs' app_code, 'tenant-runtime' audience, 'tenant-runtime:codocs:product-document' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'codocs' app_code, 'tenant-runtime' audience, 'tenant-runtime:codocs:product-document' resource_code, 'create' action, 1 install_grant
UNION ALL
SELECT 'codocs' app_code, 'tenant-runtime' audience, 'tenant-runtime:codocs' resource_code, 'read' action, 0 install_grant
UNION ALL
SELECT 'codocs' app_code, 'tenant-runtime' audience, 'tenant-runtime:codocs' resource_code, 'write' action, 0 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims' resource_code, 'read' action, 0 install_grant
UNION ALL
SELECT 'aims' app_code, 'tenant-runtime' audience, 'tenant-runtime:aims' resource_code, 'write' action, 0 install_grant
UNION ALL
SELECT 'assets' app_code, 'tenant-runtime' audience, 'tenant-runtime:assets' resource_code, 'read' action, 0 install_grant
UNION ALL
SELECT 'altoc' app_code, 'aims' audience, 'aims:product-request' resource_code, 'create-from-feedback' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'altoc' audience, 'altoc:product-feedback' resource_code, 'update-status' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'altoc' audience, 'altoc:product-feedback' resource_code, 'update-progress' action, 1 install_grant
UNION ALL
SELECT 'assets' app_code, 'aims' audience, 'aims:product-version-summary' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'assets' app_code, 'codocs' audience, 'codocs:product-document' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'assets' audience, 'assets:product' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'assets' audience, 'assets:product-adoption' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'finance' audience, 'finance:product-cost' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'finance' audience, 'finance:product-cost' resource_code, 'replace-rules' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'finance' audience, 'finance:product-cost' resource_code, 'read-rules' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'codocs' audience, 'codocs:product-document' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'codocs' audience, 'codocs:product-document' resource_code, 'create' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'console' audience, 'console:directory-users' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'aims' app_code, 'console' audience, 'console:subject-authorization' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'assets' app_code, 'console' audience, 'console:subject-authorization' resource_code, 'read' action, 1 install_grant
UNION ALL
SELECT 'finance' app_code, 'console' audience, 'console:subject-authorization' resource_code, 'read' action, 1 install_grant) expected
JOIN (SELECT 'aims' app_code, @pc_aims_client_code client_code UNION ALL SELECT 'assets', @pc_assets_client_code UNION ALL SELECT 'codocs', @pc_codocs_client_code UNION ALL SELECT 'altoc', @pc_altoc_client_code UNION ALL SELECT 'finance', @pc_finance_client_code) chosen ON chosen.app_code=expected.app_code
LEFT JOIN service_clients sc ON BINARY sc.client_code=BINARY chosen.client_code
LEFT JOIN service_client_credentials cr ON cr.id=sc.current_credential_id AND cr.service_client_id=sc.id
LEFT JOIN service_client_grants g ON g.service_client_id=sc.id AND BINARY g.resource_code=BINARY expected.resource_code AND BINARY g.action=BINARY expected.action
ORDER BY chosen.client_code,expected.audience,capability;
