-- 孤儿 grant 识别：生产持有、但代码里没有任何出站调用会请求的 active grant
-- 只读；不删除任何数据。
--
-- 判定依据：各应用 server/ 目录中真正的出站调用（requestServiceAccessToken /
-- requestWithServiceAccessToken / maybeCallTenantRuntime / call*Runtime 等）请求的 scope，
-- 已排除入站要求（requireServiceScope / serviceAuthPolicy / serviceCapabilityRequirement）——
-- 入站要求的 grant 属于调用方，不属于本应用。
--
-- 只检查 7 个业务应用；console.runtime / connector-runtime / notification-runtime /
-- directory-connector 是自动 provision 的基础设施身份，不在清理范围。
--
-- 注意：结果是**候选**不是结论。删除前仍需逐条在代码库中确认没有动态拼接的用法。

SELECT
  c.`app_code`,
  c.`client_code`,
  CONCAT(g.`resource_code`, ':', g.`action`) AS `granted_scope`,
  JSON_UNQUOTE(JSON_EXTRACT(g.`scope_json`, '$.source')) AS `source`,
  g.`updated_at`
FROM `service_client_grants` g
JOIN `service_clients` c ON c.`id` = g.`service_client_id`
LEFT JOIN (
  SELECT 'aims' AS `app_code`, 'aims:integration_operation:execute' AS `scope`
  UNION ALL SELECT 'aims', 'aims:read'
  UNION ALL SELECT 'aims', 'aims:service-ticket:work-item:create'
  UNION ALL SELECT 'aims', 'aims:write'
  UNION ALL SELECT 'aims', 'altoc:receivable:mark-billable'
  UNION ALL SELECT 'aims', 'altoc:service-ticket:delivery-result:sync'
  UNION ALL SELECT 'aims', 'assets:read'
  UNION ALL SELECT 'aims', 'assets:write'
  UNION ALL SELECT 'aims', 'codocs:company-weekly-summary:publish'
  UNION ALL SELECT 'aims', 'codocs:department-documents:list'
  UNION ALL SELECT 'aims', 'codocs:project-document:content:read'
  UNION ALL SELECT 'aims', 'console:authorization-role-holders:read'
  UNION ALL SELECT 'aims', 'data-runtime:aims:integration_operation:execute'
  UNION ALL SELECT 'aims', 'data-runtime:aims:read'
  UNION ALL SELECT 'aims', 'data-runtime:aims:service-ticket:work-item:create'
  UNION ALL SELECT 'aims', 'data-runtime:aims:write'
  UNION ALL SELECT 'aims', 'data-runtime:altoc:receivable:mark-billable'
  UNION ALL SELECT 'aims', 'data-runtime:altoc:service-ticket:delivery-result:sync'
  UNION ALL SELECT 'aims', 'data-runtime:assets:read'
  UNION ALL SELECT 'aims', 'data-runtime:assets:write'
  UNION ALL SELECT 'aims', 'data-runtime:codocs:company-weekly-summary:publish'
  UNION ALL SELECT 'aims', 'data-runtime:codocs:department-documents:list'
  UNION ALL SELECT 'aims', 'data-runtime:codocs:project-document:content:read'
  UNION ALL SELECT 'aims', 'data-runtime:console:authorization-role-holders:read'
  UNION ALL SELECT 'aims', 'data-runtime:people:write'
  UNION ALL SELECT 'aims', 'data-runtime:system_settings:view'
  UNION ALL SELECT 'aims', 'data-runtime:workflow:action_defs:sync'
  UNION ALL SELECT 'aims', 'data-runtime:workflow:instances:read'
  UNION ALL SELECT 'aims', 'people:write'
  UNION ALL SELECT 'aims', 'system_settings:view'
  UNION ALL SELECT 'aims', 'tenant-runtime:aims:integration_operation:execute'
  UNION ALL SELECT 'aims', 'tenant-runtime:aims:read'
  UNION ALL SELECT 'aims', 'tenant-runtime:aims:service-ticket:work-item:create'
  UNION ALL SELECT 'aims', 'tenant-runtime:aims:write'
  UNION ALL SELECT 'aims', 'tenant-runtime:altoc:receivable:mark-billable'
  UNION ALL SELECT 'aims', 'tenant-runtime:altoc:service-ticket:delivery-result:sync'
  UNION ALL SELECT 'aims', 'tenant-runtime:assets:read'
  UNION ALL SELECT 'aims', 'tenant-runtime:assets:write'
  UNION ALL SELECT 'aims', 'tenant-runtime:codocs:company-weekly-summary:publish'
  UNION ALL SELECT 'aims', 'tenant-runtime:codocs:department-documents:list'
  UNION ALL SELECT 'aims', 'tenant-runtime:codocs:project-document:content:read'
  UNION ALL SELECT 'aims', 'tenant-runtime:console:authorization-role-holders:read'
  UNION ALL SELECT 'aims', 'tenant-runtime:people:write'
  UNION ALL SELECT 'aims', 'tenant-runtime:system_settings:view'
  UNION ALL SELECT 'aims', 'tenant-runtime:workflow:action_defs:sync'
  UNION ALL SELECT 'aims', 'tenant-runtime:workflow:instances:read'
  UNION ALL SELECT 'aims', 'workflow:action_defs:sync'
  UNION ALL SELECT 'aims', 'workflow:instances:read'
  UNION ALL SELECT 'altoc', 'aims:read'
  UNION ALL SELECT 'altoc', 'aims:project:create-from-opportunity'
  UNION ALL SELECT 'altoc', 'data-runtime:aims:project:create-from-opportunity'
  UNION ALL SELECT 'altoc', 'tenant-runtime:aims:project:create-from-opportunity'
  UNION ALL SELECT 'altoc', 'altoc:contract:admin'
  UNION ALL SELECT 'altoc', 'altoc:contract:delivery-asset-status:sync'
  UNION ALL SELECT 'altoc', 'altoc:contract:edit'
  UNION ALL SELECT 'altoc', 'altoc:contract:view'
  UNION ALL SELECT 'altoc', 'altoc:customer:view'
  UNION ALL SELECT 'altoc', 'altoc:integration_operation:execute'
  UNION ALL SELECT 'altoc', 'altoc:lead:assign'
  UNION ALL SELECT 'altoc', 'altoc:lead:edit'
  UNION ALL SELECT 'altoc', 'altoc:opportunity:assign'
  UNION ALL SELECT 'altoc', 'altoc:opportunity:edit'
  UNION ALL SELECT 'altoc', 'altoc:read'
  UNION ALL SELECT 'altoc', 'altoc:receivable:edit'
  UNION ALL SELECT 'altoc', 'altoc:service_ticket:edit'
  UNION ALL SELECT 'altoc', 'altoc:service_ticket:view'
  UNION ALL SELECT 'altoc', 'altoc:write'
  UNION ALL SELECT 'altoc', 'assets:read'
  UNION ALL SELECT 'altoc', 'assets:write'
  UNION ALL SELECT 'altoc', 'codocs:documents:read'
  UNION ALL SELECT 'altoc', 'data-runtime:aims:read'
  UNION ALL SELECT 'altoc', 'data-runtime:altoc:contract:admin'
  UNION ALL SELECT 'altoc', 'data-runtime:altoc:contract:delivery-asset-status:sync'
  UNION ALL SELECT 'altoc', 'data-runtime:altoc:contract:edit'
  UNION ALL SELECT 'altoc', 'data-runtime:altoc:contract:view'
  UNION ALL SELECT 'altoc', 'data-runtime:altoc:customer:view'
  UNION ALL SELECT 'altoc', 'data-runtime:altoc:integration_operation:execute'
  UNION ALL SELECT 'altoc', 'data-runtime:altoc:lead:assign'
  UNION ALL SELECT 'altoc', 'data-runtime:altoc:lead:edit'
  UNION ALL SELECT 'altoc', 'data-runtime:altoc:opportunity:assign'
  UNION ALL SELECT 'altoc', 'data-runtime:altoc:opportunity:edit'
  UNION ALL SELECT 'altoc', 'data-runtime:altoc:read'
  UNION ALL SELECT 'altoc', 'data-runtime:altoc:receivable:edit'
  UNION ALL SELECT 'altoc', 'data-runtime:altoc:service_ticket:edit'
  UNION ALL SELECT 'altoc', 'data-runtime:altoc:service_ticket:view'
  UNION ALL SELECT 'altoc', 'data-runtime:altoc:write'
  UNION ALL SELECT 'altoc', 'data-runtime:assets:read'
  UNION ALL SELECT 'altoc', 'data-runtime:assets:write'
  UNION ALL SELECT 'altoc', 'data-runtime:codocs:documents:read'
  UNION ALL SELECT 'altoc', 'data-runtime:finance:read'
  UNION ALL SELECT 'altoc', 'finance:read'
  UNION ALL SELECT 'altoc', 'tenant-runtime:aims:read'
  UNION ALL SELECT 'altoc', 'tenant-runtime:altoc:contract:admin'
  UNION ALL SELECT 'altoc', 'tenant-runtime:altoc:contract:delivery-asset-status:sync'
  UNION ALL SELECT 'altoc', 'tenant-runtime:altoc:contract:edit'
  UNION ALL SELECT 'altoc', 'tenant-runtime:altoc:contract:view'
  UNION ALL SELECT 'altoc', 'tenant-runtime:altoc:customer:view'
  UNION ALL SELECT 'altoc', 'tenant-runtime:altoc:integration_operation:execute'
  UNION ALL SELECT 'altoc', 'tenant-runtime:altoc:lead:assign'
  UNION ALL SELECT 'altoc', 'tenant-runtime:altoc:lead:edit'
  UNION ALL SELECT 'altoc', 'tenant-runtime:altoc:opportunity:assign'
  UNION ALL SELECT 'altoc', 'tenant-runtime:altoc:opportunity:edit'
  UNION ALL SELECT 'altoc', 'tenant-runtime:altoc:read'
  UNION ALL SELECT 'altoc', 'tenant-runtime:altoc:receivable:edit'
  UNION ALL SELECT 'altoc', 'tenant-runtime:altoc:service_ticket:edit'
  UNION ALL SELECT 'altoc', 'tenant-runtime:altoc:service_ticket:view'
  UNION ALL SELECT 'altoc', 'tenant-runtime:altoc:write'
  UNION ALL SELECT 'altoc', 'tenant-runtime:assets:read'
  UNION ALL SELECT 'altoc', 'tenant-runtime:assets:write'
  UNION ALL SELECT 'altoc', 'tenant-runtime:codocs:documents:read'
  UNION ALL SELECT 'altoc', 'tenant-runtime:finance:read'
  UNION ALL SELECT 'assets', 'aims:read'
  UNION ALL SELECT 'assets', 'altoc:contract:delivery-asset-status:sync'
  UNION ALL SELECT 'assets', 'assets:integration_operation:execute'
  UNION ALL SELECT 'assets', 'assets:read'
  UNION ALL SELECT 'assets', 'assets:write'
  UNION ALL SELECT 'assets', 'data-runtime:aims:read'
  UNION ALL SELECT 'assets', 'data-runtime:altoc:contract:delivery-asset-status:sync'
  UNION ALL SELECT 'assets', 'data-runtime:assets:integration_operation:execute'
  UNION ALL SELECT 'assets', 'data-runtime:assets:read'
  UNION ALL SELECT 'assets', 'data-runtime:assets:write'
  UNION ALL SELECT 'assets', 'tenant-runtime:aims:read'
  UNION ALL SELECT 'assets', 'tenant-runtime:altoc:contract:delivery-asset-status:sync'
  UNION ALL SELECT 'assets', 'tenant-runtime:assets:integration_operation:execute'
  UNION ALL SELECT 'assets', 'tenant-runtime:assets:read'
  UNION ALL SELECT 'assets', 'tenant-runtime:assets:write'
  UNION ALL SELECT 'codocs', 'codocs:read'
  UNION ALL SELECT 'codocs', 'codocs:write'
  UNION ALL SELECT 'codocs', 'console:directory-project-access:read'
  UNION ALL SELECT 'codocs', 'console:directory-users:read'
  UNION ALL SELECT 'codocs', 'data-runtime:codocs:read'
  UNION ALL SELECT 'codocs', 'data-runtime:codocs:write'
  UNION ALL SELECT 'codocs', 'data-runtime:console:directory-project-access:read'
  UNION ALL SELECT 'codocs', 'data-runtime:console:directory-users:read'
  UNION ALL SELECT 'codocs', 'data-runtime:workflow:document-publish:create'
  UNION ALL SELECT 'codocs', 'tenant-runtime:codocs:read'
  UNION ALL SELECT 'codocs', 'tenant-runtime:codocs:write'
  UNION ALL SELECT 'codocs', 'tenant-runtime:console:directory-project-access:read'
  UNION ALL SELECT 'codocs', 'tenant-runtime:console:directory-users:read'
  UNION ALL SELECT 'codocs', 'tenant-runtime:workflow:document-publish:create'
  UNION ALL SELECT 'codocs', 'workflow:document-publish:create'
  UNION ALL SELECT 'finance', 'aims:read'
  UNION ALL SELECT 'finance', 'altoc:contract:finance-summary:sync'
  UNION ALL SELECT 'finance', 'data-runtime:aims:read'
  UNION ALL SELECT 'finance', 'data-runtime:altoc:contract:finance-summary:sync'
  UNION ALL SELECT 'finance', 'data-runtime:finance:integration_operation:execute'
  UNION ALL SELECT 'finance', 'data-runtime:finance:read'
  UNION ALL SELECT 'finance', 'data-runtime:finance:settings.read'
  UNION ALL SELECT 'finance', 'data-runtime:finance:write'
  UNION ALL SELECT 'finance', 'data-runtime:people:read'
  UNION ALL SELECT 'finance', 'data-runtime:system_settings:view'
  UNION ALL SELECT 'finance', 'data-runtime:workflow:invoice-request:create'
  UNION ALL SELECT 'finance', 'data-runtime:workflow:proxy'
  UNION ALL SELECT 'finance', 'finance:integration_operation:execute'
  UNION ALL SELECT 'finance', 'finance:read'
  UNION ALL SELECT 'finance', 'finance:settings.read'
  UNION ALL SELECT 'finance', 'finance:write'
  UNION ALL SELECT 'finance', 'people:read'
  UNION ALL SELECT 'finance', 'system_settings:view'
  UNION ALL SELECT 'finance', 'tenant-runtime:aims:read'
  UNION ALL SELECT 'finance', 'tenant-runtime:altoc:contract:finance-summary:sync'
  UNION ALL SELECT 'finance', 'tenant-runtime:finance:integration_operation:execute'
  UNION ALL SELECT 'finance', 'tenant-runtime:finance:read'
  UNION ALL SELECT 'finance', 'tenant-runtime:finance:settings.read'
  UNION ALL SELECT 'finance', 'tenant-runtime:finance:write'
  UNION ALL SELECT 'finance', 'tenant-runtime:people:read'
  UNION ALL SELECT 'finance', 'tenant-runtime:system_settings:view'
  UNION ALL SELECT 'finance', 'tenant-runtime:workflow:invoice-request:create'
  UNION ALL SELECT 'finance', 'tenant-runtime:workflow:proxy'
  UNION ALL SELECT 'finance', 'workflow:invoice-request:create'
  UNION ALL SELECT 'finance', 'workflow:proxy'
  UNION ALL SELECT 'people', 'aims:read'
  UNION ALL SELECT 'people', 'assets:offboarding-recovery:sync'
  UNION ALL SELECT 'people', 'console_directory:write'
  UNION ALL SELECT 'people', 'data-runtime:aims:read'
  UNION ALL SELECT 'people', 'data-runtime:assets:offboarding-recovery:sync'
  UNION ALL SELECT 'people', 'data-runtime:console_directory:write'
  UNION ALL SELECT 'people', 'data-runtime:finance:read'
  UNION ALL SELECT 'people', 'data-runtime:people:integration_operation:execute'
  UNION ALL SELECT 'people', 'data-runtime:people:read'
  UNION ALL SELECT 'people', 'data-runtime:people:write'
  UNION ALL SELECT 'people', 'data-runtime:system_settings:view'
  UNION ALL SELECT 'people', 'finance:read'
  UNION ALL SELECT 'people', 'people:integration_operation:execute'
  UNION ALL SELECT 'people', 'people:read'
  UNION ALL SELECT 'people', 'people:write'
  UNION ALL SELECT 'people', 'system_settings:view'
  UNION ALL SELECT 'people', 'tenant-runtime:aims:read'
  UNION ALL SELECT 'people', 'tenant-runtime:assets:offboarding-recovery:sync'
  UNION ALL SELECT 'people', 'tenant-runtime:console_directory:write'
  UNION ALL SELECT 'people', 'tenant-runtime:finance:read'
  UNION ALL SELECT 'people', 'tenant-runtime:people:integration_operation:execute'
  UNION ALL SELECT 'people', 'tenant-runtime:people:read'
  UNION ALL SELECT 'people', 'tenant-runtime:people:write'
  UNION ALL SELECT 'people', 'tenant-runtime:system_settings:view'
  UNION ALL SELECT 'workflow', 'console:authorization-role-holders:read'
  UNION ALL SELECT 'workflow', 'data-runtime:console:authorization-role-holders:read'
  UNION ALL SELECT 'workflow', 'data-runtime:workflow:callback'
  UNION ALL SELECT 'workflow', 'tenant-runtime:console:authorization-role-holders:read'
  UNION ALL SELECT 'workflow', 'tenant-runtime:workflow:callback'
  UNION ALL SELECT 'workflow', 'workflow:callback'
) needed
  ON needed.`app_code` = c.`app_code`
 AND needed.`scope` = CONCAT(g.`resource_code`, ':', g.`action`)
WHERE g.`status` = 'active'
  AND c.`status` = 'active'
  AND c.`app_code` IN ('aims','altoc','people','workflow','finance','assets','codocs')
  AND needed.`scope` IS NULL
ORDER BY c.`app_code`, `granted_scope`;
