<script setup lang="ts">
import { renderSafeMarkdown } from '../../shared/utils/safeMarkdown'

const props = defineProps<{ content: string }>()
const html = computed(() => renderSafeMarkdown(props.content))
</script>

<template>
  <!-- Renderer disables raw HTML/images and rejects dangerous link protocols. -->
  <!-- eslint-disable-next-line vue/no-v-html -- HTML is generated by the tested html:false Markdown renderer. -->
  <div class="safe-markdown min-w-0 break-words" v-html="html" />
</template>

<style scoped>
.safe-markdown { line-height: 1.8; overflow-wrap: anywhere; }
.safe-markdown :deep(h1), .safe-markdown :deep(h2), .safe-markdown :deep(h3) { font-weight: 650; margin: 1.4em 0 .6em; line-height: 1.4; }
.safe-markdown :deep(h1) { font-size: 1.7em; }
.safe-markdown :deep(h2) { font-size: 1.3em; }
.safe-markdown :deep(p), .safe-markdown :deep(ul), .safe-markdown :deep(ol) { margin: .8em 0; }
.safe-markdown :deep(ul) { list-style: disc; padding-left: 1.4em; }
.safe-markdown :deep(ol) { list-style: decimal; padding-left: 1.4em; }
.safe-markdown :deep(a) { color: var(--ui-primary); text-decoration: underline; }
.safe-markdown :deep(pre) { white-space: pre-wrap; background: var(--ui-bg-muted); padding: 1em; border-radius: .5em; }
.safe-markdown :deep(table) { display: block; overflow-x: auto; border-collapse: collapse; }
.safe-markdown :deep(td), .safe-markdown :deep(th) { border: 1px solid var(--ui-border); padding: .5em; min-width: 7em; }
</style>
