import { createError, getHeader, getQuery, getRequestURL, type H3Event } from 'h3'
import { readRequestBodyCompat } from './requestBody'
import { measureRequestStage } from './performanceTiming'
import { $fetch as fetchExternal } from 'ofetch'
import { requestServiceAccessToken } from './serviceOidc'
import { isTenantRuntimeProfile, resolveDeploymentProfile } from './deploymentProfile'
import { tenantRuntimeErrorData, type TenantRuntimeErrorEnvelope } from './tenantRuntimeErrors'

export type TenantRuntimeMethod = 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE'

export type TenantRuntimeCallOptions = {
  appCode: string
  scope: string
  /**
   * Stable mutation key generated by a trusted server-side caller when the
   * inbound browser request does not already carry one.
   */
  idempotencyKey?: string
  /**
   * Bootstrap-only calls must enter through an enrolled Runtime token (static
   * config or trusted Tenant Gateway injection). The bootstrap token itself is
   * valid only for `console:service-token:issue`; other bootstrap operations
   * first exchange it for an exactly scoped short-lived Console service token.
   */
  requireStaticRuntimeToken?: boolean
  /**
   * Cross-app target BFFs use their credential policy for the target runtime
   * identity instead of accidentally reusing the source app's gateway binding.
   */
  serviceTokenSourceBinding?: 'trusted-gateway' | 'service-client-policy'
  /**
   * Trusted server-side callers may raise the 10-second default for a typed
   * operation whose bounded work is known to take longer.
   */
  timeoutMs?: number
  method?: string
  query?: Record<string, unknown>
  body?: unknown
  notificationDetailActor?: {
    uid: string
    tenantId: string
    deploymentId: string
  }
  serviceCommandActor?: {
    uid: string
  }
  /**
   * A browser actor that a business application has already authenticated and
   * delegated through Workflow's `workflow:proxy` service boundary.  This is
   * deliberately narrower than a generic actor override: it can only drive
   * Workflow runtime calls and is re-validated against the inbound service
   * token before the tenant-runtime HMAC delegation is created.
   */
  workflowProxyActor?: {
    uid: string
  }
}

export type TenantRuntimeSkipped = {
  handled: false
}

export type TenantRuntimeHandled<T> = {
  handled: true
  data: T
}

export type TenantRuntimeResolutionOptions = {
  includeGlobal?: boolean
}

export interface TenantRuntimePageEnvelope<T> {
  data: T[]
  total: number
  page: number
  pageSize: number
  summary?: Record<string, unknown>
}

type TenantRuntimeActorAuth = {
  authenticated?: boolean
  uid?: string | null
  subjectType?: string | null
  deptCode?: string | null
  deptCodes?: string[] | string | null
  claims?: Record<string, unknown> | null
  tokenUse?: string | null
  appCode?: string | null
  clientCode?: string | null
  scopes?: string[] | string | null
  tenant?: string | null
  deployment?: string | null
}

type PlatformRuntimeBootstrapResponse = {
  data?: {
    token?: unknown
    expiresAt?: unknown
    tenantCode?: unknown
    deploymentCode?: unknown
    appCode?: unknown
  }
}

const platformRuntimeBootstrapCache = new Map<string, { token: string, expiresAt: number }>()
const workerServiceUserAgent = 'HZY-Cloudflare-Worker/1.0'

function safeJwtMetadata(token: string) {
  try {
    const [encodedHeader, encodedPayload] = token.split('.')
    if (!encodedHeader || !encodedPayload) return { format: 'opaque' }
    const header = JSON.parse(Buffer.from(encodedHeader, 'base64url').toString('utf8')) as Record<string, unknown>
    const payload = JSON.parse(Buffer.from(encodedPayload, 'base64url').toString('utf8')) as Record<string, unknown>
    const hzy = payload.hzy && typeof payload.hzy === 'object' && !Array.isArray(payload.hzy)
      ? payload.hzy as Record<string, unknown>
      : {}
    return {
      format: 'jwt',
      kid: stringValue(header.kid),
      alg: stringValue(header.alg),
      issuer: stringValue(payload.iss),
      audience: Array.isArray(payload.aud) ? payload.aud.map(stringValue) : stringValue(payload.aud),
      tokenUse: stringValue(payload.token_use),
      tenant: stringValue(payload.tenant || payload.tenant_code || payload.tenantCode),
      deployment: stringValue(payload.deployment || payload.deployment_code || payload.deploymentCode),
      appCode: stringValue(payload.appCode || payload.app_code || hzy.appCode),
      scope: Array.isArray(payload.scope) ? payload.scope.map(stringValue) : stringValue(payload.scope),
      issuedAt: Number(payload.iat || 0),
      expiresAt: Number(payload.exp || 0),
      observedAt: Math.floor(Date.now() / 1000)
    }
  } catch {
    return { format: 'unparseable' }
  }
}

function safeUpstreamResponseMetadata(error: unknown) {
  const response = (error as {
    response?: {
      headers?: Headers | Record<string, unknown>
    }
  })?.response
  const headers = response?.headers
  const headerValue = (name: string) => {
    if (!headers) return ''
    if (typeof (headers as Headers).get === 'function') {
      return stringValue((headers as Headers).get(name))
    }
    const record = headers as Record<string, unknown>
    return stringValue(record[name] || record[name.toLowerCase()])
  }
  const data = (error as { data?: unknown })?.data
  const responseText = typeof data === 'string'
    ? data.replace(/<[^>]*>/gu, ' ').replace(/\s+/gu, ' ').trim()
    : ''
  const title = typeof data === 'string'
    ? stringValue(data.match(/<title[^>]*>([^<]{1,160})<\/title>/iu)?.[1])
    : ''
  const cloudflareErrorCode = responseText.match(/\b(?:error\s+code|cloudflare)\D{0,24}(\d{3,4})\b/iu)?.[1] || ''
  return {
    server: headerValue('server'),
    contentType: headerValue('content-type'),
    cfRay: headerValue('cf-ray'),
    title,
    cloudflareErrorCode,
    responseSummary: responseText.slice(0, 240),
    responseShape: Array.isArray(data)
      ? 'array'
      : data === null
        ? 'null'
        : typeof data
  }
}

export function isPlatformRuntimeBootstrapToken(token: string) {
  const metadata = safeJwtMetadata(token) as Record<string, unknown>
  return metadata.format === 'jwt'
    && metadata.tokenUse === 'platform_runtime_bootstrap'
}

function serviceAuthScopes(auth: TenantRuntimeActorAuth) {
  const scopes = new Set<string>()
  const rawScopes = auth.claims?.scope
  const authScopes = auth.scopes
  for (const item of [
    ...(Array.isArray(rawScopes) ? rawScopes : String(rawScopes || '').split(/\s+/)),
    ...(Array.isArray(authScopes) ? authScopes : String(authScopes || '').split(/\s+/))
  ]) {
    const scope = stringValue(item)
    if (scope) scopes.add(scope)
  }
  return scopes
}

function trustedNotificationDetailActor(input: {
  event: H3Event
  path: string
  options: TenantRuntimeCallOptions
  tenant: string
  deployment: string
}) {
  const delegation = input.options.notificationDetailActor
  if (!delegation) return ''

  const auth = input.event.context.consoleAuth as TenantRuntimeActorAuth | undefined
  const sourceApp = stringValue(auth?.appCode || auth?.clientCode).replace(/\.runtime$/u, '')
  const expectedScope = `${input.options.appCode}:notification-details:authorize`
  const expectedPath = `/v1/${input.options.appCode}/notification-details/authorize`
  const uid = stringValue(delegation.uid)
  const tenantId = stringValue(delegation.tenantId)
  const deploymentId = stringValue(delegation.deploymentId)
  const hasControlCharacter = [...uid].some((character) => {
    const code = character.codePointAt(0) || 0
    return code < 32 || code === 127
  })

  if (
    !auth?.authenticated
    || auth.subjectType !== 'service'
    || auth.tokenUse !== 'service'
    || sourceApp !== 'console'
    || !serviceAuthScopes(auth).has(expectedScope)
    || String(input.options.method || 'GET').toUpperCase() !== 'POST'
    || input.path !== expectedPath
    || !uid
    || uid.length > 191
    || hasControlCharacter
    || !tenantId
    || tenantId !== stringValue(auth.tenant)
    || tenantId !== input.tenant
    || !deploymentId
    || deploymentId !== stringValue(auth.deployment)
    || deploymentId !== input.deployment
  ) {
    throw createError({ statusCode: 403, message: 'Trusted notification detail actor delegation is invalid.' })
  }
  return uid
}

function trustedServiceCommandActor(input: {
  event: H3Event
  options: TenantRuntimeCallOptions
  envelope: Record<string, unknown> | null
}) {
  const uid = stringValue(input.options.serviceCommandActor?.uid)
  if (!uid || !input.envelope) return ''
  const auth = input.event.context.consoleAuth as TenantRuntimeActorAuth | undefined
  const sourceApp = stringValue(auth?.appCode || auth?.clientCode).replace(/\.runtime$/u, '')
  const command = input.envelope.command as Record<string, unknown> | undefined
  const capability = stringValue(input.envelope.requiredCapability)
  if (
    !auth?.authenticated
    || auth.subjectType !== 'service'
    || auth.tokenUse !== 'service'
    || !sourceApp
    || !capability
    || !serviceAuthScopes(auth).has(capability)
    || stringValue(input.envelope.targetApp) !== input.options.appCode
    || stringValue(command?.actorUid) !== uid
    || uid.length > 191
    || [...uid].some(character => (character.codePointAt(0) || 0) < 32 || (character.codePointAt(0) || 0) === 127)
  ) {
    throw createError({ statusCode: 403, message: 'Trusted service-command actor delegation is invalid.' })
  }
  return uid
}

function validDelegatedUid(value: string) {
  return Boolean(value)
    && value.length <= 191
    && ![...value].some((character) => {
      const code = character.codePointAt(0) || 0
      return code < 32 || code === 127
    })
}

function trustedWorkflowProxyActor(input: {
  event: H3Event
  path: string
  options: TenantRuntimeCallOptions
  tenant: string
  deployment: string
}) {
  const delegation = input.options.workflowProxyActor
  if (!delegation) return ''

  const auth = input.event.context.consoleAuth as TenantRuntimeActorAuth | undefined
  const sourceApp = stringValue(auth?.appCode || auth?.clientCode).replace(/\.runtime$/u, '')
  const declaredApp = stringValue(getHeader(input.event, 'x-hzy-request-app-code'))
  const uid = stringValue(delegation.uid)
  const sourceTenant = stringValue(auth?.tenant)
  const sourceDeployment = stringValue(auth?.deployment)
  const usesServiceClientPolicy = input.options.serviceTokenSourceBinding === 'service-client-policy'

  if (
    !auth?.authenticated
    || auth.subjectType !== 'service'
    || auth.tokenUse !== 'service'
    || input.options.appCode !== 'workflow'
    || !input.path.startsWith('/v1/workflow/')
    || !serviceAuthScopes(auth).has('workflow:proxy')
    || !sourceApp
    || declaredApp !== sourceApp
    || !validDelegatedUid(uid)
    || !sourceTenant
    || sourceTenant !== input.tenant
    || !sourceDeployment
    // The legacy trusted-gateway path signs for the same deployment.  A
    // cross-app Workflow proxy deliberately retains the source app deployment
    // in its verified caller token while the separately issued target runtime
    // token binds `input.deployment` to Workflow's exact client policy.
    || (!usesServiceClientPolicy && sourceDeployment !== input.deployment)
  ) {
    throw createError({ statusCode: 403, message: 'Trusted Workflow proxy actor delegation is invalid.' })
  }
  return uid
}

type CloudflareEnv = Record<string, unknown>

type CloudflareRuntimeEvent = H3Event & {
  context?: H3Event['context'] & {
    cloudflare?: {
      env?: CloudflareEnv
    }
    _platform?: {
      cloudflare?: {
        env?: CloudflareEnv
      }
    }
  }
  req?: {
    runtime?: {
      cloudflare?: {
        env?: CloudflareEnv
      }
    }
  }
}

function stringValue(value: unknown) {
  return String(value || '').trim()
}

function configValue(config: Record<string, unknown>, keys: string[]) {
  for (const key of keys) {
    let current: unknown = config
    for (const part of key.split('.')) {
      if (!current || typeof current !== 'object') {
        current = undefined
        break
      }
      current = (current as Record<string, unknown>)[part]
    }
    const value = stringValue(current)
    if (value) return value
  }
  return ''
}

function cloudflareEnv(event: H3Event): CloudflareEnv {
  const runtimeEvent = event as CloudflareRuntimeEvent
  return runtimeEvent.context?.cloudflare?.env
    || runtimeEvent.context?._platform?.cloudflare?.env
    || runtimeEvent.req?.runtime?.cloudflare?.env
    || {}
}

function cloudflareEnvValue(event: H3Event, names: string[]) {
  const env = cloudflareEnv(event)
  for (const name of names) {
    const value = stringValue(env[name])
    if (value) return value
  }
  return ''
}

function processEnvValue(names: string[]) {
  for (const name of names) {
    const value = stringValue(process.env[name])
    if (value) return value
  }
  return ''
}

function appEnvName(appCode: string, suffix: string) {
  return `HZY_${appCode.replace(/[^a-z0-9]/gi, '_').toUpperCase()}_${suffix}`
}

function constantTimeEquals(left: string, right: string) {
  if (!left || !right) return false
  let diff = left.length ^ right.length
  const length = Math.max(left.length, right.length)
  for (let i = 0; i < length; i += 1) {
    diff |= (left.charCodeAt(i) || 0) ^ (right.charCodeAt(i) || 0)
  }
  return diff === 0
}

function tenantGatewayInternalToken(event: H3Event, config: Record<string, unknown>) {
  return configValue(config, [
    'hzy.cloudflareInternalToken',
    'hzy.tenantGateway.internalToken',
    'tenantGateway.internalToken',
    'security.cloudflareInternalToken',
    'security.tenantGatewayInternalToken'
  ]) || cloudflareEnvValue(event, [
    'HZY_CLOUDFLARE_INTERNAL_TOKEN',
    'HZY_TENANT_GATEWAY_INTERNAL_TOKEN',
    'HZY_CONSOLE_TENANT_GATEWAY_TOKEN',
    'TENANT_GATEWAY_INTERNAL_TOKEN'
  ]) || processEnvValue([
    'HZY_CLOUDFLARE_INTERNAL_TOKEN',
    'HZY_TENANT_GATEWAY_INTERNAL_TOKEN',
    'HZY_CONSOLE_TENANT_GATEWAY_TOKEN',
    'TENANT_GATEWAY_INTERNAL_TOKEN'
  ])
}

function platformBaseUrl(event: H3Event, config: Record<string, unknown>) {
  return configValue(config, [
    'hzy.platform.baseUrl',
    'platform.baseUrl'
  ]) || cloudflareEnvValue(event, [
    'HZY_PLATFORM_URL',
    'PLATFORM_BASE_URL',
    'PLATFORM_URL'
  ]) || processEnvValue([
    'HZY_PLATFORM_URL',
    'PLATFORM_BASE_URL',
    'PLATFORM_URL'
  ])
}

function isTrustedTenantGatewayRequest(event: H3Event, config: Record<string, unknown>) {
  if (stringValue(getHeader(event, 'x-hzy-gateway')) !== 'tenant-gateway') return false
  const expectedToken = tenantGatewayInternalToken(event, config)
  if (!expectedToken) return false
  return constantTimeEquals(stringValue(getHeader(event, 'x-hzy-gateway-token')), expectedToken)
}

async function requestPlatformRuntimeBootstrapToken(event: H3Event, config: Record<string, unknown>) {
  if (!isTrustedTenantGatewayRequest(event, config)) return ''

  const tenantCode = stringValue(getHeader(event, 'x-hzy-tenant'))
  const deploymentCode = stringValue(getHeader(event, 'x-hzy-deployment'))
  const environment = stringValue(getHeader(event, 'x-hzy-environment'))
  const appCode = stringValue(getHeader(event, 'x-hzy-app-code'))
  const internalToken = tenantGatewayInternalToken(event, config)
  const baseUrl = platformBaseUrl(event, config).replace(/\/+$/u, '')
  // Only a Console gateway request may mint a fresh Platform bootstrap token.
  // A trusted business-app request to Console's token endpoint instead carries
  // the already-issued Console Runtime bootstrap token from its original
  // tenant-gateway context; let resolveBearerToken validate and use that token.
  if (appCode !== 'console') return ''
  if (!tenantCode || !deploymentCode || !environment || !internalToken || !baseUrl) {
    throw createError({
      statusCode: 503,
      message: 'Trusted Tenant Gateway Runtime bootstrap context is incomplete.'
    })
  }

  const cacheKey = [baseUrl, tenantCode, deploymentCode, environment, appCode].join('|')
  const cached = platformRuntimeBootstrapCache.get(cacheKey)
  if (cached && cached.expiresAt > Date.now() + 10_000) return cached.token

  let response: PlatformRuntimeBootstrapResponse
  try {
    response = await fetchExternal<PlatformRuntimeBootstrapResponse>(
      `${baseUrl}/api/platform/internal/tenant-gateway/runtime-bootstrap-token`,
      {
        method: 'POST',
        headers: {
          'authorization': `Bearer ${internalToken}`,
          'content-type': 'application/json',
          'user-agent': workerServiceUserAgent,
          'x-hzy-internal-principal': 'console-runtime-bootstrap'
        },
        body: { tenantCode, environment, appCode },
        timeout: 10000
      }
    )
  } catch {
    throw createError({
      statusCode: 503,
      message: 'Platform Runtime bootstrap token is unavailable.'
    })
  }

  const token = stringValue(response?.data?.token)
  const expiresAt = Date.parse(stringValue(response?.data?.expiresAt))
  const metadata = safeJwtMetadata(token) as Record<string, unknown>
  if (
    !token
    || !Number.isFinite(expiresAt)
    || expiresAt <= Date.now() + 10_000
    || metadata.tokenUse !== 'platform_runtime_bootstrap'
    || metadata.tenant !== tenantCode
    || metadata.deployment !== deploymentCode
    || metadata.appCode !== appCode
    || stringValue(response?.data?.tenantCode) !== tenantCode
    || stringValue(response?.data?.deploymentCode) !== deploymentCode
    || stringValue(response?.data?.appCode) !== appCode
  ) {
    throw createError({
      statusCode: 503,
      message: 'Platform Runtime bootstrap token binding is invalid.'
    })
  }

  platformRuntimeBootstrapCache.set(cacheKey, { token, expiresAt })
  return token
}

function tenantGatewayHeader(event: H3Event, names: string[], config: Record<string, unknown>) {
  if (!isTrustedTenantGatewayRequest(event, config)) return ''
  for (const name of names) {
    const value = stringValue(getHeader(event, name))
    if (value) return value
  }
  return ''
}

function tenantRuntimeEndpoint(
  event: H3Event,
  appCode: string,
  config: Record<string, unknown>,
  options: TenantRuntimeResolutionOptions = {}
) {
  const includeGlobal = options.includeGlobal !== false
  const tenantRuntimeEnvNames = [
    appEnvName(appCode, 'TENANT_RUNTIME_URL'),
    ...(includeGlobal ? ['HZY_TENANT_RUNTIME_URL'] : []),
    appEnvName(appCode, 'DATA_RUNTIME_URL'),
    ...(includeGlobal ? ['HZY_DATA_RUNTIME_URL'] : [])
  ]

  return tenantGatewayHeader(event, ['x-hzy-tenant-runtime-url', 'x-hzy-data-runtime-url'], config) || configValue(config, [
    'hzy.tenantRuntime.endpoint',
    'tenantRuntime.endpoint',
    'hzy.dataRuntime.endpoint',
    'dataRuntime.endpoint'
  ]) || cloudflareEnvValue(event, tenantRuntimeEnvNames) || processEnvValue(tenantRuntimeEnvNames)
}

function tenantRuntimeToken(event: H3Event, appCode: string, config: Record<string, unknown>) {
  return tenantGatewayHeader(event, ['x-hzy-tenant-runtime-token', 'x-hzy-data-runtime-token'], config) || configValue(config, [
    'hzy.tenantRuntime.token',
    'tenantRuntime.token',
    'hzy.dataRuntime.token',
    'dataRuntime.token'
  ]) || cloudflareEnvValue(event, [
    appEnvName(appCode, 'TENANT_RUNTIME_TOKEN'),
    'HZY_TENANT_RUNTIME_TOKEN',
    appEnvName(appCode, 'DATA_RUNTIME_TOKEN'),
    'HZY_DATA_RUNTIME_TOKEN'
  ]) || processEnvValue([
    appEnvName(appCode, 'TENANT_RUNTIME_TOKEN'),
    'HZY_TENANT_RUNTIME_TOKEN',
    appEnvName(appCode, 'DATA_RUNTIME_TOKEN'),
    'HZY_DATA_RUNTIME_TOKEN'
  ])
}

function tenantRuntimeAudience(event: H3Event, config: Record<string, unknown>) {
  return tenantGatewayHeader(event, ['x-hzy-data-runtime-audience', 'x-hzy-tenant-runtime-audience'], config) || cloudflareEnvValue(event, [
    'HZY_DATA_RUNTIME_AUDIENCE'
  ]) || processEnvValue([
    'HZY_DATA_RUNTIME_AUDIENCE'
  ]) || configValue(config, [
    'hzy.dataRuntime.audience',
    'dataRuntime.audience'
  ]) || configValue(config, [
    'hzy.tenantRuntime.audience',
    'tenantRuntime.audience'
  ]) || cloudflareEnvValue(event, [
    'HZY_TENANT_RUNTIME_AUDIENCE'
  ]) || processEnvValue([
    'HZY_TENANT_RUNTIME_AUDIENCE'
  ]) || 'data-runtime'
}

function optionalHeader(
  event: H3Event,
  config: Record<string, unknown>,
  keys: string[],
  envNames: string[],
  gatewayHeaderNames: string[]
) {
  const gatewayValue = tenantGatewayHeader(event, gatewayHeaderNames, config)
  if (gatewayValue) return gatewayValue
  return configValue(config, keys) || cloudflareEnvValue(event, envNames) || processEnvValue(envNames)
}

function dataAccessMode(config: Record<string, unknown>, appCode: string) {
  return (
    processEnvValue([appEnvName(appCode, 'DATA_ACCESS_MODE'), 'HZY_DATA_ACCESS_MODE'])
    || configValue(config, [
      'hzy.tenantRuntime.dataAccessMode',
      'tenantRuntime.dataAccessMode',
      'hzy.dataRuntime.dataAccessMode',
      'dataRuntime.dataAccessMode',
      'hzy.dataAccessMode',
      'dataAccessMode'
    ])
  ).toLowerCase()
}

function shouldCallTenantRuntime(config: Record<string, unknown>, appCode: string, endpoint: string) {
  const mode = dataAccessMode(config, appCode)
  if (mode === 'direct-db') return false
  if (mode === 'tenant-runtime' || mode === 'fallback') return Boolean(endpoint)
  return isTenantRuntimeProfile(resolveDeploymentProfile(config)) && Boolean(endpoint)
}

function appendQuery(url: URL, query: Record<string, unknown>) {
  for (const [key, value] of Object.entries(query)) {
    if (value === undefined || value === null) continue
    if (Array.isArray(value)) {
      for (const item of value) {
        if (item !== undefined && item !== null) url.searchParams.append(key, String(item))
      }
      continue
    }
    url.searchParams.set(key, String(value))
  }
}

function normalizeMethod(value: unknown): TenantRuntimeMethod {
  const method = String(value || 'GET').toUpperCase()
  if (method === 'POST' || method === 'PATCH' || method === 'PUT' || method === 'DELETE') return method
  return 'GET'
}

export function tenantRuntimeTokenScope(audience: string, scope: string): string {
  const normalizedAudience = stringValue(audience)
  const normalizedScope = stringValue(scope)
  if (!normalizedAudience || !normalizedScope) return normalizedScope
  const scopes = normalizedScope.split(/\s+/).filter(Boolean)
  if (scopes.length > 1) {
    return scopes.map(item => tenantRuntimeTokenScope(normalizedAudience, item)).join(' ')
  }
  if (normalizedScope.startsWith('console:')) return normalizedScope
  if (normalizedScope.startsWith(`${normalizedAudience}:`)) return normalizedScope

  if (normalizedScope.includes(':')) {
    return `${normalizedAudience}:${normalizedScope}`
  }

  const [appCode, action] = normalizedScope.split(/\.(.+)/).filter(Boolean)
  if (!appCode || !action) return normalizedScope

  return `${normalizedAudience}:${appCode}:${action}`
}

async function resolveBearerToken(event: H3Event, options: TenantRuntimeCallOptions, config: Record<string, unknown>) {
  // Cross-app target BFFs must not reuse the source application's gateway
  // runtime token.  In service-client-policy mode the target obtains a fresh
  // token from its own exact `<app>.runtime` credential policy.
  let staticToken = ''
  if (options.serviceTokenSourceBinding !== 'service-client-policy') {
    staticToken = tenantRuntimeToken(event, options.appCode, config)
  }
  if (options.requireStaticRuntimeToken) {
    // Tenant Gateway already minted and HMAC-bound this short-lived token for
    // the current tenant/deployment. Reusing it avoids a second Platform lookup
    // during the nested service-token exchange; Runtime still verifies the
    // EdDSA signature and exact bootstrap claims before issuing any token.
    const forwardedPlatformBootstrap = isPlatformRuntimeBootstrapToken(staticToken)
      ? staticToken
      : ''
    const refreshedPlatformBootstrap = forwardedPlatformBootstrap
      ? ''
      : await requestPlatformRuntimeBootstrapToken(event, config)
    const bootstrapToken = forwardedPlatformBootstrap || refreshedPlatformBootstrap || staticToken
    if (!bootstrapToken) {
      throw createError({
        statusCode: 503,
        message: 'An enrolled Tenant Runtime bootstrap token is required for this operation.'
      })
    }

    // The Platform bootstrap credential is deliberately restricted to the
    // service-token issuer. It must never be presented directly to client
    // credential consumption, enrollment, or other Console Runtime routes.
    if (options.scope === 'console:service-token:issue') return bootstrapToken
    if (!isPlatformRuntimeBootstrapToken(bootstrapToken)) return bootstrapToken

    const audience = tenantRuntimeAudience(event, config)
    return await requestServiceAccessToken({
      audience,
      scope: tenantRuntimeTokenScope(audience, options.scope),
      sourceBinding: options.serviceTokenSourceBinding,
      event
    })
  }
  if (staticToken && !isPlatformRuntimeBootstrapToken(staticToken)) return staticToken
  const audience = tenantRuntimeAudience(event, config)
  return await requestServiceAccessToken({
    audience,
    scope: tenantRuntimeTokenScope(audience, options.scope),
    sourceBinding: options.serviceTokenSourceBinding,
    event
  })
}

function currentSubjectUid(event: H3Event) {
  return stringValue(verifiedUserConsoleAuth(event)?.uid)
}

function verifiedUserConsoleAuth(event: H3Event) {
  const consoleAuth = event.context.consoleAuth as TenantRuntimeActorAuth | undefined
  if (!consoleAuth?.authenticated || consoleAuth.subjectType === 'service') return null
  return consoleAuth
}

function splitCodes(value: unknown): string[] {
  if (Array.isArray(value)) return value.flatMap(item => splitCodes(item))
  return String(value || '')
    .split(/[,\s;]+/)
    .map(item => item.trim())
    .filter(Boolean)
}

function uniqueCodes(values: string[]) {
  return Array.from(new Set(values))
}

function currentSubjectDeptCodes(event: H3Event) {
  const consoleAuth = verifiedUserConsoleAuth(event)
  const values: string[] = []
  if (consoleAuth) {
    values.push(...splitCodes(consoleAuth.deptCodes))
    values.push(...splitCodes(consoleAuth.deptCode))
    values.push(...splitCodes(consoleAuth.claims?.dept_codes))
    values.push(...splitCodes(consoleAuth.claims?.dept_code))
  }
  return uniqueCodes(values)
}

function base64Url(bytes: ArrayBuffer) {
  let binary = ''
  for (const byte of new Uint8Array(bytes)) {
    binary += String.fromCharCode(byte)
  }
  return btoa(binary)
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/g, '')
}

async function signActorDelegation(input: {
  token: string
  method: TenantRuntimeMethod
  requestTarget: string
  actorUid: string
  deptCodes: string[]
  signedAt: string
  purpose?: string
}) {
  const encoder = new TextEncoder()
  const key = await crypto.subtle.importKey(
    'raw',
    encoder.encode(input.token),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  )
  const values = [
    input.method,
    input.requestTarget,
    input.actorUid,
    input.deptCodes.join(','),
    input.signedAt
  ]
  if (input.purpose) values.push(input.purpose)
  const payload = values.join('\n')
  const signature = await crypto.subtle.sign('HMAC', key, encoder.encode(payload))
  return base64Url(signature)
}

type ServiceCommandEnvelope = {
  operationId: string
  targetApp: string
  operationCode: string
  requiredCapability: string
  idempotencyKey: string
  commandSchemaVersion: string
  commandSha256: string
  command?: Record<string, unknown>
}

export type SignedServiceCommandEnvelope = ServiceCommandEnvelope

function serviceCommandEnvelope(body: unknown): ServiceCommandEnvelope | null {
  if (!body || typeof body !== 'object' || Array.isArray(body)) return null
  const raw = (body as Record<string, unknown>).serviceCommand
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return null
  const value = raw as Record<string, unknown>
  const command = value.command && typeof value.command === 'object' && !Array.isArray(value.command)
    ? value.command as Record<string, unknown>
    : undefined
  const envelope = {
    operationId: stringValue(value.operationId),
    targetApp: stringValue(value.targetApp),
    operationCode: stringValue(value.operationCode),
    requiredCapability: stringValue(value.requiredCapability),
    idempotencyKey: stringValue(value.idempotencyKey),
    commandSchemaVersion: stringValue(value.commandSchemaVersion),
    commandSha256: stringValue(value.commandSha256),
    command
  }
  if (Object.entries(envelope).some(([key, item]) => key !== 'command' && !item)) {
    throw createError({ statusCode: 400, message: 'Service command envelope is incomplete.' })
  }
  return envelope
}

async function signHmac(token: string, payload: string) {
  const encoder = new TextEncoder()
  const key = await crypto.subtle.importKey(
    'raw',
    encoder.encode(token),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  )
  return base64Url(await crypto.subtle.sign('HMAC', key, encoder.encode(payload)))
}

function base64UrlBytes(value: string) {
  const normalized = String(value || '').trim().replace(/-/g, '+').replace(/_/g, '/')
  if (!normalized || !/^[A-Za-z0-9+/]+={0,2}$/u.test(normalized)) return new Uint8Array()
  const padded = normalized + '='.repeat((4 - normalized.length % 4) % 4)
  try {
    const binary = atob(padded)
    return Uint8Array.from(binary, character => character.charCodeAt(0))
  } catch {
    return new Uint8Array()
  }
}

function serviceCommandCanonical(input: {
  method: TenantRuntimeMethod
  requestTarget: string
  tenantCode: string
  sourceDeploymentCode: string
  targetDeploymentCode: string
  sourceApp: string
  sourceClientId: string
  targetApp: string
  envelope: ServiceCommandEnvelope
  requestId: string
  signedAt: string
}) {
  return [
    input.method,
    input.requestTarget,
    input.tenantCode,
    input.sourceDeploymentCode,
    input.targetDeploymentCode,
    input.sourceApp,
    input.sourceClientId,
    input.targetApp,
    input.envelope.operationId,
    input.envelope.operationCode,
    input.envelope.requiredCapability,
    input.envelope.idempotencyKey,
    input.envelope.commandSchemaVersion,
    input.envelope.commandSha256,
    input.requestId,
    input.signedAt
  ].join('\n')
}

export async function hashServiceCommandPayload(payload: unknown) {
  const encoded = new TextEncoder().encode(JSON.stringify(payload))
  const digest = await crypto.subtle.digest('SHA-256', encoded)
  return [...new Uint8Array(digest)].map(byte => byte.toString(16).padStart(2, '0')).join('')
}

export async function buildServiceCommandRuntimeHeaders(input: {
  token: string
  method: TenantRuntimeMethod
  requestTarget: string
  requestId: string
  tenantCode: string
  sourceDeploymentCode: string
  targetDeploymentCode: string
  sourceApp: string
  sourceClientId: string
  targetApp: string
  envelope: ServiceCommandEnvelope
  signedAt?: string
}) {
  const signedAt = input.signedAt || String(Date.now())
  if (
    !input.token
    || !input.tenantCode
    || !input.sourceDeploymentCode
    || !input.targetDeploymentCode
    || !input.sourceApp
    || !input.sourceClientId
    || !input.targetApp
    || input.sourceApp === input.targetApp
    || input.envelope.targetApp !== input.targetApp
  ) {
    throw createError({ statusCode: 403, message: 'Trusted service command context is incomplete.' })
  }
  const canonical = serviceCommandCanonical({ ...input, signedAt })
  return {
    'x-hzy-service-command-tenant': input.tenantCode,
    'x-hzy-service-command-source-deployment': input.sourceDeploymentCode,
    'x-hzy-service-command-target-deployment': input.targetDeploymentCode,
    'x-hzy-service-command-source-app': input.sourceApp,
    'x-hzy-service-command-source-client': input.sourceClientId,
    'x-hzy-service-command-target-app': input.targetApp,
    'x-hzy-service-command-operation-id': input.envelope.operationId,
    'x-hzy-service-command-operation-code': input.envelope.operationCode,
    'x-hzy-service-command-capability': input.envelope.requiredCapability,
    'x-hzy-service-command-idempotency-key': input.envelope.idempotencyKey,
    'x-hzy-service-command-schema-version': input.envelope.commandSchemaVersion,
    'x-hzy-service-command-sha256': input.envelope.commandSha256,
    'x-hzy-service-command-signed-at': signedAt,
    'x-hzy-service-command-signature': await signHmac(input.token, canonical)
  }
}

/**
 * Verifies the same short-lived HMAC envelope built above before a target BFF
 * turns a source-provided actor into a runtime service-command actor. The
 * target must provide values from the verified inbound token/context, never
 * from the body, and must separately bind commandSha256 to its fixed command.
 */
export async function verifyServiceCommandRuntimeHeaders(input: {
  token: string
  method: TenantRuntimeMethod
  requestTarget: string
  requestId: string
  tenantCode: string
  sourceDeploymentCode: string
  targetDeploymentCode: string
  sourceApp: string
  sourceClientId: string
  targetApp: string
  envelope: ServiceCommandEnvelope
  readHeader: (name: string) => unknown
  now?: number
}) {
  const headers = {
    tenantCode: stringValue(input.readHeader('x-hzy-service-command-tenant')),
    sourceDeploymentCode: stringValue(input.readHeader('x-hzy-service-command-source-deployment')),
    targetDeploymentCode: stringValue(input.readHeader('x-hzy-service-command-target-deployment')),
    sourceApp: stringValue(input.readHeader('x-hzy-service-command-source-app')),
    sourceClientId: stringValue(input.readHeader('x-hzy-service-command-source-client')),
    targetApp: stringValue(input.readHeader('x-hzy-service-command-target-app')),
    operationId: stringValue(input.readHeader('x-hzy-service-command-operation-id')),
    operationCode: stringValue(input.readHeader('x-hzy-service-command-operation-code')),
    requiredCapability: stringValue(input.readHeader('x-hzy-service-command-capability')),
    idempotencyKey: stringValue(input.readHeader('x-hzy-service-command-idempotency-key')),
    commandSchemaVersion: stringValue(input.readHeader('x-hzy-service-command-schema-version')),
    commandSha256: stringValue(input.readHeader('x-hzy-service-command-sha256')),
    signedAt: stringValue(input.readHeader('x-hzy-service-command-signed-at')),
    signature: stringValue(input.readHeader('x-hzy-service-command-signature'))
  }
  const expected = {
    tenantCode: input.tenantCode,
    sourceDeploymentCode: input.sourceDeploymentCode,
    targetDeploymentCode: input.targetDeploymentCode,
    sourceApp: input.sourceApp,
    sourceClientId: input.sourceClientId,
    targetApp: input.targetApp,
    operationId: input.envelope.operationId,
    operationCode: input.envelope.operationCode,
    requiredCapability: input.envelope.requiredCapability,
    idempotencyKey: input.envelope.idempotencyKey,
    commandSchemaVersion: input.envelope.commandSchemaVersion,
    commandSha256: input.envelope.commandSha256
  }
  if (
    !input.token || !input.requestTarget || !input.requestId
    || Object.values(headers).some(value => !value)
    || Object.entries(expected).some(([key, value]) => headers[key as keyof typeof headers] !== value)
  ) {
    throw createError({ statusCode: 403, message: 'Trusted service command signature context is invalid.' })
  }
  const signedAt = Number(headers.signedAt)
  const now = input.now ?? Date.now()
  if (!Number.isSafeInteger(signedAt) || signedAt > now + 5_000 || now - signedAt > 60_000) {
    throw createError({ statusCode: 403, message: 'Trusted service command signature is expired.' })
  }
  const signature = base64UrlBytes(headers.signature)
  if (signature.length === 0) {
    throw createError({ statusCode: 403, message: 'Trusted service command signature is invalid.' })
  }
  const encoder = new TextEncoder()
  const key = await crypto.subtle.importKey('raw', encoder.encode(input.token), { name: 'HMAC', hash: 'SHA-256' }, false, ['verify'])
  const valid = await crypto.subtle.verify('HMAC', key, signature, encoder.encode(serviceCommandCanonical({
    method: input.method,
    requestTarget: input.requestTarget,
    tenantCode: input.tenantCode,
    sourceDeploymentCode: input.sourceDeploymentCode,
    targetDeploymentCode: input.targetDeploymentCode,
    sourceApp: input.sourceApp,
    sourceClientId: input.sourceClientId,
    targetApp: input.targetApp,
    envelope: input.envelope,
    requestId: input.requestId,
    signedAt: headers.signedAt
  })))
  if (!valid) {
    throw createError({ statusCode: 403, message: 'Trusted service command signature is invalid.' })
  }
}

export function isTenantRuntimeEndpointConfigured(
  event: H3Event,
  appCode: string,
  config = useRuntimeConfig() as unknown as Record<string, unknown>,
  options: TenantRuntimeResolutionOptions = {}
) {
  return Boolean(tenantRuntimeEndpoint(event, appCode, config, options))
}

export function isTenantRuntimeEnabled(
  event: H3Event,
  appCode: string,
  config = useRuntimeConfig() as unknown as Record<string, unknown>,
  options: TenantRuntimeResolutionOptions = {}
) {
  return shouldCallTenantRuntime(config, appCode, tenantRuntimeEndpoint(event, appCode, config, options))
}

export async function maybeCallTenantRuntime<T>(
  event: H3Event,
  path: string,
  options: TenantRuntimeCallOptions
): Promise<TenantRuntimeSkipped | TenantRuntimeHandled<T>> {
  const config = useRuntimeConfig() as unknown as Record<string, unknown>
  const endpoint = tenantRuntimeEndpoint(event, options.appCode, config)
  if (!shouldCallTenantRuntime(config, options.appCode, endpoint)) {
    return { handled: false }
  }

  const url = new URL(path, endpoint.endsWith('/') ? endpoint : `${endpoint}/`)
  appendQuery(url, options.query || getQuery(event))
  const method = normalizeMethod(options.method)
  const token = await measureRequestStage(event, 'runtime_token', () => resolveBearerToken(event, options, config))
  const tokenMetadata = safeJwtMetadata(token) as Record<string, unknown>
  const envelope = serviceCommandEnvelope(options.body)
  const requestId = stringValue(getHeader(event, 'x-request-id') || getHeader(event, 'x-correlation-id'))
    || (envelope ? crypto.randomUUID() : '')
  const idempotencyKey = stringValue(options.idempotencyKey || getHeader(event, 'idempotency-key'))
  const gatewayTenant = optionalHeader(event, config, [
    'hzy.tenantRuntime.tenant',
    'tenantRuntime.tenant',
    'hzy.dataRuntime.tenant',
    'dataRuntime.tenant'
  ], [
    'HZY_TENANT_RUNTIME_TENANT',
    'HZY_DATA_RUNTIME_TENANT'
  ], ['x-hzy-tenant'])
  const gatewayDeployment = optionalHeader(event, config, [
    'hzy.tenantRuntime.deployment',
    'tenantRuntime.deployment',
    'hzy.dataRuntime.deployment',
    'dataRuntime.deployment'
  ], [
    'HZY_TENANT_RUNTIME_DEPLOYMENT',
    'HZY_DATA_RUNTIME_DEPLOYMENT'
  ], ['x-hzy-deployment'])
  const usesServiceClientPolicy = options.serviceTokenSourceBinding === 'service-client-policy'
  const tenant = usesServiceClientPolicy ? stringValue(tokenMetadata.tenant) : gatewayTenant
  const deployment = usesServiceClientPolicy ? stringValue(tokenMetadata.deployment) : gatewayDeployment
  if (usesServiceClientPolicy && (!tenant || !deployment)) {
    throw createError({
      statusCode: 503,
      message: 'Service client token is missing its tenant/runtime deployment policy binding.'
    })
  }
  const delegatedSubjectUid = trustedNotificationDetailActor({
    event,
    path,
    options,
    tenant,
    deployment
  })
  const serviceCommandSubjectUid = trustedServiceCommandActor({ event, options, envelope })
  const workflowProxySubjectUid = trustedWorkflowProxyActor({
    event,
    path,
    options,
    tenant,
    deployment
  })
  const subjectUid = delegatedSubjectUid || serviceCommandSubjectUid || workflowProxySubjectUid || currentSubjectUid(event)
  const subjectDeptCodes = delegatedSubjectUid ? [] : currentSubjectDeptCodes(event)
  const actorSignedAt = subjectUid ? String(Date.now()) : ''
  const actorSignature = subjectUid
    ? await signActorDelegation({
        token,
        method,
        requestTarget: `${url.pathname}${url.search}`,
        actorUid: subjectUid,
        deptCodes: subjectDeptCodes,
        signedAt: actorSignedAt,
        purpose: delegatedSubjectUid ? 'notification-detail-authorization' : serviceCommandSubjectUid ? 'service-command' : undefined
      })
    : ''
  let serviceCommandHeaders: Record<string, string> = {}
  if (envelope) {
    const incoming = event.context.consoleAuth as TenantRuntimeActorAuth | undefined
    const sourceApp = stringValue(incoming?.appCode || incoming?.clientCode).replace(/\.runtime$/u, '')
    const sourceClientId = stringValue(incoming?.clientCode || incoming?.appCode)
    const sourceTenant = stringValue(incoming?.tenant)
    const sourceDeployment = stringValue(incoming?.deployment)
    if (
      !incoming?.authenticated
      || incoming.subjectType !== 'service'
      || incoming.tokenUse !== 'service'
      || !sourceApp
      || !sourceClientId
      || sourceTenant !== tenant
    ) {
      throw createError({ statusCode: 403, message: 'Verified source service identity is required for service commands.' })
    }
    serviceCommandHeaders = await buildServiceCommandRuntimeHeaders({
      token,
      method,
      requestTarget: `${url.pathname}${url.search}`,
      requestId,
      tenantCode: sourceTenant,
      sourceDeploymentCode: sourceDeployment,
      targetDeploymentCode: deployment,
      sourceApp,
      sourceClientId,
      targetApp: options.appCode,
      envelope
    })
  }

  try {
    const data = await measureRequestStage(event, 'runtime_http', () => fetchExternal<T>(url.toString(), {
      method,
      headers: {
        'authorization': `Bearer ${token}`,
        'user-agent': workerServiceUserAgent,
        ...(method === 'GET' ? {} : { 'content-type': 'application/json' }),
        ...(requestId ? { 'x-request-id': requestId } : {}),
        ...(idempotencyKey ? { 'idempotency-key': idempotencyKey } : {}),
        ...(subjectUid ? { 'x-hzy-actor-uid': subjectUid } : {}),
        ...(subjectDeptCodes[0] ? { 'x-hzy-actor-dept-code': subjectDeptCodes[0] } : {}),
        ...(subjectDeptCodes.length > 0 ? { 'x-hzy-actor-dept-codes': subjectDeptCodes.join(',') } : {}),
        ...(actorSignedAt ? { 'x-hzy-actor-signed-at': actorSignedAt } : {}),
        ...(actorSignature ? { 'x-hzy-actor-signature': actorSignature } : {}),
        ...(delegatedSubjectUid ? { 'x-hzy-actor-purpose': 'notification-detail-authorization' } : serviceCommandSubjectUid ? { 'x-hzy-actor-purpose': 'service-command' } : {}),
        ...(tenant ? { 'x-hzy-tenant': tenant } : {}),
        ...(deployment ? { 'x-hzy-deployment': deployment } : {}),
        ...serviceCommandHeaders
      },
      ...(method === 'GET' ? {} : { body: options.body ?? {} }),
      timeout: options.timeoutMs || 10000
    }))
    return { handled: true, data }
  } catch (error: unknown) {
    const fetchError = error as {
      status?: number
      statusCode?: number
      statusMessage?: string
      data?: TenantRuntimeErrorEnvelope
    }
    const runtimeError = tenantRuntimeErrorData(
      fetchError,
      error instanceof Error ? error.message : String(error)
    )
    if (runtimeError.upstreamStatus >= 400) {
      const logMessage = runtimeError.upstreamStatus === 401 || runtimeError.upstreamStatus === 403
        ? '[tenantRuntimeClient] tenant runtime rejected authenticated request'
        : '[tenantRuntimeClient] tenant runtime request failed'
      console.warn(logMessage, {
        appCode: options.appCode,
        path: url.pathname,
        code: runtimeError.code,
        upstreamStatus: runtimeError.upstreamStatus,
        upstream: safeUpstreamResponseMetadata(error),
        token: safeJwtMetadata(token)
      })
    }
    throw createError({
      statusCode: runtimeError.statusCode,
      statusMessage: runtimeError.statusCode === 503 ? 'Tenant Runtime unavailable' : fetchError.statusMessage,
      message: runtimeError.message,
      data: {
        code: runtimeError.code,
        message: runtimeError.message,
        upstreamStatus: runtimeError.upstreamStatus
      }
    })
  }
}

export async function maybeCallCurrentAppTenantRuntime<T>(
  event: H3Event,
  options: {
    appCode: string
    scope: string
    pathPrefix?: string
  }
): Promise<TenantRuntimeSkipped | TenantRuntimeHandled<T>> {
  const pathname = getRequestURL(event).pathname
  const marker = options.pathPrefix || '/api/v1'
  const markerIndex = pathname.indexOf(marker)
  if (markerIndex < 0) return { handled: false }

  const suffix = pathname.slice(markerIndex + marker.length)
  const path = `/v1/${options.appCode}${suffix}`
  const method = normalizeMethod(event.node.req.method)
  const body = method === 'GET' ? undefined : await readRequestBodyCompat(event)
  return maybeCallTenantRuntime<T>(event, path, {
    appCode: options.appCode,
    scope: options.scope,
    method,
    body
  })
}
