package wizbiztool

// KnownSourceTables is frozen from W0 Appendix A metadata. It contains no
// production counts, hashes or data. Unknown tables are never ignored.
var knownSourceTables = map[string]bool{
	"gen_table":                true,
	"gen_table_column":         true,
	"qrtz_blob_triggers":       true,
	"qrtz_calendars":           true,
	"qrtz_cron_triggers":       true,
	"qrtz_fired_triggers":      true,
	"qrtz_job_details":         true,
	"qrtz_locks":               true,
	"qrtz_paused_trigger_grps": true,
	"qrtz_scheduler_state":     true,
	"qrtz_simple_triggers":     true,
	"qrtz_simprop_triggers":    true,
	"qrtz_triggers":            true,
	"sys_config":               true,
	"sys_dept":                 true,
	"sys_dict_data":            true,
	"sys_dict_type":            true,
	"sys_job":                  true,
	"sys_job_log":              true,
	"sys_logininfor":           true,
	"sys_menu":                 true,
	"sys_notice":               true,
	"sys_oper_log":             true,
	"sys_role":                 true,
	"sys_role_dept":            true,
	"sys_role_menu":            true,
	"sys_user":                 true,
	"sys_user_post":            true,
	"sys_user_role":            true,
	"wb_account_balance":       true,
	"wb_annual_contribution":   true,
	"wb_archives":              true,
	"wb_archives_list":         true,
	"wb_archives_page":         true,
	"wb_archives_page_copy1":   true,
	"wb_attendance":            true,
	"wb_bank_account":          true,
	"wb_career":                true,
	"wb_contact_message":       true,
	"wb_contactman":            true,
	"wb_contactman_info":       true,
	"wb_contract":              true,
	"wb_employee":              true,
	"wb_employee_post":         true,
	"wb_invoice":               true,
	"wb_markdown_file":         true,
	"wb_markdown_folder":       true,
	"wb_markdown_history":      true,
	"wb_markdown_image":        true,
	"wb_month":                 true,
	"wb_month_state":           true,
	"wb_organization":          true,
	"wb_organization_info":     true,
	"wb_pa_define":             true,
	"wb_pa_record":             true,
	"wb_payment_plan":          true,
	"wb_post":                  true,
	"wb_product":               true,
	"wb_product_version":       true,
	"wb_project":               true,
	"wb_project_contribution":  true,
	"wb_project_income":        true,
	"wb_project_member":        true,
	"wb_project_payment":       true,
	"wb_project_portion":       true,
	"wb_project_report":        true,
	"wb_rank":                  true,
	"wb_repository":            true,
	"wb_salary":                true,
	"wb_salary_adjustment":     true,
	"wb_salary_bk_0919":        true,
	"wb_salary_copy1":          true,
	"wb_salary_import":         true,
	"wb_salary_parameter":      true,
	"wb_solution":              true,
	"wb_system":                true,
}
var preserveSourceTables = map[string]bool{
	"wb_invoice":           true,
	"wb_project_income":    true,
	"wb_project_payment":   true,
	"wb_payment_plan":      true,
	"wb_system":            true,
	"wb_project":           true,
	"wb_product":           true,
	"wb_archives":          true,
	"wb_archives_page":     true,
	"wb_archives_list":     true,
	"wb_organization_info": true,
	"wb_contactman_info":   true,
}

func sourceInScope(name string) bool {
	if preserveSourceTables[name] {
		return true
	}
	switch name {
	case "wb_employee", "sys_user", "wb_organization", "wb_contactman", "wb_bank_account", "wb_account_balance", "wb_contract":
		return true
	}
	return false
}
