import { fileURLToPath } from 'node:url'

const page = (path, name, source) => ({ path, name, file: fileURLToPath(new URL(`./pages/${source}.vue`, import.meta.url)) })
export default Object.freeze({
  code: 'finance', prefix: '/finance', label: '财务',
  hostReadiness: { entryPath: '/bank-accounts', deferredPages: [] },
  navigation: [
    { id: 'finance.operations.treasury.historical-finance', area: 'operations', group: 'treasury', label: '历史财务接续', to: '/finance/historical-finance', permission: { resource: 'historical_finance', action: 'view' }, order: 61 },
    { id: 'finance.operations.treasury.receivable-adjustments', area: 'operations', group: 'treasury', label: '应收调整', to: '/finance/receivable-adjustments', permission: { resource: 'receivable_adjustments', action: 'view' }, order: 62 },
    { id: 'finance.operations.treasury.allocation-batches', area: 'operations', group: 'treasury', label: '分配批次', to: '/finance/allocation-batches', permission: { resource: 'reconciliation', action: 'view' }, order: 63 },
    { id: 'finance.operations.treasury.migration', area: 'operations', group: 'treasury', label: '迁移事项', to: '/finance/migration', permission: { resource: 'migration_exceptions', action: 'view' }, order: 150 },
    { id: 'finance.operations.treasury.legal-entities', area: 'operations', group: 'treasury', label: '法人主体', to: '/finance/legal-entities', permission: { resource: 'legal_entities', action: 'view' }, order: 15 },
    { id: 'finance.operations.treasury.project-accounting', area: 'operations', group: 'treasury', label: '项目核算', to: '/finance/project-accounting', permission: { resource: 'project_accounting', action: 'view' }, order: 110 },
    { id: 'finance.operations.treasury.cost-allocations', area: 'operations', group: 'treasury', label: '成本分摊', to: '/finance/project-cost-allocations', permission: { resource: 'project_accounting', action: 'view' }, order: 120 },
    { id: 'finance.operations.treasury.employee-costs', area: 'operations', group: 'treasury', label: '员工月成本', to: '/finance/employee-costs', permission: { resource: 'project_accounting', action: 'admin' }, order: 130 },
    { id: 'finance.operations.treasury.payment-requests', area: 'operations', group: 'treasury', label: '付款申请', to: '/finance/payment-requests', permission: { resource: 'expenses', action: 'view' }, order: 100 },
    { id: 'finance.console.config.expense-types', area: 'console', group: 'config', label: '费用类型', to: '/finance/settings/expense-types', permission: { resource: 'settings', action: 'admin' }, order: 50 },
    { id: 'finance.console.config.income-types', area: 'console', group: 'config', label: '收入类型', to: '/finance/settings/income-types', permission: { resource: 'settings', action: 'admin' }, order: 60 },
    { id: 'finance.console.config.subjects', area: 'console', group: 'config', label: '财务科目', to: '/finance/settings/subjects', permission: { resource: 'settings', action: 'admin' }, order: 70 },
    { id: 'finance.console.config.subject-mappings', area: 'console', group: 'config', label: '科目映射', to: '/finance/settings/subject-mappings', permission: { resource: 'settings', action: 'admin' }, order: 80 },
    { id: 'finance.console.config.accounting-objects', area: 'console', group: 'config', label: '核算对象', to: '/finance/accounting-objects', permission: { resource: 'settings', action: 'admin' }, order: 90 },
    { id: 'finance.console.config.audit-logs', area: 'console', group: 'config', label: '财务审计', to: '/finance/audit-logs', permission: { resource: 'settings', action: 'admin' }, order: 100 },
    { id: 'finance.console.config.approval-instances', area: 'console', group: 'config', label: '审批关联', to: '/finance/integrations/approval-instances', permission: { resource: 'settings', action: 'admin' }, order: 110 },
    { id: 'finance.operations.treasury.expenses', area: 'operations', group: 'treasury', label: '支出台账', to: '/finance/expenses', permission: { resource: 'expenses', action: 'view' }, order: 70 },
    { id: 'finance.operations.treasury.claims', area: 'operations', group: 'treasury', label: '费用报销', to: '/finance/expenses/claims', permission: { resource: 'expenses', action: 'view' }, order: 80 },
    { id: 'finance.operations.treasury.project-requests', area: 'operations', group: 'treasury', label: '项目支出申请', to: '/finance/expenses/project-requests', permission: { resource: 'expenses', action: 'view' }, order: 90 },
    { id: 'finance.operations.treasury.invoice-requests', area: 'operations', group: 'treasury', label: '开票申请', to: '/finance/invoices/requests', permission: { resource: 'invoices', action: 'view' }, order: 30 },
    { id: 'finance.operations.treasury.invoices', area: 'operations', group: 'treasury', label: '正式发票', to: '/finance/invoices', permission: { resource: 'invoices', action: 'view' }, order: 40 },
    { id: 'finance.operations.treasury.receipts', area: 'operations', group: 'treasury', label: '收款与结算', to: '/finance/receipts', permission: { resource: 'receipts', action: 'view' }, order: 50 },
    { id: 'finance.operations.treasury.reconciliation', area: 'operations', group: 'treasury', label: '核销', to: '/finance/reconciliation', permission: { resource: 'reconciliation', action: 'view' }, order: 60 },

    { id: 'finance.operations.treasury.accounts', area: 'operations', group: 'treasury', label: '银行账户', to: '/finance/bank-accounts', permission: { resource: 'bank_accounts', action: 'view' }, order: 10 },
    { id: 'finance.operations.treasury.snapshots', area: 'operations', group: 'treasury', label: '余额快照', to: '/finance/bank-accounts/balances', permission: { resource: 'bank_accounts', action: 'view' }, order: 20 },
    { id: 'finance.console.config.people-cost', area: 'console', group: 'config', label: '人力成本参数', to: '/finance/settings/people-cost-parameters', permission: { resource: 'settings', action: 'admin' }, order: 40 }
  ],
  handlers: [],
  tasks: [],
  objectWorkspaces: [],
  pages: [
    page('/historical-finance', 'historical-finance', 'historical-finance'),
    page('/historical-finance/:code', 'historical-finance-detail', 'historical-finance'),
    page('/receipts/:code/allocate', 'receipt-allocation', 'receipt-allocation'),
    page('/receivable-adjustments', 'receivable-adjustments', 'receivable-adjustments'),
    page('/receivable-adjustments/new', 'receivable-adjustments-new', 'receivable-adjustments-new'),
    page('/receivable-adjustments/:code', 'receivable-adjustments-detail', 'receivable-adjustments-detail'),
    page('/allocation-batches', 'allocation-batches', 'allocation-batches'),
    page('/allocation-batches/:code', 'allocation-batch-detail', 'allocation-batch-detail'),

    page('/migration', 'migration', 'migration'),
    page('/legal-entities', 'legal-entities', 'legal-entities'),
    page('/project-accounting', 'project-accounting', 'project-accounting'),
    page('/project-accounting/:projectCode', 'project-accounting-detail', 'project-accounting-detail'),
    page('/project-cost-allocations', 'cost-allocations', 'cost-allocations'),
    page('/project-cost-allocations/:code', 'cost-allocation-detail', 'cost-allocation-detail'),
    page('/employee-costs', 'employee-costs', 'employee-costs'),
    page('/employee-costs/:code', 'employee-cost-detail', 'employee-cost-detail'),
    page('/payment-requests', 'payment-requests-list', 'payment-requests-list'),
    page('/payment-requests/:code', 'payment-requests-code', 'payment-requests-code'),
    page('/payment-requests/new', 'payment-requests-new', 'payment-requests-new'),
    page('/payment-requests/:code/edit', 'payment-requests-code-edit', 'payment-requests-code-edit'),
    page('/settings/expense-types', 'settings-expense-types-list', 'settings-expense-types-list'),
    page('/settings/expense-types/new', 'settings-expense-types-new', 'settings-expense-types-new'),
    page('/settings/expense-types/:code/edit', 'settings-expense-types-edit', 'settings-expense-types-edit'),
    page('/settings/income-types', 'settings-income-types-list', 'settings-income-types-list'),
    page('/settings/income-types/new', 'settings-income-types-new', 'settings-income-types-new'),
    page('/settings/income-types/:code/edit', 'settings-income-types-edit', 'settings-income-types-edit'),
    page('/settings/subjects', 'settings-subjects-list', 'settings-subjects-list'),
    page('/settings/subjects/new', 'settings-subjects-new', 'settings-subjects-new'),
    page('/settings/subjects/:code/edit', 'settings-subjects-edit', 'settings-subjects-edit'),
    page('/settings/subject-mappings', 'settings-subject-mappings-list', 'settings-subject-mappings-list'),
    page('/settings/subject-mappings/new', 'settings-subject-mappings-new', 'settings-subject-mappings-new'),
    page('/settings/subject-mappings/:code/edit', 'settings-subject-mappings-edit', 'settings-subject-mappings-edit'),
    page('/accounting-objects', 'settings-accounting-objects-list', 'settings-accounting-objects-list'),
    page('/accounting-objects/new', 'settings-accounting-objects-new', 'settings-accounting-objects-new'),
    page('/accounting-objects/:code/edit', 'settings-accounting-objects-edit', 'settings-accounting-objects-edit'),
    page('/audit-logs', 'settings-audit-logs-list', 'settings-audit-logs-list'),
    page('/integrations/approval-instances', 'settings-approval-instances-list', 'settings-approval-instances-list'),
    page('/expenses', 'expenses-list', 'expenses-list'),
    page('/expenses/:code', 'expenses-code', 'expenses-code'),
    page('/expenses/new', 'expenses-new', 'expenses-new'),
    page('/expenses/:code/edit', 'expenses-code-edit', 'expenses-code-edit'),
    page('/expenses/claims', 'claims-list', 'claims-list'),
    page('/expenses/claims/:code', 'claims-code', 'claims-code'),
    page('/expenses/claims/new', 'claims-new', 'claims-new'),
    page('/expenses/claims/:code/edit', 'claims-code-edit', 'claims-code-edit'),
    page('/expenses/project-requests', 'project-requests-list', 'project-requests-list'),
    page('/expenses/project-requests/:code', 'project-requests-code', 'project-requests-code'),
    page('/expenses/project-requests/new', 'project-requests-new', 'project-requests-new'),
    page('/expenses/project-requests/:code/edit', 'project-requests-code-edit', 'project-requests-code-edit'),
    page('/expenses/projects', 'expenses-projects', 'expenses-projects'),
    page('/invoices/requests', 'invoice-requests-list', 'invoice-requests-list'),
    page('/invoices/requests/:code', 'invoice-requests-code', 'invoice-requests-code'),
    page('/invoices/requests/:code/edit', 'invoice-requests-code-edit', 'invoice-requests-code-edit'),
    page('/invoices/requests/new', 'invoice-requests-new', 'invoice-requests-new'),
    page('/invoices', 'invoices-list', 'invoices-list'),
    page('/invoices/:code', 'invoices-code', 'invoices-code'),
    page('/invoices/:code/edit', 'invoices-code-edit', 'invoices-code-edit'),
    { path: '/receipts', name: 'receipts-list', file: fileURLToPath(new URL('../../enterprise/app/components/FinanceSettlementPage.vue', import.meta.url)) },
    page('/receipts/:code', 'receipts-code', 'receipts-code'),
    page('/receipts/:code/edit', 'receipts-code-edit', 'receipts-code-edit'),
    page('/receipts/new', 'receipts-new', 'receipts-new'),
    page('/reconciliation', 'reconciliation-list', 'reconciliation-list'),
    page('/reconciliation/new', 'reconciliation-new', 'reconciliation-new'),
    page('/invoices/requests/:code/issue', 'invoice-requests-issue', 'invoice-requests-issue'),
    page('/invoices/requests/:code/assign-issuance', 'invoice-requests-assign-issuance', 'invoice-requests-assign-issuance'),
    page('/receipts/:code/classify', 'receipts-classify', 'receipts-classify'),
    page('/reconciliation/:code/void', 'reconciliation-void', 'reconciliation-void'),

    page('/bank-accounts', 'bank-accounts', 'bank-accounts'),
    page('/bank-accounts/balances', 'balance-snapshots', 'balance-snapshots'),
    page('/bank-accounts/:code', 'bank-account-detail', 'bank-account-detail'),
    page('/settings/people-cost-parameters', 'people-cost-parameters', 'people-cost-parameters'),
    page('/settings/people-cost-parameters/new', 'people-cost-parameter-create', 'people-cost-parameter-form'),
    page('/settings/people-cost-parameters/:code/edit', 'people-cost-parameter-edit', 'people-cost-parameter-form')
  ]
})
