// Preserve Node runtime settings when building without credential-bearing dotenv.
export function nuxtPlatformEnv(env) {
  // /proc environ also contains lowercase PM2 fields (name, pm_id, watch,
  // pm_exec_path). Feeding them back as env can overwrite PM2's app definition.
  const result = Object.fromEntries(Object.entries(env).filter(([key]) => /^[A-Z][A-Z0-9_]*$/.test(key)
    && !/^(PM2_|PM_ID$|NODE_APP_INSTANCE$|NODE_UNIQUE_ID$|NODE_CHANNEL_FD$)/.test(key)))
  const fields = {
    SECURITY_OPS_UIDS: 'PLATFORM_OPS_UIDS', SECURITY_OPS_BOOTSTRAP_UIDS: 'PLATFORM_BOOTSTRAP_OPS_UIDS',
    SECURITY_ENABLE_OPS_RBAC: 'PLATFORM_ENABLE_OPS_RBAC', SECURITY_ALLOW_OPS_UID_FALLBACK: 'PLATFORM_ALLOW_OPS_UID_FALLBACK',
    SECURITY_ALLOW_LEGACY_ADMIN_API: 'PLATFORM_ALLOW_LEGACY_ADMIN_API', SECURITY_PLATFORM_SIGNING_KEY_DIR: 'PLATFORM_SIGNING_KEY_DIR',
    AUTH_SESSION_TTL_SECONDS: 'PLATFORM_AUTH_SESSION_TTL_SECONDS', AUTH_RESEND_API_KEY: 'RESEND_API_KEY',
    AUTH_EMAIL_FROM: 'PLATFORM_AUTH_EMAIL_FROM', AUTH_ACTIVATION_BASE_URL: 'PLATFORM_AUTH_ACTIVATION_BASE_URL',
    AUTH_EMAIL_ACTIVATION_TTL_SECONDS: 'PLATFORM_AUTH_EMAIL_ACTIVATION_TTL_SECONDS',
    AUTH_GOOGLE_CLIENT_ID: 'GOOGLE_OAUTH_CLIENT_ID', AUTH_GOOGLE_CLIENT_SECRET: 'GOOGLE_OAUTH_CLIENT_SECRET',
    AUTH_GOOGLE_REDIRECT_URI: 'GOOGLE_OAUTH_REDIRECT_URI', AUTH_GOOGLE_HOSTED_DOMAIN: 'GOOGLE_OAUTH_HOSTED_DOMAIN',
    AUTH_GOOGLE_ALLOWED_EMAILS: 'GOOGLE_OAUTH_ALLOWED_EMAILS', AUTH_GOOGLE_ALLOWED_DOMAINS: 'GOOGLE_OAUTH_ALLOWED_DOMAINS',
    AUTH_WECOM_CORPID: 'WECOM_CORPID', AUTH_WECOM_CORPSECRET: 'WECOM_CORPSECRET', AUTH_WECOM_AGENTID: 'WECOM_AGENTID',
    AUTH_WECOM_REDIRECT_URI: 'WECOM_OAUTH_REDIRECT_URI', AUTH_WECOM_ALLOWED_USERIDS: 'WECOM_OAUTH_ALLOWED_USERIDS',
    AUTH_WECOM_ALLOW_ALL: 'WECOM_OAUTH_ALLOW_ALL', GITLAB_BASE_URL: 'GITLAB_BASE_URL', GITLAB_TOKEN: 'GITLAB_BOT_TOKEN',
    GITLAB_DEFAULT_MANIFEST_PATH: 'GITLAB_DEFAULT_APP_MANIFEST_PATH', GITLAB_REQUEST_TIMEOUT_MS: 'GITLAB_REQUEST_TIMEOUT_MS',
    OBSERVABILITY_API_URL: 'HZY_OBSERVABILITY_API_URL', OBSERVABILITY_ADMIN_TOKEN: 'HZY_OBSERVABILITY_ADMIN_TOKEN',
    PUBLIC_SERVICE_URL: 'PLATFORM_SERVICE_URL'
  }
  for (const key of ['HOST', 'PORT', 'NAME', 'USER', 'PASSWORD', 'CONNECTION_LIMIT']) fields[`DB_${key}`] = `DB_${key}`
  for (const [target, source] of Object.entries(fields)) if (env[source] !== undefined) result[`NUXT_${target}`] = env[source]
  result.NUXT_SECURITY_INTERNAL_SERVICE_TOKENS = [env.HZY_CLOUDFLARE_INTERNAL_TOKEN, env.PLATFORM_INTERNAL_SERVICE_TOKENS, env.PLATFORM_INTERNAL_SERVICE_TOKEN].filter(Boolean).join(',')
  result.NUXT_AUTH_DEV_MOCK_ENABLED = 'false'
  result.NUXT_PUBLIC_AUTH_DEV_MOCK_ENABLED = 'false'
  return result
}
