-- APF-13b candidate only; do not execute as part of delivery.
CREATE TABLE finance_payment_request (
    id                      BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    code                    VARCHAR(50) NOT NULL COMMENT '付款申请编号',
    title                   VARCHAR(200) NOT NULL COMMENT '申请标题',
    payment_type            VARCHAR(30) NOT NULL COMMENT '付款类型：supplier/customer_refund/loan/expense/other',
    applicant_uid       VARCHAR(64) NOT NULL COMMENT '申请人UID',
    applicant_dept_code     VARCHAR(50) DEFAULT NULL COMMENT '申请人部门编码',
    project_code            VARCHAR(50) DEFAULT NULL COMMENT '项目编码(Aims/Console)',
    contract_code           VARCHAR(50) DEFAULT NULL COMMENT '合同编码(Altoc)',
    customer_code           VARCHAR(50) DEFAULT NULL COMMENT '客户编码(Altoc)',
    supplier_code           VARCHAR(50) DEFAULT NULL COMMENT '供应商编码',
    payee_name              VARCHAR(200) NOT NULL COMMENT '收款方名称',
    payee_account_masked    VARCHAR(100) DEFAULT NULL COMMENT '收款方账号脱敏值',
    payee_account_secret_ref VARCHAR(200) DEFAULT NULL COMMENT '收款方账号密文引用(Console Vault secret_ref)',
    payee_bank              VARCHAR(200) DEFAULT NULL COMMENT '收款方开户行',
    requested_amount        DECIMAL(18,2) NOT NULL COMMENT '申请付款金额',
    approved_amount         DECIMAL(18,2) DEFAULT NULL COMMENT '审批通过金额',
    paid_amount             DECIMAL(18,2) DEFAULT 0.00 COMMENT '已付款金额',
    planned_pay_date        DATE DEFAULT NULL COMMENT '计划付款日期',
    bank_account_id         BIGINT DEFAULT NULL COMMENT '付款账户ID',
    status                  VARCHAR(30) DEFAULT 'draft' COMMENT '状态：draft/pending_approval/approved/rejected/paid/canceled',
    workflow_instance_id    VARCHAR(100) DEFAULT NULL COMMENT 'Workflow审批实例ID',
    submitted_at            DATETIME DEFAULT NULL COMMENT '提交时间',
    approved_at             DATETIME DEFAULT NULL COMMENT '审批通过时间',
    rejected_at             DATETIME DEFAULT NULL COMMENT '审批拒绝时间',
    reject_reason           VARCHAR(500) DEFAULT NULL COMMENT '拒绝原因',
    paid_at                 DATETIME DEFAULT NULL COMMENT '付款时间',
    generated_expense_id    BIGINT DEFAULT NULL COMMENT '生成的支出台账ID',
    remark                  VARCHAR(500) DEFAULT NULL COMMENT '备注',
    created_by              VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    updated_by              VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    created_at              DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at              DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at              DATETIME DEFAULT NULL COMMENT '软删除时间',

    row_version INT UNSIGNED NOT NULL DEFAULT 1,
    confirmed_by VARCHAR(64) DEFAULT NULL,
    handler_uid VARCHAR(64) DEFAULT NULL,
    currency_code CHAR(3) NOT NULL DEFAULT 'CNY',
    UNIQUE KEY uk_finance_payment_request_code (code),
    INDEX idx_finance_payment_request_type (payment_type),
    INDEX idx_finance_payment_request_applicant (applicant_uid),
    INDEX idx_finance_payment_request_project (project_code),
    INDEX idx_finance_payment_request_contract (contract_code),
    INDEX idx_finance_payment_request_bank_account (bank_account_id),
    INDEX idx_finance_payment_request_status (status),
    INDEX idx_finance_payment_request_workflow (workflow_instance_id),
    INDEX idx_finance_payment_request_deleted (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='付款申请';
