-- Candidate only. Not executed; owning Finance canonical APF-13a subset.

CREATE TABLE finance_expense (
    id                      BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    code                    VARCHAR(50) NOT NULL COMMENT '支出编号',
    expense_type_id         BIGINT DEFAULT NULL COMMENT '费用/支出类型ID',
    subject_id              BIGINT DEFAULT NULL COMMENT '财务科目ID',
    expense_date            DATE NOT NULL COMMENT '支出日期',
    expense_amount          DECIMAL(18,2) NOT NULL COMMENT '支出金额',
    fee_amount              DECIMAL(18,2) DEFAULT 0.00 COMMENT '手续费',
    currency_code           VARCHAR(10) DEFAULT 'CNY' COMMENT '币种',
    bank_account_id         BIGINT DEFAULT NULL COMMENT '付款账户ID',
    project_code            VARCHAR(50) DEFAULT NULL COMMENT '项目编码(Aims/Console)',
    contract_code           VARCHAR(50) DEFAULT NULL COMMENT '合同编码(Altoc)',
    customer_code           VARCHAR(50) DEFAULT NULL COMMENT '客户编码(Altoc)',
    department_code         VARCHAR(50) DEFAULT NULL COMMENT '归属部门编码',
    accounting_object_type  VARCHAR(50) DEFAULT NULL COMMENT '核算对象类型',
    accounting_object_code  VARCHAR(50) DEFAULT NULL COMMENT '核算对象编码',
    sales_scope_type        VARCHAR(30) DEFAULT NULL COMMENT '销售费用归集范围：region/customer/opportunity/contract/sales_campaign/general',
    sales_scope_code        VARCHAR(50) DEFAULT NULL COMMENT '销售费用归集对象编码',
    sales_region_code       VARCHAR(50) DEFAULT NULL COMMENT '销售区域编码',
    sales_owner_uid         VARCHAR(50) DEFAULT NULL COMMENT '销售负责人UID',
    handler_uid         VARCHAR(50) DEFAULT NULL COMMENT '经办人UID',
    payee_name              VARCHAR(200) DEFAULT NULL COMMENT '收款方名称',
    payee_account_masked    VARCHAR(100) DEFAULT NULL COMMENT '收款方账号脱敏值',
    payee_bank              VARCHAR(200) DEFAULT NULL COMMENT '收款方开户行',
    payment_channel         VARCHAR(30) DEFAULT NULL COMMENT '支付渠道：cash/bank_transfer/third_party/other',
    source_request_type     VARCHAR(50) DEFAULT NULL COMMENT '来源申请类型：finance_expense_claim/project_expense/payment_request/manual/migration',
    source_request_code     VARCHAR(50) DEFAULT NULL COMMENT '来源申请编号',
    status                  VARCHAR(30) DEFAULT 'draft' COMMENT '状态：draft/pending_payment/paid/confirmed/canceled',
    description             VARCHAR(500) DEFAULT NULL COMMENT '事由',
    source_refs_json        JSON DEFAULT NULL COMMENT '审批/收入/旧系统等引用',
    created_by              VARCHAR(50) DEFAULT NULL COMMENT '创建人',
    updated_by              VARCHAR(50) DEFAULT NULL COMMENT '更新人',
    created_at              DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at              DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at              DATETIME DEFAULT NULL COMMENT '软删除时间',

    row_version INT UNSIGNED NOT NULL DEFAULT 1,
    confirmed_by VARCHAR(64) DEFAULT NULL,
    UNIQUE KEY uk_finance_expense_source (source_request_type, source_request_code),
    UNIQUE KEY uk_finance_expense_code (code),
    INDEX idx_finance_expense_type (expense_type_id),
    INDEX idx_finance_expense_subject (subject_id),
    INDEX idx_finance_expense_date (expense_date),
    INDEX idx_finance_expense_project (project_code),
    INDEX idx_finance_expense_contract (contract_code),
    INDEX idx_finance_expense_department (department_code),
    INDEX idx_finance_expense_accounting_object (accounting_object_type, accounting_object_code),
    INDEX idx_finance_expense_sales_scope (sales_scope_type, sales_scope_code),
    INDEX idx_finance_expense_sales_region (sales_region_code),
    INDEX idx_finance_expense_sales_owner (sales_owner_uid),
    INDEX idx_finance_expense_handler (handler_uid),
    INDEX idx_finance_expense_status (status),
    INDEX idx_finance_expense_deleted (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='支出台账';

CREATE TABLE finance_expense_claim (
    id                      BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    code                    VARCHAR(50) NOT NULL COMMENT '报销单编号',
    title                   VARCHAR(200) NOT NULL COMMENT '报销标题',
    applicant_uid       VARCHAR(50) NOT NULL COMMENT '申请人UID',
    applicant_dept_code     VARCHAR(50) DEFAULT NULL COMMENT '申请人部门编码',
    project_code            VARCHAR(50) DEFAULT NULL COMMENT '项目编码(Aims/Console)',
    contract_code           VARCHAR(50) DEFAULT NULL COMMENT '合同编码(Altoc)',
    customer_code           VARCHAR(50) DEFAULT NULL COMMENT '客户编码(Altoc)',
    total_amount            DECIMAL(18,2) NOT NULL COMMENT '报销总额',
    approved_amount         DECIMAL(18,2) DEFAULT NULL COMMENT '审批通过金额',
    paid_amount             DECIMAL(18,2) DEFAULT 0.00 COMMENT '已支付金额',
    currency_code           VARCHAR(10) DEFAULT 'CNY' COMMENT '币种',
    cost_bearer_type        VARCHAR(30) DEFAULT NULL COMMENT '成本承担方：company/customer/project/shared',
    cost_bearer_code        VARCHAR(50) DEFAULT NULL COMMENT '成本承担方编码',
    status                  VARCHAR(30) DEFAULT 'draft' COMMENT '状态：draft/pending_approval/approved/rejected/paid/canceled',
    workflow_instance_id    VARCHAR(100) DEFAULT NULL COMMENT 'Workflow审批实例ID',
    submitted_at            DATETIME DEFAULT NULL COMMENT '提交时间',
    approved_at             DATETIME DEFAULT NULL COMMENT '审批通过时间',
    rejected_at             DATETIME DEFAULT NULL COMMENT '审批拒绝时间',
    reject_reason           VARCHAR(500) DEFAULT NULL COMMENT '拒绝原因',
    paid_at                 DATETIME DEFAULT NULL COMMENT '支付时间',
    generated_expense_id    BIGINT DEFAULT NULL COMMENT '生成的支出台账ID',
    remark                  VARCHAR(500) DEFAULT NULL COMMENT '备注',
    created_by              VARCHAR(50) DEFAULT NULL COMMENT '创建人',
    updated_by              VARCHAR(50) DEFAULT NULL COMMENT '更新人',
    created_at              DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at              DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at              DATETIME DEFAULT NULL COMMENT '软删除时间',

    row_version INT UNSIGNED NOT NULL DEFAULT 1,
    confirmed_by VARCHAR(64) DEFAULT NULL,
    handler_uid VARCHAR(64) DEFAULT NULL,
    UNIQUE KEY uk_expense_claim_code (code),
    INDEX idx_expense_claim_applicant (applicant_uid),
    INDEX idx_expense_claim_project (project_code),
    INDEX idx_expense_claim_contract (contract_code),
    INDEX idx_expense_claim_status (status),
    INDEX idx_expense_claim_workflow (workflow_instance_id),
    INDEX idx_expense_claim_deleted (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='费用报销单';

CREATE TABLE finance_expense_claim_item (
    id                  BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    claim_id            BIGINT NOT NULL COMMENT '报销单ID',
    expense_type_id     BIGINT DEFAULT NULL COMMENT '费用类型ID',
    subject_id          BIGINT DEFAULT NULL COMMENT '财务科目ID',
    occurred_at         DATE DEFAULT NULL COMMENT '费用发生日期',
    amount              DECIMAL(18,2) NOT NULL COMMENT '金额',
    tax_amount          DECIMAL(18,2) DEFAULT NULL COMMENT '税额',
    invoice_no          VARCHAR(80) DEFAULT NULL COMMENT '票据/发票号',
    description         VARCHAR(500) DEFAULT NULL COMMENT '说明',
    sort_no             INT DEFAULT 0 COMMENT '排序',
    created_at          DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at          DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',

    INDEX idx_claim_item_claim (claim_id),
    INDEX idx_claim_item_expense_type (expense_type_id),
    INDEX idx_claim_item_subject (subject_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='费用报销明细';

CREATE TABLE finance_project_expense_request (
    id                      BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    code                    VARCHAR(50) NOT NULL COMMENT '项目支出申请编号',
    title                   VARCHAR(200) NOT NULL COMMENT '申请标题',
    applicant_uid       VARCHAR(50) NOT NULL COMMENT '申请人UID',
    applicant_dept_code     VARCHAR(50) DEFAULT NULL COMMENT '申请人部门编码',
    project_code            VARCHAR(50) NOT NULL COMMENT '项目编码(Aims/Console)',
    contract_code           VARCHAR(50) DEFAULT NULL COMMENT '合同编码(Altoc)',
    customer_code           VARCHAR(50) DEFAULT NULL COMMENT '客户编码(Altoc)',
    supplier_code           VARCHAR(50) DEFAULT NULL COMMENT '供应商编码(Assets/Finance)',
    total_amount            DECIMAL(18,2) NOT NULL COMMENT '申请总额',
    approved_amount         DECIMAL(18,2) DEFAULT NULL COMMENT '审批通过金额',
    status                  VARCHAR(30) DEFAULT 'draft' COMMENT '状态：draft/pending_approval/approved/rejected/paid/canceled',
    workflow_instance_id    VARCHAR(100) DEFAULT NULL COMMENT 'Workflow审批实例ID',
    submitted_at            DATETIME DEFAULT NULL COMMENT '提交时间',
    approved_at             DATETIME DEFAULT NULL COMMENT '审批通过时间',
    rejected_at             DATETIME DEFAULT NULL COMMENT '审批拒绝时间',
    reject_reason           VARCHAR(500) DEFAULT NULL COMMENT '拒绝原因',
    generated_expense_id    BIGINT DEFAULT NULL COMMENT '生成的支出台账ID',
    remark                  VARCHAR(500) DEFAULT NULL COMMENT '备注',
    created_by              VARCHAR(50) DEFAULT NULL COMMENT '创建人',
    updated_by              VARCHAR(50) DEFAULT NULL COMMENT '更新人',
    created_at              DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at              DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at              DATETIME DEFAULT NULL COMMENT '软删除时间',

    row_version INT UNSIGNED NOT NULL DEFAULT 1,
    confirmed_by VARCHAR(64) DEFAULT NULL,
    handler_uid VARCHAR(64) DEFAULT NULL,
    currency_code CHAR(3) NOT NULL DEFAULT 'CNY',
    paid_at DATETIME DEFAULT NULL,
    UNIQUE KEY uk_project_expense_request_code (code),
    INDEX idx_project_expense_request_project (project_code),
    INDEX idx_project_expense_request_contract (contract_code),
    INDEX idx_project_expense_request_applicant (applicant_uid),
    INDEX idx_project_expense_request_status (status),
    INDEX idx_project_expense_request_workflow (workflow_instance_id),
    INDEX idx_project_expense_request_deleted (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='项目支出申请';

CREATE TABLE finance_project_expense_request_item (
    id                  BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    request_id          BIGINT NOT NULL COMMENT '项目支出申请ID',
    expense_type_id     BIGINT DEFAULT NULL COMMENT '费用类型ID',
    subject_id          BIGINT DEFAULT NULL COMMENT '财务科目ID',
    item_name           VARCHAR(200) NOT NULL COMMENT '支出项目名称',
    amount              DECIMAL(18,2) NOT NULL COMMENT '金额',
    quantity            DECIMAL(12,2) DEFAULT NULL COMMENT '数量',
    unit_price          DECIMAL(18,2) DEFAULT NULL COMMENT '单价',
    description         VARCHAR(500) DEFAULT NULL COMMENT '说明',
    sort_no             INT DEFAULT 0 COMMENT '排序',
    created_at          DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at          DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',

    INDEX idx_project_expense_item_request (request_id),
    INDEX idx_project_expense_item_type (expense_type_id),
    INDEX idx_project_expense_item_subject (subject_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='项目支出申请明细';
