import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import test from 'node:test'
import { goCompanySummaryCommandDigest, goCompanySummaryCommandJSON, matchesCompanySummaryCommandDigest } from '../server/utils/companyWeeklySummaryCommandDigest.ts'

// Generated by integrationoperation.ValidateAndDigestCommand in
// data-runtime/internal/integrationoperation/company_summary_digest_contract_test.go.
const goGolden = '19505b89b3d61d1cf29e62bc5a88f914c9880017f98011f8b98133bdf1bfdfcf'
const command = {
  periodKey: '2026-W40',
  summaryId: 17,
  summaryVersionId: 23,
  revisionNo: 3,
  title: '公司汇总 & 进展',
  markdownSha256: 'a8b2597965989c0ce74f320695fdc2d63da08983502124addd34280aee9d59db',
  recipientUids: [] as string[],
  documentType: 'company',
  idempotencyKey: 'aims:company-weekly-summary:2026-W40:r3:publish:v1',
  operatorUid: 'zhouguangying'
}

const legacyDigest = (value: Record<string, unknown>) =>
  createHash('sha256').update(JSON.stringify(value), 'utf8').digest('hex')

test('Codocs accepts the Go-generated W40-shaped command digest and legacy TS producer digest', () => {
  assert.equal(goCompanySummaryCommandDigest(command), goGolden)
  assert.match(goCompanySummaryCommandJSON(command), /公司汇总 \\u0026 进展/)
  assert.notEqual(legacyDigest(command), goGolden)
  assert.equal(legacyDigest(command), '33781299dc370b77adbe8defa12af2b3c571411f7c305106f17b5814872e02c3')
  assert.equal(matchesCompanySummaryCommandDigest(command, goGolden), true)
  assert.equal(matchesCompanySummaryCommandDigest(command, legacyDigest(command)), true)
})

test('changing any validated company summary command field invalidates both digests', () => {
  const changes: Record<keyof typeof command, unknown> = {
    periodKey: '2026-W41', summaryId: 18, summaryVersionId: 24, revisionNo: 4,
    title: '公司汇总 & 变更', markdownSha256: 'b'.repeat(64), recipientUids: ['member-1'],
    documentType: 'personal', idempotencyKey: 'changed-key', operatorUid: 'other-user'
  }
  for (const [field, changed] of Object.entries(changes)) {
    const altered = { ...command, [field]: changed }
    assert.notEqual(goCompanySummaryCommandDigest(altered), goGolden, field)
    assert.notEqual(legacyDigest(altered), legacyDigest(command), field)
    assert.equal(matchesCompanySummaryCommandDigest(altered, goGolden), false, field)
    assert.equal(matchesCompanySummaryCommandDigest(altered, legacyDigest(command)), false, field)
  }
})

test('unsupported nested or non-finite command values cannot match either digest', () => {
  for (const value of [{ nested: true }, [['nested']], Number.NaN, Number.POSITIVE_INFINITY, 1.5]) {
    const altered = { ...command, title: value }
    assert.equal(matchesCompanySummaryCommandDigest(altered, goGolden), false)
    assert.equal(matchesCompanySummaryCommandDigest(altered, legacyDigest(command)), false)
    assert.throws(() => goCompanySummaryCommandJSON(altered), TypeError)
  }
})
