import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import assert from 'node:assert/strict'
import { test } from 'node:test'

const root = resolve(import.meta.dirname, '..')
const read = (file: string) => readFileSync(resolve(root, file), 'utf8')

test('Aims project document content service route binds service identity before body/runtime/OSS', () => {
  const route = read('server/api/v1/service/project-documents/[uuid]/content.post.ts')

  assert.match(route, /AIMS_PROJECT_DOCUMENT_CONTENT_SERVICE_AUTH/)
  assert.match(route, /requireCodocsServiceTenantDeploymentBinding/)
  assert.match(route, /verifyServiceCommandRuntimeHeaders/)
  assert.match(route, /hashServiceCommandPayload/)
  assert.match(route, /getHeader\(event, 'x-hzy-tenant'\)/)
  assert.match(route, /getHeader\(event, 'x-hzy-deployment'\)/)
  assert.match(route, /codocs:project-document:content:read/)
  assert.match(route, /aims\.codocs\.project-document\.content-read\.v1/)
  assert.match(route, /action\) !== 'content:read'/)
  assert.match(route, /callCodocsTenantRuntime/)
  assert.match(read('../foundation/server/utils/consoleOidc.ts'), /event\.context\.consoleAuth = context/)
  assert.match(read('../foundation/server/utils/tenantRuntimeClient.ts'), /command\?: Record<string, unknown>/)
  assert.match(read('../foundation/server/utils/tenantRuntimeClient.ts'), /command\?\.actorUid/)
  assert.match(route, /serviceTokenSourceBinding:\s*'service-client-policy'/)
  assert.match(route, /serviceCommandActor:\s*\{\s*uid:\s*text\(serviceCommand\.command\?\.actorUid\)\s*\}/)
  assert.match(route, /downloadDocument/)
  assert.ok(route.indexOf('requireCodocsServiceTenantDeploymentBinding(') < route.indexOf('readBody<'))
  const runtimeCall = route.indexOf('grant = await callCodocsTenantRuntime')
  const ossRead = route.indexOf('content = (await downloadDocument')
  const signatureVerify = route.indexOf('await verifyServiceCommandRuntimeHeaders')
  assert.ok(route.indexOf('requireCodocsServiceTenantDeploymentBinding(') < runtimeCall)
  assert.ok(signatureVerify < runtimeCall)
  assert.ok(runtimeCall < ossRead)
  assert.match(route, /tenant runtime rejected/)
  assert.doesNotMatch(route, /url:\s*grant\./)
  assert.doesNotMatch(route, /ossPath:\s*grant\./)
})

test('runtime contract is source-bound and reuses Codocs document ACL rather than body project roles', () => {
  const route = read('server/api/v1/service/project-documents/[uuid]/content.post.ts')
  const runtime = read('../data-runtime/internal/apps/codocs/project_document_service.go')
  const adapter = read('../data-runtime/internal/apps/codocs/adapter.go')
  const middleware = read('server/middleware/tenant-runtime.ts')
  const policy = read('server/lib/serviceAuthPolicy.ts')

  assert.match(policy, /scope: 'codocs:project-document:content:read', allowedApps: \['aims'\], allowedClientCodes: \['aims\.runtime'\], exactScope: true/)
  assert.match(route, /sourceClientId:\s*'aims\.runtime'/)
  assert.match(read('../foundation/server/utils/serviceOidc.ts'), /const gatewayContext = input\.event/)
  assert.match(read('../foundation/server/utils/serviceOidc.ts'), /const requestHeaders = gatewayContext/)
  assert.match(read('../foundation/server/utils/serviceOidc.ts'), /headers: requestHeaders/)
  assert.match(read('../foundation/server/utils/tenantRuntimeClient.ts'), /usesServiceClientPolicy[\s\S]*tokenMetadata\.deployment/)
  assert.match(runtime, /TrustedServiceCommandSourceAppKey\)\) != "aims"/)
  assert.match(runtime, /TrustedServiceCommandSourceClientKey\)\) != "aims\.runtime"/)
  assert.match(runtime, /hzy_runtime_actor_purpose"\)\) != "service-command"/)
  assert.match(runtime, /a\.documentAccess\(ctx, uuid, query\)/)
  assert.match(runtime, /int64Value\(document\["status"\]\) != 1/)
  assert.match(runtime, /storage doc_type\/project_code cannot be treated as the project boundary/)
  assert.doesNotMatch(runtime, /document\["doc_type"\] != "project"/)
  assert.doesNotMatch(runtime, /actorProjectCodes/)
  assert.doesNotMatch(runtime, /actorRoles/)
  assert.match(adapter, /service\/project-documents/)
  assert.match(middleware, /project-documents/)
})
