/** UI only: identifiers remain the existing typed API values. */
export const apfEnumLabels: Record<string, string> = {
  government: '政府', group: '集团', third_party: '第三方', pm: '项目经理', business: '商务', presales: '售前', finance: '财务', member: '成员', todo: '待处理', done: '已完成', overdue: '已逾期', supportive: '支持', resistant: '反对', user: '用户', system: '系统', purpose: '委托用途', in_process: '进程内', software: '软件', own: '自有', customer: '客户', lead: '线索', opportunity: '商机', quotation: '报价', contract: '合同', service_ticket: '工单', codocs: '文档系统', external_url: '外部链接', marketing: '市场活动', referral: '推荐', partner: '合作伙伴', approval_pending: '审批中', archived: '已归档', special_vat: '增值税专用发票', general_vat: '增值税普通发票', electronic: '电子发票', sent: '已发送', voided: '已作废', purchaser: '采购方', tech_influencer: '技术影响者', fulfilled: '已履行', blocked: '受阻', not_planned: '未计划', activating: '启动中', fixed_price: '固定价格', time_and_material: '按工时与材料', point_in_time: '时点确认', over_time: '期间确认', waived: '已豁免', contract_line: '合同行', template: '模板', aims: '项目管理', assets: '资产管理', altoc: '销售管理', skipped: '已跳过', supplier: '供应商', organization: '组织', person: '个人', buyer: '买方', seller: '卖方', payer: '付款方', end_customer: '最终客户', vendor: '供应方', guarantor: '担保方', ratio: '比例', stage: '阶段', annual: '年度', internal: '内部', created_from_contract: '由合同创建', linked_existing: '关联已有项目', receivable: '应收', payable: '应付', payment_term: '付款条款', unallocated: '未分配', amount: '金额', workdays: '工作日',
  M: '管理序列', P: '专业序列', full_time: '全职', part_time: '兼职', outsourced: '外包', intern: '实习', agent: '代理',
  active: '有效', inactive: '停用', leaving: '待离职', left: '已离职', onboard: '入职', transfer: '调动', rank_change: '调级', leave: '离职',
  none: '无需审批', draft: '草稿', pending: '待处理', approved: '已批准', rejected: '已退回', cancelled: '已取消',
  dingtalk: '钉钉', oa_archive: '原档案', manual: '人工', standard_rate: '标准费率', finance_adjustment: '财务调整', import: '导入', standard: '标准', actual: '实际', manual_adjusted: '人工调整',
  acceptance: '验收', advance: '预付款', annual_service: '年度服务', contract_signed: '合同签署', customization: '定制', date: '日期', delivery: '交付', goods_delivery: '货物交付', hardware: '硬件', implementation: '实施', maintenance: '维保', milestone: '里程碑', milestone_accepted: '里程碑验收', month: '月', obligation_accepted: '义务验收', obligation_completed: '义务完成', one_time: '一次性', optional: '可选', other: '其他', quarter: '季度', recurring: '周期', required: '必须', retention: '质保金', service: '服务', service_delivery: '服务交付', service_end: '服务结束', service_period: '服务期间', software_license: '软件许可', stage_completed: '阶段完成', training: '培训', warranty: '保修', year: '年',
  info_gathering: '信息收集', qualification: '资格审查', bid_preparation: '标书准备', bid_submitted: '已投标', bid_opening: '开标', won: '已赢单', lost: '已输单', review_done: '复盘完成', abandoned: '已放弃', open: '进行中', invited: '邀请招标', negotiation: '谈判', single_source: '单一来源', inquiry: '询价', price: '价格', technical: '技术', relationship: '关系',
  upsell: '增购', cross_sell: '交叉销售', identified: '已识别', contacted: '已联系', proposal: '方案', closed: '已关闭', low: '低', normal: '普通', medium: '中', high: '高', urgent: '紧急', incident: '故障', consulting: '咨询', requirement: '需求', change: '变更', ticket: '工单', hour: '小时', day: '天', planned: '已计划', suspended: '已暂停', expired: '已过期', terminated: '已终止', pending_plan: '待交付计划', delivery_asset: '交付资产', environment: '环境', delivery_asset_environment: '交付资产与环境', operation: '运维', inspection: '巡检', upgrade: '升级', special: '专项',
  awaiting_arrangement: '待安排', completed: '已完成', handover: '工作交接', asset_recovery_coordination: '资产回收协调', mapped: '已绑定', suggested: '待确认', conflict: '存在冲突', unmatched: '待选择', running: '处理中', succeeded: '已成功', failed: '失败', success: '成功',
  not_started: '未开始', in_progress: '进行中', processing: '处理中', accepted: '已接受', submitted: '已提交', waiting_customer: '等待客户', resolved: '已解决', warning: '预警', breached: '已超时', met: '达标', unknown: '待核对', in_service: '服务期内', out_of_service: '服务期外', over_quota: '超额度', idle: '未派发', on_track: '正常',
  awaiting_profile: '待完善资料', ready_for_provisioning: '待开通', reserving_identity: '正在预留身份', provisioning_account: '正在开通账号', activating_employee: '正在建立任职', projecting_authorization: '等待权限同步', provisioning_failed: '开通失败', reservation_expired: '预留已过期', authorization_failed: '权限同步失败',
  following: '跟进中', converted: '已转化', disqualified: '已作废', paused: '已暂停', applying: '申请中', allocated: '已拨付', tob: '企业项目', tog: '政务项目', renewal: '续约', channel: '渠道', direct: '直接采购', competitive_consultation: '竞争性磋商', open_tender: '公开招标', framework: '框架协议', visit: '拜访', call: '电话', demo: '演示', meeting: '会议', tender: '投标', memo: '备忘',
  enabled: '启用', disabled: '停用', pending_approval: '审批中', effective: '已生效', activated: '已启动', billable: '可开票', ready: '待启动', invalid: '已失效', unplanned: '未计划', invoicing: '开票中', invoiced: '已开票', partially_invoiced: '部分开票', partially_received: '部分到账', received: '已到账', bad_debt: '坏账', partially_paid: '部分付款', paid: '已付款', partially_reconciled: '部分核销', reconciled: '已核销', canceled: '已取消',
  sales: '销售', purchase: '采购', pipeline: '储备', best_case: '乐观预测', commit: '预计达成', omitted: '不计预测', decision_maker: '决策者', economic_buyer: '预算负责人', sponsor: '支持者', procurement: '采购', technical_influencer: '技术影响者', end_user: '使用者', competitor_supporter: '竞争方支持者', neutral: '中立', positive: '支持', negative: '反对', proposal_doc: '方案文档', contract_text: '合同文本', meeting_memo: '会议纪要', tender_doc: '招标文档', evidence: '证据', general: '其他资料'
}
export function apfEnumLabel(value: unknown) {
  return value === null || value === undefined || value === '' ? '未填写' : apfEnumLabels[String(value)] || '待核对'
}
export function apfServerFieldErrors(error: unknown, fields: string[]): Record<string, string> {
  const e = error as { statusCode?: number, status?: number, response?: { status?: number }, data?: Record<string, unknown> }
  if (Number(e?.statusCode || e?.status || e?.response?.status) !== 400) return {}
  const data = e.data?.data as Record<string, unknown> | undefined
  const detail = data || e.data || {}
  // Only field names are used. Never render server error text, SQL or URLs.
  const hints = [detail.field, ...Object.keys((detail.fieldErrors || {}) as object), ...(Array.isArray(detail.errors) ? detail.errors.map((v: { name?: string, path?: string }) => v?.name || v?.path) : [])]
  const known = fields.filter(field => hints.includes(field))
  return Object.fromEntries((known.length ? known : fields).map(field => [field, '此字段未通过校验，请核对选项、格式及关联关系']))
}
