-- APF-16b fixed create-only candidate. No legacy writes; no runtime execution.

CREATE TABLE altoc_contract_delivery_asset_plan (
    row_version INT UNSIGNED NOT NULL DEFAULT 1,
    id                      BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    code                    VARCHAR(64) NOT NULL COMMENT '计划交付资产编号',
    contract_id             BIGINT NOT NULL COMMENT '合同ID',
    contract_line_id        BIGINT DEFAULT NULL COMMENT '合同行ID',
    obligation_id           BIGINT DEFAULT NULL COMMENT '履约义务ID',
    customer_code           VARCHAR(100) DEFAULT NULL COMMENT '客户编码',
    name                    VARCHAR(200) NOT NULL COMMENT '计划资产名称',
    product_code            VARCHAR(100) DEFAULT NULL COMMENT '产品编码',
    product_version         VARCHAR(100) DEFAULT NULL COMMENT '产品版本',
    catalog_item_code       VARCHAR(100) DEFAULT NULL COMMENT '目录项编码',
    product_origin          VARCHAR(30) DEFAULT NULL COMMENT '产品来源',
    source_contract_code    VARCHAR(64) NOT NULL COMMENT '来源合同编号',
    source_contract_line_code VARCHAR(64) DEFAULT NULL COMMENT '来源合同行编号',
    source_obligation_code  VARCHAR(64) DEFAULT NULL COMMENT '来源义务编号',
    source_project_code     VARCHAR(64) DEFAULT NULL COMMENT '来源项目编号',
    external_asset_code     VARCHAR(100) DEFAULT NULL COMMENT 'Assets资产编码',
    deployment_mode         VARCHAR(50) DEFAULT NULL COMMENT '部署模式',
    instance_key            VARCHAR(100) DEFAULT NULL COMMENT '实例键',
    tenant_key              VARCHAR(100) DEFAULT NULL COMMENT '租户键',
    environment_code        VARCHAR(100) DEFAULT NULL COMMENT '环境编码',
    license_model           VARCHAR(50) DEFAULT NULL COMMENT '授权模型',
    license_quantity        DECIMAL(18,4) DEFAULT NULL COMMENT '授权数量',
    capacity                DECIMAL(18,4) DEFAULT NULL COMMENT '容量',
    unit                    VARCHAR(30) DEFAULT NULL COMMENT '单位',
    status                  VARCHAR(30) NOT NULL DEFAULT 'planned' COMMENT '状态',
    planned_delivery_at     DATETIME DEFAULT NULL COMMENT '计划交付时间',
    delivered_at            DATETIME DEFAULT NULL COMMENT '交付时间',
    go_live_at              DATETIME DEFAULT NULL COMMENT '上线时间',
    accepted_at             DATETIME DEFAULT NULL COMMENT '验收时间',
    expired_at              DATETIME DEFAULT NULL COMMENT '到期时间',
    terminated_at           DATETIME DEFAULT NULL COMMENT '终止时间',
    warranty_start_at       DATETIME DEFAULT NULL COMMENT '质保开始时间',
    warranty_end_at         DATETIME DEFAULT NULL COMMENT '质保结束时间',
    support_expiry_at       DATETIME DEFAULT NULL COMMENT '支持到期时间',
    source_job_id           BIGINT DEFAULT NULL COMMENT '来源编排作业ID',
    created_by              VARCHAR(50) DEFAULT NULL COMMENT '创建人',
    updated_by              VARCHAR(50) DEFAULT NULL COMMENT '更新人',
    created_at              DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at              DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at              DATETIME DEFAULT NULL COMMENT '软删除时间',

    UNIQUE KEY uk_contract_delivery_asset_plan_code (code),
    UNIQUE KEY uk_contract_delivery_asset_plan_line (contract_id, contract_line_id, instance_key),
    INDEX idx_contract_delivery_asset_contract (contract_id, status),
    INDEX idx_contract_delivery_asset_line (contract_line_id),
    INDEX idx_contract_delivery_asset_customer (customer_code),
    INDEX idx_contract_delivery_asset_external (external_asset_code),
    INDEX idx_contract_delivery_asset_source_job (source_job_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='合同计划交付资产表';

CREATE TABLE altoc_service_agreement (
    row_version INT UNSIGNED NOT NULL DEFAULT 1,
    id                      BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    code                    VARCHAR(64) NOT NULL COMMENT '服务协议编号',
    contract_id             BIGINT NOT NULL COMMENT '合同ID',
    contract_line_id        BIGINT DEFAULT NULL COMMENT '合同行ID',
    customer_code           VARCHAR(100) DEFAULT NULL COMMENT '客户编码',
    name                    VARCHAR(200) NOT NULL COMMENT '服务协议名称',
    service_level           VARCHAR(50) DEFAULT NULL COMMENT '服务等级',
    service_start_date      DATE DEFAULT NULL COMMENT '服务开始日期',
    service_end_date        DATE DEFAULT NULL COMMENT '服务结束日期',
    service_window          VARCHAR(100) DEFAULT NULL COMMENT '服务窗口',
    billing_mode            VARCHAR(50) DEFAULT NULL COMMENT '计费方式',
    renewal_policy          VARCHAR(100) DEFAULT NULL COMMENT '续约策略',
    response_minutes        INT DEFAULT NULL COMMENT '默认响应时限(分钟)',
    resolution_minutes      INT DEFAULT NULL COMMENT '默认解决时限(分钟)',
    included_quota          DECIMAL(10,2) DEFAULT NULL COMMENT '包含工单额度',
    quota_unit              VARCHAR(30) DEFAULT NULL COMMENT '额度单位：ticket/hour/day',
    consumed_quota          DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '已消耗额度',
    renewal_remind_at       DATE DEFAULT NULL COMMENT '续约提醒日期',
    status                  VARCHAR(30) NOT NULL DEFAULT 'planned' COMMENT '状态：planned/active/suspended/expired/terminated/cancelled',
    owner_user_id           VARCHAR(50) DEFAULT NULL COMMENT '负责人',
    maintenance_contract_id BIGINT DEFAULT NULL COMMENT '来源维保合同ID',
    source_job_id           BIGINT DEFAULT NULL COMMENT '来源编排作业ID',
    created_by              VARCHAR(50) DEFAULT NULL COMMENT '创建人',
    updated_by              VARCHAR(50) DEFAULT NULL COMMENT '更新人',
    created_at              DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at              DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at              DATETIME DEFAULT NULL COMMENT '软删除时间',

    UNIQUE KEY uk_service_agreement_code (code),
    UNIQUE KEY uk_service_agreement_line (contract_id, contract_line_id),
    INDEX idx_service_agreement_contract (contract_id, status),
    INDEX idx_service_agreement_customer (customer_code),
    INDEX idx_service_agreement_line (contract_line_id),
    INDEX idx_service_agreement_maintenance (maintenance_contract_id),
    INDEX idx_service_agreement_renewal (renewal_remind_at, status),
    INDEX idx_service_agreement_source_job (source_job_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='服务协议表';

CREATE TABLE altoc_service_agreement_coverage (
    row_version INT UNSIGNED NOT NULL DEFAULT 1,
    id                      BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    coverage_code           VARCHAR(64) NOT NULL COMMENT '服务覆盖关系编号',
    service_agreement_id    BIGINT NOT NULL COMMENT '服务协议ID',
    target_type             VARCHAR(40) NOT NULL DEFAULT 'pending_plan' COMMENT '目标类型：delivery_asset/environment/delivery_asset_environment/pending_plan/legacy',
    source_plan_code        VARCHAR(100) DEFAULT NULL COMMENT 'Altoc合同计划资产编码',
    delivery_asset_code     VARCHAR(100) DEFAULT NULL COMMENT 'Assets正式客户交付资产编码',
    environment_code        VARCHAR(100) DEFAULT NULL COMMENT 'Assets正式环境编码',
    legacy_reference        VARCHAR(255) DEFAULT NULL COMMENT '无法自动解析的旧引用',
    resolution_status       VARCHAR(30) NOT NULL DEFAULT 'pending' COMMENT '解析状态：pending/resolved/needs_review',
    coverage_status         VARCHAR(30) NOT NULL DEFAULT 'planned' COMMENT '覆盖状态：planned/active/suspended/ended/cancelled',
    coverage_scope          VARCHAR(50) DEFAULT NULL COMMENT '覆盖范围',
    product_scope_json      JSON DEFAULT NULL COMMENT '产品覆盖范围快照',
    effective_from          DATE DEFAULT NULL COMMENT '生效日期',
    effective_to            DATE DEFAULT NULL COMMENT '失效日期',
    included                TINYINT NOT NULL DEFAULT 1 COMMENT '是否包含',
    exclusion_note          VARCHAR(500) DEFAULT NULL COMMENT '排除说明',
    source_type             VARCHAR(30) NOT NULL DEFAULT 'manual' COMMENT '来源类型：activation/migration/manual/renewal/callback',
    created_by              VARCHAR(50) DEFAULT NULL COMMENT '创建人',
    updated_by              VARCHAR(50) DEFAULT NULL COMMENT '更新人',
    created_at              DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at              DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at              DATETIME DEFAULT NULL COMMENT '软删除时间',
    active_target_key       VARCHAR(500) GENERATED ALWAYS AS (
      CASE
        WHEN deleted_at IS NULL AND coverage_status <> 'cancelled' THEN CONCAT(
          service_agreement_id, ':', target_type, ':',
          CASE
            WHEN target_type = 'pending_plan' THEN COALESCE(source_plan_code, '')
            WHEN target_type = 'legacy' THEN COALESCE(legacy_reference, '')
            ELSE ''
          END, ':',
          COALESCE(delivery_asset_code, ''), ':',
          COALESCE(environment_code, ''), ':',
          COALESCE(CAST(effective_from AS CHAR), ''), ':',
          COALESCE(CAST(effective_to AS CHAR), '')
        )
        ELSE NULL
      END
    ) STORED,

    UNIQUE KEY uk_service_agreement_coverage_code (coverage_code),
    UNIQUE KEY uk_service_agreement_coverage_target (active_target_key),
    INDEX idx_sac_agreement (service_agreement_id, coverage_status, resolution_status),
    INDEX idx_sac_source_plan (source_plan_code, resolution_status),
    INDEX idx_sac_delivery_asset (delivery_asset_code, coverage_status),
    INDEX idx_sac_environment (environment_code, coverage_status),
    INDEX idx_sac_resolution (resolution_status, target_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='服务协议正式覆盖对象表';

CREATE TABLE altoc_service_agreement_project_rel (
    row_version INT UNSIGNED NOT NULL DEFAULT 1,
    id                      BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    service_agreement_id    BIGINT NOT NULL COMMENT '服务协议ID',
    project_code            VARCHAR(64) NOT NULL COMMENT 'Aims项目编号',
    project_role            VARCHAR(30) NOT NULL DEFAULT 'maintenance' COMMENT '项目角色：maintenance/operation/inspection/upgrade/special',
    is_default              TINYINT NOT NULL DEFAULT 0 COMMENT '是否默认项目',
    effective_from          DATE DEFAULT NULL COMMENT '生效日期',
    effective_to            DATE DEFAULT NULL COMMENT '失效日期',
    status                  VARCHAR(30) NOT NULL DEFAULT 'active' COMMENT '状态：planned/active/suspended/ended',
    source_type             VARCHAR(30) NOT NULL DEFAULT 'manual' COMMENT '来源类型：activation/manual/migration/ticket_resolution',
    created_by              VARCHAR(50) DEFAULT NULL COMMENT '创建人',
    updated_by              VARCHAR(50) DEFAULT NULL COMMENT '更新人',
    created_at              DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at              DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at              DATETIME DEFAULT NULL COMMENT '软删除时间',

    UNIQUE KEY uk_service_agreement_project_role (service_agreement_id, project_code, project_role),
    INDEX idx_sapr_agreement (service_agreement_id, status, is_default),
    INDEX idx_sapr_project (project_code, status),
    INDEX idx_sapr_effective (service_agreement_id, project_role, effective_from, effective_to)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='服务协议-Aims项目关系表';

CREATE TABLE altoc_maintenance_contract (
    row_version INT UNSIGNED NOT NULL DEFAULT 1,
    id                      BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    code                    VARCHAR(30) NOT NULL COMMENT '维保合同编号(MC-xxxxxx)',
    customer_id             BIGINT NOT NULL COMMENT '客户ID',
    contract_id             BIGINT DEFAULT NULL COMMENT '原合同ID',
    opportunity_id          BIGINT DEFAULT NULL COMMENT '来源商机ID',
    delivery_code           VARCHAR(64) DEFAULT NULL COMMENT 'Assets交付视图编号',
    project_code            VARCHAR(64) DEFAULT NULL COMMENT 'Aims项目编号',
    product_code            VARCHAR(64) DEFAULT NULL COMMENT '产品编号',
    product_version         VARCHAR(64) DEFAULT NULL COMMENT '产品版本',
    name                    VARCHAR(200) NOT NULL COMMENT '维保合同名称',
    service_level           VARCHAR(30) DEFAULT 'standard' COMMENT '服务级别：standard/premium/custom',
    service_start_date      DATE NOT NULL COMMENT '服务开始日期',
    service_end_date        DATE NOT NULL COMMENT '服务结束日期',
    amount                  DECIMAL(18,2) DEFAULT 0.00 COMMENT '维保金额',
    currency_code           VARCHAR(10) DEFAULT 'CNY' COMMENT '币种',
    status                  VARCHAR(30) DEFAULT 'active' COMMENT '状态：draft/active/expiring/expired/terminated',
    owner_user_id           VARCHAR(50) DEFAULT NULL COMMENT '客户成功负责人',
    renewal_remind_at       DATE DEFAULT NULL COMMENT '续约提醒日期',
    source_app              VARCHAR(50) DEFAULT NULL COMMENT '来源应用',
    source_biz_type         VARCHAR(50) DEFAULT NULL COMMENT '来源业务类型',
    source_biz_id           VARCHAR(100) DEFAULT NULL COMMENT '来源业务ID',
    remark                  VARCHAR(500) DEFAULT NULL COMMENT '备注',
    created_by              VARCHAR(50) DEFAULT NULL COMMENT '创建人',
    updated_by              VARCHAR(50) DEFAULT NULL COMMENT '更新人',
    created_at              DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at              DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at              DATETIME DEFAULT NULL COMMENT '软删除时间',

    UNIQUE KEY uk_code (code),
    INDEX idx_customer_id (customer_id),
    INDEX idx_contract_id (contract_id),
    INDEX idx_opportunity_id (opportunity_id),
    INDEX idx_delivery_code (delivery_code),
    INDEX idx_project_code (project_code),
    INDEX idx_service_period (service_start_date, service_end_date),
    INDEX idx_status (status),
    INDEX idx_owner_user_id (owner_user_id),
    INDEX idx_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='维保合同表';

CREATE TABLE altoc_service_entitlement (
    row_version INT UNSIGNED NOT NULL DEFAULT 1,
    id                      BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    code                    VARCHAR(30) NOT NULL COMMENT '服务权益编号(SE-xxxxxx)',
    maintenance_contract_id BIGINT NOT NULL COMMENT '维保合同ID',
    service_agreement_id    BIGINT DEFAULT NULL COMMENT '迁移后的服务协议ID',
    entitlement_type        VARCHAR(30) DEFAULT 'sla' COMMENT '权益类型：sla/quota/onsite/remote',
    name                    VARCHAR(120) NOT NULL COMMENT '权益名称',
    service_window          VARCHAR(50) DEFAULT '5x8' COMMENT '服务窗口：5x8/7x24/custom',
    priority                VARCHAR(20) DEFAULT 'normal' COMMENT '适用优先级：low/normal/high/urgent',
    response_minutes        INT DEFAULT NULL COMMENT '响应时限(分钟)',
    resolution_minutes      INT DEFAULT NULL COMMENT '解决时限(分钟)',
    included_quota          DECIMAL(10,2) DEFAULT NULL COMMENT '包含额度',
    quota_unit              VARCHAR(30) DEFAULT NULL COMMENT '额度单位：hour/ticket/day',
    billing_mode            VARCHAR(30) DEFAULT 'included' COMMENT '计费方式：included/billable/overage',
    status                  VARCHAR(20) DEFAULT 'active' COMMENT '状态：active/inactive',
    remark                  VARCHAR(500) DEFAULT NULL COMMENT '备注',
    created_by              VARCHAR(50) DEFAULT NULL COMMENT '创建人',
    updated_by              VARCHAR(50) DEFAULT NULL COMMENT '更新人',
    created_at              DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at              DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',

    UNIQUE KEY uk_code (code),
    INDEX idx_contract_id (maintenance_contract_id),
    INDEX idx_service_agreement_id (service_agreement_id),
    INDEX idx_entitlement_type (entitlement_type),
    INDEX idx_priority (priority),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='服务权益/SLA表';
