-- APF-16c create-only installation candidate; no environment execution.
CREATE TABLE altoc_service_ticket (
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    delivery_hash CHAR(64) DEFAULT NULL,
    id                      BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    code                    VARCHAR(30) NOT NULL COMMENT '服务工单编号(ST-xxxxxx)',
    customer_id             BIGINT NOT NULL COMMENT '客户ID',
    maintenance_contract_id BIGINT DEFAULT NULL COMMENT '维保合同ID',
    contract_id             BIGINT DEFAULT NULL COMMENT '合同ID',
    service_agreement_id    BIGINT DEFAULT NULL COMMENT '服务协议ID',
    service_agreement_code  VARCHAR(64) DEFAULT NULL COMMENT '服务协议编号快照',
    delivery_code           VARCHAR(64) DEFAULT NULL COMMENT 'Assets交付视图编号',
    delivery_asset_code     VARCHAR(100) DEFAULT NULL COMMENT '客户交付资产编码',
    project_code            VARCHAR(64) DEFAULT NULL COMMENT 'Aims项目编号',
    product_code            VARCHAR(64) DEFAULT NULL COMMENT '产品编号',
    product_version         VARCHAR(64) DEFAULT NULL COMMENT '产品版本',
    environment_code        VARCHAR(64) DEFAULT NULL COMMENT '环境编号',
    ticket_type             VARCHAR(30) NOT NULL COMMENT '类型：incident/consulting/requirement/change',
    title                   VARCHAR(200) NOT NULL COMMENT '标题',
    description             TEXT DEFAULT NULL COMMENT '描述',
    priority                VARCHAR(20) DEFAULT 'normal' COMMENT '优先级：low/normal/high/urgent',
    status                  VARCHAR(30) DEFAULT 'open' COMMENT '状态：open/accepted/processing/waiting_customer/resolved/closed/cancelled',
    sla_status              VARCHAR(30) DEFAULT 'not_started' COMMENT 'SLA状态：not_started/on_track/warning/breached/met',
    entitlement_status      VARCHAR(30) NOT NULL DEFAULT 'unknown' COMMENT '权益状态：unknown/in_service/out_of_service/over_quota',
    quota_consumed          DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '本工单已扣减额度',
    reported_by_contact     VARCHAR(100) DEFAULT NULL COMMENT '报障联系人',
    reported_by_phone       VARCHAR(50) DEFAULT NULL COMMENT '联系电话',
    reported_by_email       VARCHAR(100) DEFAULT NULL COMMENT '联系邮箱',
    owner_user_id           VARCHAR(50) DEFAULT NULL COMMENT '客户成功负责人',
    handler_user_id         VARCHAR(50) DEFAULT NULL COMMENT '当前处理人',
    response_due_at         DATETIME DEFAULT NULL COMMENT '响应截止时间',
    resolution_due_at       DATETIME DEFAULT NULL COMMENT '解决截止时间',
    first_responded_at      DATETIME DEFAULT NULL COMMENT '首次响应时间',
    resolved_at             DATETIME DEFAULT NULL COMMENT '解决时间',
    closed_at               DATETIME DEFAULT NULL COMMENT '关闭时间',
    aims_project_code       VARCHAR(64) DEFAULT NULL COMMENT '回流Aims项目编号',
    aims_work_item_key      VARCHAR(100) DEFAULT NULL COMMENT '回流Aims工作项键',
    aims_work_item_type     VARCHAR(50) DEFAULT NULL COMMENT '回流Aims工作项类型',
    aims_dispatch_status    VARCHAR(20) NOT NULL DEFAULT 'idle' COMMENT 'Aims派发：idle/pending/succeeded',
    aims_dispatch_operation_key VARCHAR(191) DEFAULT NULL COMMENT 'Aims派发可靠operation key',
    aims_delivery_generation BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '已应用Aims结果事件代次',
    aims_delivery_status    VARCHAR(30) DEFAULT NULL COMMENT '已应用Aims结果状态',
    codocs_document_uuid    VARCHAR(100) DEFAULT NULL COMMENT '运维知识文档UUID',
    ops_knowledge_pending_uuid VARCHAR(100) DEFAULT NULL COMMENT '运维知识编排预留UUID；完成前阻止换绑',
    ops_knowledge_status    VARCHAR(20) NOT NULL DEFAULT 'idle' COMMENT '运维知识编排状态：idle/pending/linked',
    ops_knowledge_idempotency_key VARCHAR(191) DEFAULT NULL COMMENT '运维知识编排幂等键',
    source_app              VARCHAR(50) DEFAULT NULL COMMENT '来源应用',
    source_biz_type         VARCHAR(50) DEFAULT NULL COMMENT '来源业务类型',
    source_biz_id           VARCHAR(100) DEFAULT NULL COMMENT '来源业务ID',
    created_by              VARCHAR(50) DEFAULT NULL COMMENT '创建人',
    updated_by              VARCHAR(50) DEFAULT NULL COMMENT '更新人',
    created_at              DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at              DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at              DATETIME DEFAULT NULL COMMENT '软删除时间',

    UNIQUE KEY uk_code (code),
    INDEX idx_customer_id (customer_id),
    INDEX idx_maintenance_contract_id (maintenance_contract_id),
    INDEX idx_contract_id (contract_id),
    INDEX idx_service_agreement_id (service_agreement_id),
    INDEX idx_service_agreement_code (service_agreement_code),
    INDEX idx_delivery_code (delivery_code),
    INDEX idx_delivery_asset_code (delivery_asset_code),
    INDEX idx_project_code (project_code),
    INDEX idx_status (status),
    INDEX idx_sla_status (sla_status),
    INDEX idx_entitlement_status (entitlement_status),
    INDEX idx_ops_knowledge_pending (ops_knowledge_pending_uuid, ops_knowledge_status),
    INDEX idx_priority (priority),
    INDEX idx_aims_work_item_key (aims_work_item_key),
    INDEX idx_aims_dispatch (aims_dispatch_status, aims_dispatch_operation_key),
    INDEX idx_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='服务工单表';
