-- APF-16d incremental candidate; only renewal records; no automatic opportunity/coverage writes.
CREATE TABLE altoc_renewal_opportunity (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 code VARCHAR(30) NOT NULL,
 customer_id BIGINT NOT NULL,
 contract_id BIGINT DEFAULT NULL,
 name VARCHAR(200) NOT NULL,
 renewal_type VARCHAR(30) NOT NULL DEFAULT 'maintenance',
 expected_amount DECIMAL(18,2) DEFAULT NULL,
 expected_sign_date DATE DEFAULT NULL,
 stage VARCHAR(30) NOT NULL DEFAULT 'identified',
 status VARCHAR(30) NOT NULL DEFAULT 'open',
 owner_uid VARCHAR(50) NOT NULL,
 owner_dept_code VARCHAR(50) DEFAULT NULL,
 risk_level VARCHAR(20) DEFAULT NULL,
 reason VARCHAR(500) DEFAULT NULL,
 next_action VARCHAR(500) DEFAULT NULL,
 next_action_due_date DATE DEFAULT NULL,
 row_version INT UNSIGNED NOT NULL DEFAULT 1,
 created_by VARCHAR(50) NOT NULL,
 updated_by VARCHAR(50) NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 deleted_at DATETIME DEFAULT NULL,
 UNIQUE KEY uk_code(code),
 INDEX idx_customer(customer_id),
 INDEX idx_contract(contract_id),
 INDEX idx_owner(owner_uid),
 INDEX idx_dept(owner_dept_code),
 INDEX idx_status(status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
