-- APF M1 candidate canonical; no history import, no compatibility views.
CREATE TABLE altoc_attachment (
    id              BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    entity_type     VARCHAR(30)  NOT NULL,
    entity_id       BIGINT UNSIGNED NOT NULL,
    attachment_type VARCHAR(30)  NOT NULL DEFAULT 'general' COMMENT 'general/contract_text/contract_scan/source_evidence/...',
    file_name       VARCHAR(200) NOT NULL,
    file_key        VARCHAR(500) NOT NULL COMMENT 'OSS object key（经 Foundation 文件 adapter，integrationCode 决定桶）',
    file_size       BIGINT UNSIGNED DEFAULT NULL,
    content_type    VARCHAR(100) DEFAULT NULL,
    file_sha256     CHAR(64) DEFAULT NULL,
    uploaded_by     VARCHAR(64) NOT NULL,
    created_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at      DATETIME(3) DEFAULT NULL,
    KEY idx_altoc_attachment_entity (entity_type, entity_id),
    KEY idx_altoc_attachment_uploaded_by (uploaded_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='业务附件引用';

CREATE TABLE altoc_audit_log (
    id              BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    entity_type     VARCHAR(30)  NOT NULL,
    entity_id       BIGINT UNSIGNED NOT NULL,
    entity_code     VARCHAR(64)  DEFAULT NULL,
    action          VARCHAR(64)  NOT NULL,
    old_value       JSON DEFAULT NULL,
    new_value       JSON DEFAULT NULL,
    operator_uid    VARCHAR(64)  NOT NULL,
    operator_ip     VARCHAR(64)  DEFAULT NULL,
    channel         VARCHAR(30)  NOT NULL DEFAULT 'user' COMMENT 'user/system/purpose/in_process',
    request_id      VARCHAR(100) DEFAULT NULL,
    created_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    KEY idx_altoc_audit_entity (entity_type, entity_id),
    KEY idx_altoc_audit_code (entity_type, entity_code),
    KEY idx_altoc_audit_operator (operator_uid, created_at),
    KEY idx_altoc_audit_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Altoc 审计日志';

CREATE TABLE altoc_catalog_item (
    id                  BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    code                VARCHAR(64)  NOT NULL COMMENT '商业目录项编码',
    name                VARCHAR(200) NOT NULL,
    item_type           VARCHAR(30)  DEFAULT NULL COMMENT 'software/service/implementation/maintenance/hardware',
    parent_item_id      BIGINT UNSIGNED DEFAULT NULL,
    product_code        VARCHAR(64)  DEFAULT NULL COMMENT 'Assets 产品主档 product_code；自有产品填写，第三方/服务为空',
    product_origin      VARCHAR(30)  NOT NULL DEFAULT 'own' COMMENT 'own/third_party',
    specification       VARCHAR(500) DEFAULT NULL,
    unit                VARCHAR(20)  DEFAULT NULL,
    standard_price      DECIMAL(18,2) DEFAULT NULL,
    cost_price          DECIMAL(18,2) DEFAULT NULL,
    tax_rate            DECIMAL(5,2)  NOT NULL DEFAULT 6.00,
    status              VARCHAR(20)  NOT NULL DEFAULT 'active',
    remark              VARCHAR(500) DEFAULT NULL,
    row_version         INT UNSIGNED NOT NULL DEFAULT 1,
    created_by          VARCHAR(64) DEFAULT NULL,
    updated_by          VARCHAR(64) DEFAULT NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at          DATETIME(3) DEFAULT NULL,
    UNIQUE KEY uk_altoc_catalog_item_code (code),
    KEY idx_altoc_catalog_item_parent (parent_item_id),
    KEY idx_altoc_catalog_item_product (product_code),
    KEY idx_altoc_catalog_item_type (item_type, status),
    CONSTRAINT fk_altoc_catalog_item_parent FOREIGN KEY (parent_item_id) REFERENCES altoc_catalog_item(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='报价/合同商业目录项（原 product 表；产品主档归 Assets，这里只保存商务口径）';

CREATE TABLE altoc_contract_business_template (
    id              BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    code            VARCHAR(64) NOT NULL,
    name            VARCHAR(120) NOT NULL,
    direction       VARCHAR(20) NOT NULL DEFAULT 'sales' COMMENT 'sales/purchase',
    primary_type    VARCHAR(50) NOT NULL,
    is_system       TINYINT(1) NOT NULL DEFAULT 1,
    status          VARCHAR(20) NOT NULL DEFAULT 'active',
    version_no      INT NOT NULL DEFAULT 1,
    template_json   JSON NOT NULL COMMENT '合同行默认策略、义务模板、结算模板快照',
    row_version     INT UNSIGNED NOT NULL DEFAULT 1,
    created_by      VARCHAR(64) DEFAULT NULL,
    updated_by      VARCHAR(64) DEFAULT NULL,
    created_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at      DATETIME(3) DEFAULT NULL,
    UNIQUE KEY uk_altoc_contract_business_template_code (code),
    KEY idx_altoc_contract_template_direction (direction, primary_type, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='合同业务模板';

CREATE TABLE altoc_customer_level (
    id          BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    code        VARCHAR(50) NOT NULL,
    name        VARCHAR(100) NOT NULL,
    sort_no     INT NOT NULL DEFAULT 0,
    is_enabled  TINYINT(1) NOT NULL DEFAULT 1,
    created_at  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_altoc_customer_level_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客户等级字典';

CREATE TABLE altoc_customer_type (
    id          BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    code        VARCHAR(50) NOT NULL,
    name        VARCHAR(100) NOT NULL,
    sort_no     INT NOT NULL DEFAULT 0,
    is_enabled  TINYINT(1) NOT NULL DEFAULT 1,
    created_at  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_altoc_customer_type_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客户类型字典';

CREATE TABLE altoc_document_link (
    id                  BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    entity_type         VARCHAR(30)  NOT NULL COMMENT 'customer/lead/opportunity/quotation/contract/tender/service_ticket',
    entity_id           BIGINT UNSIGNED NOT NULL,
    document_uuid       CHAR(36) DEFAULT NULL COMMENT 'Codocs 文档 uuid；外部链接为空',
    external_url        VARCHAR(1000) DEFAULT NULL,
    external_mime_type  VARCHAR(100) DEFAULT NULL,
    document_title      VARCHAR(255) DEFAULT NULL,
    link_type           VARCHAR(30)  NOT NULL DEFAULT 'general' COMMENT 'proposal/contract_text/meeting_memo/tender_doc/evidence/general',
    source_type         VARCHAR(30)  NOT NULL DEFAULT 'codocs' COMMENT 'codocs/external_url',
    created_by          VARCHAR(64) DEFAULT NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at          DATETIME(3) DEFAULT NULL,
    UNIQUE KEY uk_altoc_document_link_entity_doc (entity_type, entity_id, document_uuid),
    KEY idx_altoc_document_link_entity (entity_type, entity_id),
    KEY idx_altoc_document_link_uuid (document_uuid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='业务对象—Codocs 文档关联（内容与 ACL 归 Codocs）';

CREATE TABLE altoc_integration_operation (
    operation_id                CHAR(36) PRIMARY KEY COMMENT '全局稳定操作UUID；创建后不可修改',
    operation_key               VARCHAR(191) NOT NULL COMMENT '调用方稳定业务操作键；创建后不可修改',
    correlation_key             VARCHAR(191) NOT NULL COMMENT '多目标命令链业务关联键；单命令可等于operation_key',
    sequence_no                 INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '同一命令链内序号；创建后不可修改',
    depends_on_operation_key    VARCHAR(191) DEFAULT NULL COMMENT '前置业务操作键；仅依赖成功后可派发',
    tenant_code                 VARCHAR(100) NOT NULL COMMENT '经认证上下文确认的租户；创建后不可修改',
    deployment_code             VARCHAR(100) NOT NULL COMMENT '经认证上下文确认的部署；创建后不可修改',
    source_app                  VARCHAR(50) NOT NULL COMMENT '调用方应用；创建后不可修改且不得等于target_app',
    target_app                  VARCHAR(50) NOT NULL COMMENT '单一目标应用；创建后不可修改且不得等于source_app',
    operation_code              VARCHAR(191) NOT NULL COMMENT '版本化dispatcher代码映射键；创建后不可修改',
    required_capability         VARCHAR(191) NOT NULL COMMENT '创建时所需capability审计快照；不得作为dispatcher可执行来源',
    source_biz_type             VARCHAR(100) NOT NULL COMMENT '调用方稳定业务对象类型；创建后不可修改',
    source_biz_code             VARCHAR(191) NOT NULL COMMENT '调用方稳定业务对象编码；创建后不可修改',
    target_receipt_id           CHAR(36) DEFAULT NULL COMMENT '目标端原子回执 UUID；source success 确认后写入',
    target_biz_type             VARCHAR(100) DEFAULT NULL COMMENT '目标业务对象类型；成功确认后写入',
    target_biz_code             VARCHAR(191) DEFAULT NULL COMMENT '目标稳定业务对象编码；成功确认后写入',
    idempotency_key             VARCHAR(191) NOT NULL COMMENT '发送给目标服务的稳定幂等键；创建后不可修改',
    command_schema_version      VARCHAR(30) NOT NULL DEFAULT 'v1' COMMENT '冻结命令schema版本；创建后不可修改',
    command_json                JSON NOT NULL COMMENT '冻结命令载荷；不得包含Token、凭证、内部URL或动态路由字段',
    command_sha256              CHAR(64) NOT NULL COMMENT '规范化命令载荷SHA-256；创建后不可修改',
    status                      VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '状态：pending/processing/retry_wait/partial_unknown/succeeded/failed_permanent/dead_letter/cancelled',
    attempt_count               INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '已开始尝试次数',
    max_attempts                INT UNSIGNED NOT NULL DEFAULT 8 COMMENT '最大自动尝试次数',
    next_attempt_at             DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '下次可领取时间',
    last_attempt_at             DATETIME(3) DEFAULT NULL COMMENT '最近尝试开始时间',
    locked_by                   VARCHAR(100) DEFAULT NULL COMMENT '当前持有租约的worker标识',
    locked_until                DATETIME(3) DEFAULT NULL COMMENT '当前租约截止时间',
    fencing_token               BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '每次领取递增的栅栏令牌，拒绝陈旧worker写回',
    version_no                  BIGINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '乐观锁版本；每次状态写入递增',
    original_request_id         VARCHAR(100) DEFAULT NULL COMMENT '原始调用请求ID',
    correlation_id              VARCHAR(100) DEFAULT NULL COMMENT '跨服务技术追踪关联ID',
    original_actor_uid          VARCHAR(100) DEFAULT NULL COMMENT '经验证的原始用户actor UID',
    service_client_id           VARCHAR(100) DEFAULT NULL COMMENT '经验证的调用服务client ID',
    replay_count                INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '管理员人工重放次数',
    last_replay_actor_uid       VARCHAR(100) DEFAULT NULL COMMENT '最近人工重放管理员UID',
    last_replay_reason          VARCHAR(500) DEFAULT NULL COMMENT '最近人工重放原因；不得包含敏感信息',
    last_replay_at              DATETIME(3) DEFAULT NULL COMMENT '最近人工重放时间',
    last_http_status            SMALLINT UNSIGNED DEFAULT NULL COMMENT '最近下游HTTP状态码',
    last_error_code             VARCHAR(100) DEFAULT NULL COMMENT '安全稳定错误码；不得保存内部地址或凭证',
    last_error_class            VARCHAR(50) DEFAULT NULL COMMENT '安全错误分类：authentication/authorization/transient/contract/conflict/protocol等',
    last_error_summary          VARCHAR(1000) DEFAULT NULL COMMENT '脱敏错误摘要；不得保存响应正文、Token、内部URL或堆栈',
    last_error_at               DATETIME(3) DEFAULT NULL COMMENT '最近错误时间',
    response_summary_sha256     CHAR(64) DEFAULT NULL COMMENT '脱敏响应摘要SHA-256；不保存完整响应',
    failure_notified_at         DATETIME(3) DEFAULT NULL COMMENT '达到失败阈值后的首次通知时间，用于一次性告警',
    failure_notification_id     VARCHAR(64) DEFAULT NULL COMMENT 'Console幂等通知ID；仅在发布成功后写入',
    succeeded_at                DATETIME(3) DEFAULT NULL COMMENT '目标效果确认成功时间',
    failed_permanent_at         DATETIME(3) DEFAULT NULL COMMENT '进入failed_permanent时间',
    dead_lettered_at            DATETIME(3) DEFAULT NULL COMMENT '进入dead_letter时间',
    cancelled_at                DATETIME(3) DEFAULT NULL COMMENT '受控取消时间',
    created_by                  VARCHAR(100) DEFAULT NULL COMMENT '创建者UID或服务client ID',
    updated_by                  VARCHAR(100) DEFAULT NULL COMMENT '最近更新者UID或worker标识',
    created_at                  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_at                  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',

    UNIQUE KEY uk_iop_identity (tenant_code, deployment_code, source_app, target_app, operation_code, idempotency_key),
    UNIQUE KEY uk_iop_operation_key (tenant_code, deployment_code, source_app, operation_key),
    UNIQUE KEY uk_iop_chain_sequence (tenant_code, deployment_code, source_app, correlation_key, sequence_no),
    INDEX idx_iop_due (status, next_attempt_at, locked_until),
    INDEX idx_iop_lock (status, locked_until),
    INDEX idx_iop_source_biz (tenant_code, deployment_code, source_app, source_biz_type, source_biz_code),
    INDEX idx_iop_target_biz (tenant_code, deployment_code, target_app, target_biz_type, target_biz_code),
    INDEX idx_iop_dependency (tenant_code, deployment_code, source_app, depends_on_operation_key),
    INDEX idx_iop_request (tenant_code, deployment_code, original_request_id),
    INDEX idx_iop_correlation_id (tenant_code, deployment_code, correlation_id),
    INDEX idx_iop_correlation_key (tenant_code, deployment_code, source_app, correlation_key, sequence_no),
    INDEX idx_iop_failure_notification (tenant_code, deployment_code, source_app, status, failure_notified_at, dead_lettered_at, operation_id),
    CONSTRAINT altoc_chk_iop_cross_app CHECK (source_app <> target_app),
    CONSTRAINT altoc_chk_iop_status CHECK (status IN ('pending', 'processing', 'retry_wait', 'partial_unknown', 'succeeded', 'failed_permanent', 'dead_letter', 'cancelled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='调用方跨应用单目标命令Outbox；身份和命令字段创建后不可修改';

CREATE TABLE altoc_integration_operation_attempt (
    attempt_id                 CHAR(36) PRIMARY KEY COMMENT '全局稳定尝试UUID',
    operation_id               CHAR(36) NOT NULL COMMENT '所属integration operation UUID',
    operation_code             VARCHAR(191) NOT NULL COMMENT '版本化dispatcher代码映射键审计快照',
    attempt_no                 INT UNSIGNED NOT NULL COMMENT '操作内递增尝试序号',
    trigger_type               VARCHAR(32) NOT NULL COMMENT '触发方式：immediate/scheduled/manual_replay/lease_recovery',
    request_id                 VARCHAR(100) DEFAULT NULL COMMENT '本次派发请求ID',
    correlation_id             VARCHAR(100) DEFAULT NULL COMMENT '本次跨服务技术追踪关联ID',
    locked_by                  VARCHAR(100) DEFAULT NULL COMMENT '本次执行worker标识快照',
    fencing_token              BIGINT UNSIGNED NOT NULL COMMENT '本次执行栅栏令牌',
    result_status              VARCHAR(32) NOT NULL DEFAULT 'processing' COMMENT '尝试状态：processing；完成后一次性收口为succeeded/retry_wait/partial_unknown/failed_permanent/dead_letter/cancelled',
    http_status                SMALLINT UNSIGNED DEFAULT NULL COMMENT '下游HTTP状态码',
    error_code                 VARCHAR(100) DEFAULT NULL COMMENT '安全稳定错误码',
    error_class                VARCHAR(50) DEFAULT NULL COMMENT '安全错误分类',
    error_summary              VARCHAR(1000) DEFAULT NULL COMMENT '脱敏错误摘要；不得保存响应正文、Token、内部URL或堆栈',
    target_biz_type            VARCHAR(100) DEFAULT NULL COMMENT '本次确认的目标业务对象类型',
    target_biz_code            VARCHAR(191) DEFAULT NULL COMMENT '本次确认的目标稳定业务对象编码',
    response_summary_sha256    CHAR(64) DEFAULT NULL COMMENT '脱敏响应摘要SHA-256；不保存完整响应',
    started_at                 DATETIME(3) NOT NULL COMMENT '尝试开始时间',
    finished_at                DATETIME(3) DEFAULT NULL COMMENT '尝试结束时间',
    duration_ms                BIGINT UNSIGNED DEFAULT NULL COMMENT '尝试耗时毫秒',
    created_at                 DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '追加时间；身份字段禁止修改，processing仅允许一次性写入完成结果',

    UNIQUE KEY uk_ioa_operation_attempt (operation_id, attempt_no),
    INDEX idx_ioa_operation_created (operation_id, created_at),
    INDEX idx_ioa_operation_code (operation_code, created_at),
    INDEX idx_ioa_request (request_id),
    INDEX idx_ioa_correlation (correlation_id, created_at),
    INDEX idx_ioa_result (result_status, created_at),
    INDEX idx_ioa_error (error_class, error_code, created_at),
    CONSTRAINT altoc_fk_ioa_operation FOREIGN KEY (operation_id) REFERENCES `altoc_integration_operation`(operation_id) ON DELETE RESTRICT,
    CONSTRAINT altoc_chk_ioa_result_status CHECK (result_status IN ('processing', 'succeeded', 'retry_wait', 'partial_unknown', 'failed_permanent', 'dead_letter', 'cancelled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='跨应用命令执行尝试安全审计日志；身份行追加，processing只允许一次性收口且不保存命令/响应正文或凭证';

CREATE TABLE altoc_integration_operation_dead_letter_actionable (
  operation_id CHAR(36) NOT NULL COMMENT '来源integration operation UUID',
  generation_no BIGINT UNSIGNED NOT NULL COMMENT '以进入dead_letter时operation version作为单调generation',
  tenant_code VARCHAR(100) NOT NULL,
  deployment_code VARCHAR(100) NOT NULL,
  source_app VARCHAR(64) NOT NULL,
  target_app VARCHAR(64) NOT NULL,
  operation_code VARCHAR(191) NOT NULL,
  source_biz_type VARCHAR(64) NOT NULL,
  source_biz_code VARCHAR(191) NOT NULL,
  attempt_count INT UNSIGNED NOT NULL,
  max_attempts INT UNSIGNED NOT NULL,
  last_error_code VARCHAR(100) DEFAULT NULL COMMENT '安全稳定错误码；不保存raw error',
  last_error_class VARCHAR(50) DEFAULT NULL,
  dead_lettered_at DATETIME(3) NOT NULL,
  original_actor_uid VARCHAR(100) DEFAULT NULL,
  source_operation_version BIGINT UNSIGNED NOT NULL,
  actionable_key VARCHAR(191) NOT NULL,
  publish_object_version VARCHAR(191) NOT NULL,
  notification_id VARCHAR(64) DEFAULT NULL,
  recipient_uids JSON DEFAULT NULL COMMENT 'Console实际返回的规范化显式收件UID数组',
  publish_acked_at DATETIME(3) DEFAULT NULL,
  closure_state VARCHAR(16) DEFAULT NULL COMMENT 'resolved/cancelled',
  closure_object_version VARCHAR(191) DEFAULT NULL,
  closure_pending_at DATETIME(3) DEFAULT NULL,
  closure_acked_at DATETIME(3) DEFAULT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (operation_id, generation_no),
  UNIQUE KEY uk_iopdla_actionable (tenant_code, deployment_code, source_app, actionable_key),
  UNIQUE KEY uk_iopdla_notification (tenant_code, deployment_code, source_app, notification_id),
  INDEX idx_iopdla_publish (tenant_code, deployment_code, source_app, publish_acked_at, dead_lettered_at),
  INDEX idx_iopdla_closure (tenant_code, deployment_code, source_app, closure_acked_at, closure_pending_at),
  CONSTRAINT altoc_fk_iopdla_operation FOREIGN KEY (operation_id) REFERENCES `altoc_integration_operation`(operation_id) ON DELETE RESTRICT,
  CONSTRAINT altoc_chk_iopdla_closure CHECK (closure_state IS NULL OR closure_state IN ('resolved','cancelled')),
  CONSTRAINT altoc_chk_iopdla_recipient CHECK (recipient_uids IS NULL OR JSON_TYPE(recipient_uids) = 'ARRAY')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='跨应用死信actionable generation发布与closure证据';

CREATE TABLE altoc_payment_term_template (
    id              BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    code            VARCHAR(50) NOT NULL,
    name            VARCHAR(100) NOT NULL,
    template_json   JSON NOT NULL COMMENT '条款模板：[{term_type,ratio|amount,trigger_type,recurrence,...}]',
    is_enabled      TINYINT(1) NOT NULL DEFAULT 1,
    row_version     INT UNSIGNED NOT NULL DEFAULT 1,
    created_by      VARCHAR(64) DEFAULT NULL,
    updated_by      VARCHAR(64) DEFAULT NULL,
    created_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_altoc_payment_term_template_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='付款条款模板';

CREATE TABLE altoc_service_command_receipt (
    receipt_id                 CHAR(36) PRIMARY KEY COMMENT '全局稳定目标回执UUID',
    operation_id               CHAR(36) NOT NULL COMMENT '调用方integration operation UUID；创建后不可修改',
    operation_code             VARCHAR(191) NOT NULL COMMENT '版本化目标命令代码；创建后不可修改',
    tenant_code                VARCHAR(100) NOT NULL COMMENT '目标端验证后的租户；创建后不可修改',
    source_deployment_code     VARCHAR(100) NOT NULL COMMENT '目标 BFF 验证后的调用方部署；创建后不可修改',
    deployment_code            VARCHAR(100) NOT NULL COMMENT '目标 Runtime token 验证后的目标部署；创建后不可修改',
    source_app                 VARCHAR(50) NOT NULL COMMENT '目标端验证后的调用方；创建后不可修改且不得等于target_app',
    target_app                 VARCHAR(50) NOT NULL COMMENT '当前目标应用；创建后不可修改且不得等于source_app',
    required_capability        VARCHAR(191) NOT NULL COMMENT '目标接口所需capability审计快照；不得用于动态选择授权',
    idempotency_key            VARCHAR(191) NOT NULL COMMENT '目标端稳定幂等键；创建后不可修改',
    identity_sha256            BINARY(32) GENERATED ALWAYS AS (UNHEX(SHA2(CONCAT_WS('|', tenant_code, source_deployment_code, deployment_code, source_app, target_app, operation_code, idempotency_key), 256))) STORED COMMENT '目标幂等身份生成摘要；用于受索引宽度限制的唯一约束',
    command_schema_version     VARCHAR(30) NOT NULL DEFAULT 'v1' COMMENT '目标端接收的冻结命令schema版本',
    command_sha256             CHAR(64) NOT NULL COMMENT '规范化命令载荷SHA-256；同键异hash必须409',
    status                     VARCHAR(32) NOT NULL DEFAULT 'processing' COMMENT '状态：processing/succeeded/rejected',
    locked_by                  VARCHAR(100) DEFAULT NULL COMMENT '当前处理worker标识',
    locked_until               DATETIME(3) DEFAULT NULL COMMENT '目标端处理租约截止时间',
    fencing_token              BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '目标端接管处理时递增的栅栏令牌',
    version_no                 BIGINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '乐观锁版本；每次状态写入递增',
    first_request_id           VARCHAR(100) DEFAULT NULL COMMENT '首次接收请求ID',
    last_request_id            VARCHAR(100) DEFAULT NULL COMMENT '最近同幂等键请求ID',
    correlation_id             VARCHAR(100) DEFAULT NULL COMMENT '跨服务技术追踪关联ID',
    original_actor_uid         VARCHAR(100) DEFAULT NULL COMMENT '目标端验证后的委托用户actor UID',
    service_client_id          VARCHAR(100) DEFAULT NULL COMMENT '目标端验证后的调用服务client ID',
    target_biz_type            VARCHAR(100) DEFAULT NULL COMMENT '目标业务对象类型',
    target_biz_code            VARCHAR(191) DEFAULT NULL COMMENT '目标稳定业务对象编码；同键成功重放时返回',
    response_http_status       SMALLINT UNSIGNED DEFAULT NULL COMMENT '首次终态HTTP状态码',
    response_summary_sha256    CHAR(64) DEFAULT NULL COMMENT '脱敏响应摘要SHA-256；不保存完整响应',
    last_error_code            VARCHAR(100) DEFAULT NULL COMMENT '安全稳定错误码',
    last_error_class           VARCHAR(50) DEFAULT NULL COMMENT '安全错误分类',
    last_error_summary         VARCHAR(1000) DEFAULT NULL COMMENT '脱敏错误摘要；不得保存响应正文、Token、内部URL或堆栈',
    received_at                DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '首次接收时间',
    last_received_at           DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '最近接收时间',
    completed_at               DATETIME(3) DEFAULT NULL COMMENT '处理完成时间',
    created_at                 DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_at                 DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',

    UNIQUE KEY uk_scr_identity (identity_sha256),
    UNIQUE KEY uk_scr_operation_id (operation_id),
    INDEX idx_scr_status_lock (status, locked_until),
    INDEX idx_scr_target_biz (tenant_code, deployment_code, target_app, target_biz_type, target_biz_code),
    INDEX idx_scr_first_request (tenant_code, deployment_code, first_request_id),
    INDEX idx_scr_last_request (tenant_code, deployment_code, last_request_id),
    INDEX idx_scr_correlation (tenant_code, deployment_code, correlation_id),
    INDEX idx_scr_received (received_at),
    CONSTRAINT altoc_chk_scr_cross_app CHECK (source_app <> target_app),
    CONSTRAINT altoc_chk_scr_status CHECK (status IN ('processing', 'succeeded', 'rejected'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='目标服务命令Inbox回执；同幂等键同摘要重放、不同摘要冲突';

CREATE TABLE altoc_customer (
    id                          BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    code                        VARCHAR(64)  NOT NULL COMMENT '客户编号 CU-xxxxxx；跨域稳定键',
    name                        VARCHAR(200) NOT NULL,
    normalized_name             VARCHAR(200) DEFAULT NULL COMMENT '去重匹配用标准化名称',
    short_name                  VARCHAR(100) DEFAULT NULL,
    unified_social_credit_code  VARCHAR(50)  DEFAULT NULL,
    organization_domain         VARCHAR(200) DEFAULT NULL,
    customer_type_id            BIGINT UNSIGNED DEFAULT NULL,
    customer_level_id           BIGINT UNSIGNED DEFAULT NULL,
    industry_code               VARCHAR(64)  DEFAULT NULL COMMENT 'Console 字典 business-domain code',
    region_code                 VARCHAR(64)  DEFAULT NULL COMMENT 'Console 字典 region code',
    source_type                 VARCHAR(50)  DEFAULT NULL COMMENT 'marketing/referral/visit/tender/partner/other',
    status                      VARCHAR(20)  NOT NULL DEFAULT 'draft' COMMENT 'draft/approval_pending/approved/active/inactive/archived',
    owner_uid                   VARCHAR(64)  NOT NULL COMMENT '客户负责人 uid（对象关系授权依据）',
    owner_dept_code             VARCHAR(64)  DEFAULT NULL,
    parent_customer_id          BIGINT UNSIGNED DEFAULT NULL,
    is_partner                  TINYINT(1) NOT NULL DEFAULT 0,
    credit_level                VARCHAR(20)  DEFAULT NULL COMMENT 'A/B/C/D',
    website                     VARCHAR(300) DEFAULT NULL,
    telephone                   VARCHAR(30)  DEFAULT NULL,
    province                    VARCHAR(50)  DEFAULT NULL,
    city                        VARCHAR(50)  DEFAULT NULL,
    address                     VARCHAR(500) DEFAULT NULL,
    wechat_official_account     VARCHAR(100) DEFAULT NULL,
    description                 TEXT DEFAULT NULL,
    started_at                  DATE DEFAULT NULL COMMENT '合作起始日期（业务日期，非迁移字段）',
    last_follow_up_at           DATETIME(3) DEFAULT NULL,
    -- 外部主数据导入预留接口（见文档 §4.6）：只存来源与外部引用，不存源系统快照
    source_system               VARCHAR(32)  NOT NULL DEFAULT 'manual' COMMENT 'manual/import:<system>；导入接口写入',
    external_ref                VARCHAR(128) DEFAULT NULL COMMENT '外部系统客户标识；与 source_system 组成导入幂等键',
    external_synced_at          DATETIME(3)  DEFAULT NULL,
    approved_at                 DATETIME(3)  DEFAULT NULL,
    approved_by                 VARCHAR(64)  DEFAULT NULL,
    workflow_instance_id        VARCHAR(100) DEFAULT NULL,
    remark                      VARCHAR(500) DEFAULT NULL,
    row_version                 INT UNSIGNED NOT NULL DEFAULT 1,
    created_by                  VARCHAR(64) DEFAULT NULL,
    updated_by                  VARCHAR(64) DEFAULT NULL,
    created_at                  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at                  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at                  DATETIME(3) DEFAULT NULL,
    UNIQUE KEY uk_altoc_customer_code (code),
    UNIQUE KEY uk_altoc_customer_external (source_system, external_ref),
    KEY idx_altoc_customer_name (name),
    KEY idx_altoc_customer_normalized_name (normalized_name),
    KEY idx_altoc_customer_uscc (unified_social_credit_code),
    KEY idx_altoc_customer_domain (organization_domain),
    KEY idx_altoc_customer_owner (owner_uid, status),
    KEY idx_altoc_customer_dept (owner_dept_code, status),
    KEY idx_altoc_customer_status (status, deleted_at),
    KEY idx_altoc_customer_parent (parent_customer_id),
    KEY idx_altoc_customer_industry (industry_code),
    KEY idx_altoc_customer_region (region_code),
    CONSTRAINT fk_altoc_customer_type FOREIGN KEY (customer_type_id) REFERENCES altoc_customer_type(id),
    CONSTRAINT fk_altoc_customer_level FOREIGN KEY (customer_level_id) REFERENCES altoc_customer_level(id),
    CONSTRAINT fk_altoc_customer_parent FOREIGN KEY (parent_customer_id) REFERENCES altoc_customer(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客户主数据';

CREATE TABLE altoc_customer_invoice_profile (
    id                  BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    code                VARCHAR(64)  NOT NULL COMMENT '开票资料编号 CIP-xxxxxx；Finance 开票申请冻结引用',
    customer_id         BIGINT UNSIGNED NOT NULL,
    taxpayer_name       VARCHAR(200) NOT NULL COMMENT '发票抬头/购方名称',
    taxpayer_no         VARCHAR(50)  DEFAULT NULL,
    registered_address  VARCHAR(500) DEFAULT NULL,
    registered_phone    VARCHAR(50)  DEFAULT NULL,
    bank_name           VARCHAR(200) DEFAULT NULL,
    bank_account        VARCHAR(100) DEFAULT NULL,
    invoice_type        VARCHAR(30)  NOT NULL DEFAULT 'special_vat' COMMENT 'special_vat/general_vat/electronic',
    invoice_email       VARCHAR(100) DEFAULT NULL,
    receiver_name       VARCHAR(100) DEFAULT NULL,
    receiver_phone      VARCHAR(50)  DEFAULT NULL,
    receiver_address    VARCHAR(500) DEFAULT NULL,
    is_default          TINYINT(1) NOT NULL DEFAULT 1,
    status              VARCHAR(20)  NOT NULL DEFAULT 'active' COMMENT 'active/inactive',
    remark              VARCHAR(500) DEFAULT NULL,
    row_version         INT UNSIGNED NOT NULL DEFAULT 1,
    created_by          VARCHAR(64) DEFAULT NULL,
    updated_by          VARCHAR(64) DEFAULT NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at          DATETIME(3) DEFAULT NULL,
    -- 每客户至多一条有效默认资料；允许多条非默认资料（历史抬头、分支机构）
    default_slot        TINYINT GENERATED ALWAYS AS (CASE WHEN is_default = 1 AND status = 'active' AND deleted_at IS NULL THEN 1 ELSE NULL END) STORED,
    UNIQUE KEY uk_altoc_customer_invoice_profile_code (code),
    UNIQUE KEY uk_altoc_customer_invoice_profile_default (customer_id, default_slot),
    KEY idx_altoc_customer_invoice_profile_customer (customer_id, status),
    KEY idx_altoc_customer_invoice_profile_taxpayer (taxpayer_no),
    CONSTRAINT fk_altoc_customer_invoice_profile_customer FOREIGN KEY (customer_id) REFERENCES altoc_customer(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客户开票资料（原 customer_invoice_info；一客户一默认）';

CREATE TABLE altoc_quotation (
    id                      BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    code                    VARCHAR(64)  NOT NULL COMMENT 'QU-xxxxxx',
    quotation_no            VARCHAR(50)  DEFAULT NULL COMMENT '对外报价单号',
    customer_id             BIGINT UNSIGNED NOT NULL,
    opportunity_id          BIGINT UNSIGNED DEFAULT NULL COMMENT 'altoc_opportunity.id（B2 表，域内 FK 在 B2 安装时补）',
    version_no              INT NOT NULL DEFAULT 1,
    status                  VARCHAR(20)  NOT NULL DEFAULT 'draft' COMMENT 'draft/pending_approval/approved/rejected/sent/accepted/expired/voided',
    valid_until             DATE DEFAULT NULL,
    discount_rate           DECIMAL(5,2) DEFAULT NULL,
    gross_margin_rate       DECIMAL(5,2) DEFAULT NULL,
    amount_tax_inclusive    DECIMAL(18,2) DEFAULT NULL,
    amount_tax_exclusive    DECIMAL(18,2) DEFAULT NULL,
    currency_code           CHAR(3) NOT NULL DEFAULT 'CNY',
    tax_rate                DECIMAL(5,2) NOT NULL DEFAULT 6.00,
    owner_uid               VARCHAR(64)  NOT NULL,
    owner_dept_code         VARCHAR(64)  DEFAULT NULL,
    workflow_instance_id    VARCHAR(100) DEFAULT NULL,
    approved_at             DATETIME(3) DEFAULT NULL,
    approved_by             VARCHAR(64) DEFAULT NULL,
    rejected_at             DATETIME(3) DEFAULT NULL,
    rejected_by             VARCHAR(64) DEFAULT NULL,
    reject_reason           VARCHAR(500) DEFAULT NULL,
    sent_at                 DATETIME(3) DEFAULT NULL,
    accepted_at             DATETIME(3) DEFAULT NULL,
    expired_at              DATETIME(3) DEFAULT NULL,
    last_status_changed_at  DATETIME(3) DEFAULT NULL,
    last_status_changed_by  VARCHAR(64) DEFAULT NULL,
    remark                  VARCHAR(500) DEFAULT NULL,
    row_version             INT UNSIGNED NOT NULL DEFAULT 1,
    created_by              VARCHAR(64) DEFAULT NULL,
    updated_by              VARCHAR(64) DEFAULT NULL,
    created_at              DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at              DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at              DATETIME(3) DEFAULT NULL,
    UNIQUE KEY uk_altoc_quotation_code (code),
    KEY idx_altoc_quotation_customer (customer_id, status),
    KEY idx_altoc_quotation_opportunity (opportunity_id),
    KEY idx_altoc_quotation_owner (owner_uid, status),
    KEY idx_altoc_quotation_valid_until (valid_until),
    CONSTRAINT fk_altoc_quotation_customer FOREIGN KEY (customer_id) REFERENCES altoc_customer(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='报价单';

CREATE TABLE altoc_quotation_item (
    id                      BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    quotation_id            BIGINT UNSIGNED NOT NULL,
    line_no                 INT NOT NULL,
    catalog_item_id         BIGINT UNSIGNED DEFAULT NULL,
    item_name               VARCHAR(200) NOT NULL,
    specification           VARCHAR(500) DEFAULT NULL,
    unit                    VARCHAR(20)  DEFAULT NULL,
    quantity                DECIMAL(18,4) NOT NULL DEFAULT 1.0000,
    unit_price              DECIMAL(18,2) DEFAULT NULL,
    discount_rate           DECIMAL(5,2) DEFAULT NULL,
    cost_price              DECIMAL(18,2) DEFAULT NULL,
    tax_rate                DECIMAL(5,2) NOT NULL DEFAULT 6.00,
    amount_tax_inclusive    DECIMAL(18,2) DEFAULT NULL,
    amount_tax_exclusive    DECIMAL(18,2) DEFAULT NULL,
    sort_no                 INT NOT NULL DEFAULT 0,
    created_at              DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at              DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_altoc_quotation_item_line (quotation_id, line_no),
    KEY idx_altoc_quotation_item_catalog (catalog_item_id),
    CONSTRAINT fk_altoc_quotation_item_quotation FOREIGN KEY (quotation_id) REFERENCES altoc_quotation(id) ON DELETE CASCADE,
    CONSTRAINT fk_altoc_quotation_item_catalog FOREIGN KEY (catalog_item_id) REFERENCES altoc_catalog_item(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='报价明细';

CREATE TABLE altoc_quotation_version (
    id              BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    quotation_id    BIGINT UNSIGNED NOT NULL,
    version_no      INT NOT NULL,
    snapshot_json   JSON NOT NULL COMMENT '头 + 明细冻结快照（批准/发送时固化）',
    snapshot_sha256 CHAR(64) NOT NULL,
    created_by      VARCHAR(64) DEFAULT NULL,
    created_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_altoc_quotation_version (quotation_id, version_no),
    CONSTRAINT fk_altoc_quotation_version_quotation FOREIGN KEY (quotation_id) REFERENCES altoc_quotation(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='报价版本快照（不可变）';

CREATE TABLE altoc_contact (
    id                  BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    code                VARCHAR(64)  NOT NULL COMMENT '联系人编号 CN-xxxxxx',
    customer_id         BIGINT UNSIGNED NOT NULL,
    name                VARCHAR(50)  NOT NULL,
    gender              TINYINT NOT NULL DEFAULT 0 COMMENT '0未知 1男 2女',
    dept_name           VARCHAR(100) DEFAULT NULL,
    job_title           VARCHAR(100) DEFAULT NULL,
    mobile              VARCHAR(30)  DEFAULT NULL,
    normalized_mobile   VARCHAR(30)  DEFAULT NULL,
    alternate_mobile    VARCHAR(30)  DEFAULT NULL,
    phone               VARCHAR(30)  DEFAULT NULL,
    email               VARCHAR(100) DEFAULT NULL,
    normalized_email    VARCHAR(100) DEFAULT NULL,
    wechat              VARCHAR(100) DEFAULT NULL,
    mailing_address     VARCHAR(500) DEFAULT NULL,
    decision_role       VARCHAR(30)  DEFAULT NULL COMMENT 'decision_maker/purchaser/tech_influencer/user/other',
    influence_level     VARCHAR(20)  DEFAULT NULL COMMENT 'high/medium/low',
    is_key_contact      TINYINT(1) NOT NULL DEFAULT 0,
    status              VARCHAR(20)  NOT NULL DEFAULT 'active' COMMENT 'active/inactive',
    owner_uid           VARCHAR(64)  DEFAULT NULL,
    remark              VARCHAR(500) DEFAULT NULL,
    row_version         INT UNSIGNED NOT NULL DEFAULT 1,
    created_by          VARCHAR(64) DEFAULT NULL,
    updated_by          VARCHAR(64) DEFAULT NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at          DATETIME(3) DEFAULT NULL,
    UNIQUE KEY uk_altoc_contact_code (code),
    KEY idx_altoc_contact_customer (customer_id, status),
    KEY idx_altoc_contact_name (name),
    KEY idx_altoc_contact_mobile (normalized_mobile),
    KEY idx_altoc_contact_email (normalized_email),
    CONSTRAINT fk_altoc_contact_customer FOREIGN KEY (customer_id) REFERENCES altoc_customer(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客户联系人';

CREATE TABLE altoc_contract (
    id                      BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    code                    VARCHAR(64)  NOT NULL COMMENT 'CT-xxxxxx；跨域稳定键（Finance/Aims 引用）',
    contract_no             VARCHAR(50)  DEFAULT NULL COMMENT '对外合同号',
    name                    VARCHAR(200) NOT NULL,
    customer_id             BIGINT UNSIGNED NOT NULL,
    contact_id              BIGINT UNSIGNED DEFAULT NULL,
    parent_contract_id      BIGINT UNSIGNED DEFAULT NULL,
    is_master_contract      TINYINT(1) NOT NULL DEFAULT 0,
    opportunity_id          BIGINT UNSIGNED DEFAULT NULL,
    quotation_id            BIGINT UNSIGNED DEFAULT NULL,
    direction               VARCHAR(20)  NOT NULL DEFAULT 'sales' COMMENT 'sales/purchase',
    primary_type            VARCHAR(50)  NOT NULL DEFAULT 'standard' COMMENT '由合同行类型推导：software/implementation/service/maintenance/mixed/...',
    agreement_form          VARCHAR(50)  NOT NULL DEFAULT 'standard_contract',
    template_code           VARCHAR(64)  DEFAULT NULL,
    source_type             VARCHAR(50)  DEFAULT NULL COMMENT 'quotation/opportunity/manual',
    source_code             VARCHAR(100) DEFAULT NULL,
    -- 四条正交状态轴 + 兼容的 status（见文档 §2.3 与建议调整 A-07）
    status                  VARCHAR(20)  NOT NULL DEFAULT 'draft' COMMENT 'draft/pending_approval/approved/rejected/effective/completed/terminated/invalid',
    legal_status            VARCHAR(30)  NOT NULL DEFAULT 'draft' COMMENT 'draft/pending_approval/approved/effective/suspended/closed/terminated',
    fulfillment_status      VARCHAR(30)  NOT NULL DEFAULT 'not_started' COMMENT 'not_started/in_progress/fulfilled/blocked/cancelled',
    financial_status        VARCHAR(30)  NOT NULL DEFAULT 'unplanned' COMMENT 'unplanned/planned/invoicing/partially_received/received/bad_debt；由结算计划汇总维护',
    activation_status       VARCHAR(30)  NOT NULL DEFAULT 'not_planned' COMMENT 'not_planned/ready/activating/activated/completed/failed',
    sign_date               DATE DEFAULT NULL,
    effective_date          DATE DEFAULT NULL,
    end_date                DATE DEFAULT NULL,
    amount_tax_inclusive    DECIMAL(18,2) DEFAULT NULL COMMENT '合同行合计（由 recalculateContractLineTotalsTx 维护）',
    amount_tax_exclusive    DECIMAL(18,2) DEFAULT NULL,
    currency_code           CHAR(3) NOT NULL DEFAULT 'CNY',
    tax_rate                DECIMAL(5,2) NOT NULL DEFAULT 6.00,
    gross_margin_rate       DECIMAL(5,2) DEFAULT NULL,
    retention_rate          DECIMAL(5,2) DEFAULT NULL,
    payment_term_summary    VARCHAR(500) DEFAULT NULL,
    is_third_party          TINYINT(1) NOT NULL DEFAULT 0,
    third_party_customer_id BIGINT UNSIGNED DEFAULT NULL,
    service_period_months   INT DEFAULT NULL,
    contract_period_months  INT DEFAULT NULL,
    content_summary         VARCHAR(1000) DEFAULT NULL,
    service_terms           VARCHAR(1000) DEFAULT NULL,
    owner_uid               VARCHAR(64)  NOT NULL,
    owner_dept_code         VARCHAR(64)  DEFAULT NULL,
    workflow_instance_id    VARCHAR(100) DEFAULT NULL,
    approved_at             DATETIME(3) DEFAULT NULL,
    approved_by             VARCHAR(64) DEFAULT NULL,
    rejected_at             DATETIME(3) DEFAULT NULL,
    rejected_by             VARCHAR(64) DEFAULT NULL,
    reject_reason           VARCHAR(500) DEFAULT NULL,
    terminated_at           DATETIME(3) DEFAULT NULL,
    completed_at            DATETIME(3) DEFAULT NULL,
    last_status_changed_at  DATETIME(3) DEFAULT NULL,
    last_status_changed_by  VARCHAR(64) DEFAULT NULL,
    remark                  VARCHAR(500) DEFAULT NULL,
    version_no              INT NOT NULL DEFAULT 1 COMMENT '业务版本（签署内容变更时递增）',
    row_version             INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '乐观锁（原 lock_version）',
    created_by              VARCHAR(64) DEFAULT NULL,
    updated_by              VARCHAR(64) DEFAULT NULL,
    created_at              DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at              DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at              DATETIME(3) DEFAULT NULL,
    UNIQUE KEY uk_altoc_contract_code (code),
    KEY idx_altoc_contract_customer (customer_id, legal_status),
    KEY idx_altoc_contract_parent (parent_contract_id),
    KEY idx_altoc_contract_master (is_master_contract, customer_id, direction),
    KEY idx_altoc_contract_opportunity (opportunity_id),
    KEY idx_altoc_contract_quotation (quotation_id),
    KEY idx_altoc_contract_status (status, deleted_at),
    KEY idx_altoc_contract_legal_status (legal_status),
    KEY idx_altoc_contract_fulfillment (fulfillment_status),
    KEY idx_altoc_contract_financial (financial_status),
    KEY idx_altoc_contract_activation (activation_status),
    KEY idx_altoc_contract_owner (owner_uid, legal_status),
    KEY idx_altoc_contract_dept (owner_dept_code, legal_status),
    KEY idx_altoc_contract_effective (effective_date),
    KEY idx_altoc_contract_end (end_date),
    KEY idx_altoc_contract_source (source_type, source_code),
    CONSTRAINT fk_altoc_contract_customer FOREIGN KEY (customer_id) REFERENCES altoc_customer(id),
    CONSTRAINT fk_altoc_contract_contact FOREIGN KEY (contact_id) REFERENCES altoc_contact(id),
    CONSTRAINT fk_altoc_contract_parent FOREIGN KEY (parent_contract_id) REFERENCES altoc_contract(id),
    CONSTRAINT fk_altoc_contract_quotation FOREIGN KEY (quotation_id) REFERENCES altoc_quotation(id),
    CONSTRAINT fk_altoc_contract_third_party FOREIGN KEY (third_party_customer_id) REFERENCES altoc_customer(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='合同';

CREATE TABLE altoc_contract_line (
    id                          BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    code                        VARCHAR(64)  NOT NULL COMMENT 'CL-xxxxxx；Aims 项目行关系、Finance 成本归因引用',
    contract_id                 BIGINT UNSIGNED NOT NULL,
    line_no                     INT NOT NULL,
    line_type                   VARCHAR(50)  NOT NULL COMMENT 'software_license/implementation/customization/service/maintenance/hardware/training/other',
    name                        VARCHAR(200) NOT NULL,
    description                 TEXT DEFAULT NULL,
    catalog_item_id             BIGINT UNSIGNED DEFAULT NULL,
    catalog_item_code           VARCHAR(64)  DEFAULT NULL,
    product_code                VARCHAR(64)  DEFAULT NULL COMMENT 'Assets 产品主档编码（自有产品）',
    product_version             VARCHAR(100) DEFAULT NULL,
    product_origin              VARCHAR(30)  NOT NULL DEFAULT 'own' COMMENT 'own/third_party',
    supplier_code               VARCHAR(100) DEFAULT NULL,
    source_quotation_item_id    BIGINT UNSIGNED DEFAULT NULL,
    quantity                    DECIMAL(18,4) NOT NULL DEFAULT 1.0000,
    unit                        VARCHAR(30)  DEFAULT NULL,
    quantity_factors_json       JSON DEFAULT NULL,
    unit_price                  DECIMAL(18,2) DEFAULT NULL,
    amount_tax_exclusive        DECIMAL(18,2) DEFAULT NULL,
    amount_tax_inclusive        DECIMAL(18,2) DEFAULT NULL,
    tax_rate                    DECIMAL(5,2)  NOT NULL DEFAULT 6.00,
    planned_cost                DECIMAL(18,2) DEFAULT NULL,
    planned_margin              DECIMAL(18,2) DEFAULT NULL,
    currency_code               CHAR(3) NOT NULL DEFAULT 'CNY',
    billing_method              VARCHAR(30)  NOT NULL DEFAULT 'fixed_price' COMMENT 'fixed_price/time_and_material/recurring',
    fulfillment_method          VARCHAR(30)  NOT NULL DEFAULT 'point_in_time' COMMENT 'point_in_time/over_time',
    service_start_date          DATE DEFAULT NULL,
    service_end_date            DATE DEFAULT NULL,
    project_policy              VARCHAR(30)  NOT NULL DEFAULT 'none' COMMENT 'none/optional/required',
    project_template_code       VARCHAR(100) DEFAULT NULL,
    asset_policy                VARCHAR(50)  NOT NULL DEFAULT 'none' COMMENT 'none/planned_on_effective/...',
    service_policy              VARCHAR(50)  NOT NULL DEFAULT 'none',
    procurement_policy          VARCHAR(30)  NOT NULL DEFAULT 'none',
    acceptance_required         TINYINT(1) NOT NULL DEFAULT 0,
    acceptance_criteria         VARCHAR(1000) DEFAULT NULL,
    status                      VARCHAR(20)  NOT NULL DEFAULT 'active' COMMENT 'active/inactive/cancelled',
    sort_no                     INT NOT NULL DEFAULT 0,
    snapshot_json               JSON DEFAULT NULL COMMENT '创建来源快照（报价明细/模板）',
    row_version                 INT UNSIGNED NOT NULL DEFAULT 1,
    created_by                  VARCHAR(64) DEFAULT NULL,
    updated_by                  VARCHAR(64) DEFAULT NULL,
    created_at                  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at                  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at                  DATETIME(3) DEFAULT NULL,
    UNIQUE KEY uk_altoc_contract_line_code (code),
    UNIQUE KEY uk_altoc_contract_line_no (contract_id, line_no),
    KEY idx_altoc_contract_line_contract (contract_id, sort_no, id),
    KEY idx_altoc_contract_line_type (line_type),
    KEY idx_altoc_contract_line_product (product_code),
    KEY idx_altoc_contract_line_source_quote_item (source_quotation_item_id),
    CONSTRAINT fk_altoc_contract_line_contract FOREIGN KEY (contract_id) REFERENCES altoc_contract(id) ON DELETE CASCADE,
    CONSTRAINT fk_altoc_contract_line_catalog FOREIGN KEY (catalog_item_id) REFERENCES altoc_catalog_item(id),
    CONSTRAINT fk_altoc_contract_line_quote_item FOREIGN KEY (source_quotation_item_id) REFERENCES altoc_quotation_item(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='合同行';

CREATE TABLE altoc_contract_obligation (
    id                      BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    code                    VARCHAR(64)  NOT NULL COMMENT 'OB-xxxxxx；Aims 项目义务关系引用',
    contract_id             BIGINT UNSIGNED NOT NULL,
    contract_line_id        BIGINT UNSIGNED DEFAULT NULL,
    obligation_type         VARCHAR(50)  NOT NULL COMMENT 'delivery/acceptance/service_period/training/warranty/...',
    name                    VARCHAR(200) NOT NULL,
    description             TEXT DEFAULT NULL,
    fulfillment_method      VARCHAR(30)  DEFAULT NULL,
    planned_start_at        DATETIME(3) DEFAULT NULL,
    planned_due_at          DATETIME(3) DEFAULT NULL,
    actual_completed_at     DATETIME(3) DEFAULT NULL,
    submitted_at            DATETIME(3) DEFAULT NULL,
    accepted_at             DATETIME(3) DEFAULT NULL,
    rejected_at             DATETIME(3) DEFAULT NULL,
    acceptance_required     TINYINT(1) NOT NULL DEFAULT 0,
    acceptance_criteria     VARCHAR(1000) DEFAULT NULL,
    status                  VARCHAR(30)  NOT NULL DEFAULT 'not_started' COMMENT 'not_started/in_progress/submitted/accepted/rejected/completed/waived/blocked/cancelled',
    owner_uid               VARCHAR(64)  DEFAULT NULL,
    evidence_document_uuid  CHAR(36) DEFAULT NULL COMMENT 'Codocs 文档 uuid',
    evidence_note           VARCHAR(1000) DEFAULT NULL,
    waiver_reason           VARCHAR(500) DEFAULT NULL,
    reject_reason           VARCHAR(500) DEFAULT NULL,
    source_type             VARCHAR(50)  DEFAULT NULL COMMENT 'contract_line/template/manual',
    source_ref_code         VARCHAR(100) DEFAULT NULL,
    sort_no                 INT NOT NULL DEFAULT 0,
    version_no              INT NOT NULL DEFAULT 1,
    snapshot_json           JSON DEFAULT NULL,
    row_version             INT UNSIGNED NOT NULL DEFAULT 1,
    created_by              VARCHAR(64) DEFAULT NULL,
    updated_by              VARCHAR(64) DEFAULT NULL,
    created_at              DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at              DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at              DATETIME(3) DEFAULT NULL,
    UNIQUE KEY uk_altoc_contract_obligation_code (code),
    KEY idx_altoc_contract_obligation_contract (contract_id, sort_no, id),
    KEY idx_altoc_contract_obligation_line (contract_line_id),
    KEY idx_altoc_contract_obligation_status (status, planned_due_at),
    KEY idx_altoc_contract_obligation_owner (owner_uid, status),
    CONSTRAINT fk_altoc_contract_obligation_contract FOREIGN KEY (contract_id) REFERENCES altoc_contract(id) ON DELETE CASCADE,
    CONSTRAINT fk_altoc_contract_obligation_line FOREIGN KEY (contract_line_id) REFERENCES altoc_contract_line(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='合同履约义务';

CREATE TABLE altoc_contract_orchestration_job (
    id                  BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    job_key             VARCHAR(191) NOT NULL COMMENT '幂等键：contract_code + activation 版本',
    contract_id         BIGINT UNSIGNED NOT NULL,
    job_type            VARCHAR(50)  NOT NULL DEFAULT 'contract_activation',
    status              VARCHAR(30)  NOT NULL DEFAULT 'pending' COMMENT 'pending/running/succeeded/failed/cancelled',
    plan_json           JSON NOT NULL COMMENT '冻结的启动计划（项目计划、里程碑、资产计划、服务协议）',
    plan_sha256         CHAR(64) NOT NULL,
    started_at          DATETIME(3) DEFAULT NULL,
    finished_at         DATETIME(3) DEFAULT NULL,
    last_error_code     VARCHAR(100) DEFAULT NULL,
    row_version         INT UNSIGNED NOT NULL DEFAULT 1,
    created_by          VARCHAR(64) DEFAULT NULL,
    updated_by          VARCHAR(64) DEFAULT NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_altoc_orchestration_job_key (job_key),
    KEY idx_altoc_orchestration_job_contract (contract_id, status),
    CONSTRAINT fk_altoc_orchestration_job_contract FOREIGN KEY (contract_id) REFERENCES altoc_contract(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='合同履约启动编排作业';

CREATE TABLE altoc_contract_orchestration_step (
    id                  BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    job_id              BIGINT UNSIGNED NOT NULL,
    step_key            VARCHAR(100) NOT NULL COMMENT 'plan:<plan_key>:project / :milestones / asset / service_agreement',
    sequence_no         INT NOT NULL,
    depends_on_step_key VARCHAR(100) DEFAULT NULL,
    target_domain       VARCHAR(20)  NOT NULL COMMENT 'aims/assets/altoc',
    status              VARCHAR(30)  NOT NULL DEFAULT 'pending' COMMENT 'pending/succeeded/failed/skipped',
    operation_id        CHAR(36) DEFAULT NULL COMMENT '仍走可靠操作时的 altoc_integration_operation.operation_id；同库共享事务时为空',
    result_biz_code     VARCHAR(191) DEFAULT NULL COMMENT '产出对象编码：project_code 等',
    result_json         JSON DEFAULT NULL,
    last_error_code     VARCHAR(100) DEFAULT NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_altoc_orchestration_step (job_id, step_key),
    KEY idx_altoc_orchestration_step_operation (operation_id),
    CONSTRAINT fk_altoc_orchestration_step_job FOREIGN KEY (job_id) REFERENCES altoc_contract_orchestration_job(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='合同履约启动编排步骤';

CREATE TABLE altoc_contract_party (
    id                  BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    contract_id         BIGINT UNSIGNED NOT NULL,
    party_type          VARCHAR(30)  NOT NULL COMMENT 'customer/supplier/organization/person',
    party_ref_code      VARCHAR(100) DEFAULT NULL COMMENT 'customer_code / supplier_code 等稳定编码',
    party_name_snapshot VARCHAR(200) NOT NULL,
    role_code           VARCHAR(50)  NOT NULL COMMENT 'buyer/seller/payer/end_customer/vendor/agent/guarantor',
    is_primary          TINYINT(1) NOT NULL DEFAULT 0,
    contact_name        VARCHAR(100) DEFAULT NULL,
    contact_mobile      VARCHAR(50)  DEFAULT NULL,
    contact_email       VARCHAR(100) DEFAULT NULL,
    sort_no             INT NOT NULL DEFAULT 0,
    created_by          VARCHAR(64) DEFAULT NULL,
    updated_by          VARCHAR(64) DEFAULT NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at          DATETIME(3) DEFAULT NULL,
    UNIQUE KEY uk_altoc_contract_party_role_ref (contract_id, role_code, party_ref_code),
    KEY idx_altoc_contract_party_role (role_code, is_primary),
    CONSTRAINT fk_altoc_contract_party_contract FOREIGN KEY (contract_id) REFERENCES altoc_contract(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='合同参与方';

CREATE TABLE altoc_contract_payment_term (
    id                  BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    code                VARCHAR(64)  NOT NULL COMMENT 'PT-xxxxxx',
    contract_id         BIGINT UNSIGNED NOT NULL,
    contract_line_id    BIGINT UNSIGNED DEFAULT NULL COMMENT '为空=合同级条款（按合同总额）；非空=行级条款',
    term_name           VARCHAR(100) NOT NULL,
    term_type           VARCHAR(20)  NOT NULL COMMENT 'one_time/advance/milestone/acceptance/retention/annual_service',
    billing_mode        VARCHAR(30)  NOT NULL DEFAULT 'stage' COMMENT 'one_time/ratio/stage/annual',
    sort_no             INT NOT NULL DEFAULT 0,
    amount              DECIMAL(18,2) NOT NULL,
    ratio               DECIMAL(8,4)  DEFAULT NULL COMMENT '占条款基数（合同或合同行金额）比例 %',
    currency_code       CHAR(3) NOT NULL DEFAULT 'CNY',
    condition_desc      VARCHAR(500) DEFAULT NULL,
    trigger_type        VARCHAR(50)  NOT NULL DEFAULT 'manual' COMMENT 'contract_signed/stage_completed/obligation_completed/obligation_accepted/milestone_accepted/date/recurring/manual',
    trigger_stage_type  VARCHAR(30)  DEFAULT NULL COMMENT 'stage_completed 时：contract_signed/delivery/acceptance/service_end',
    trigger_obligation_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'obligation_* 时绑定的履约义务',
    expected_date       DATE DEFAULT NULL,
    recurrence_interval VARCHAR(20)  DEFAULT NULL COMMENT 'year/quarter/month',
    recurrence_month    TINYINT DEFAULT NULL,
    recurrence_day      TINYINT DEFAULT NULL,
    service_start_date  DATE DEFAULT NULL,
    service_end_date    DATE DEFAULT NULL,
    invoice_required    TINYINT(1) NOT NULL DEFAULT 1,
    row_version         INT UNSIGNED NOT NULL DEFAULT 1,
    created_by          VARCHAR(64) DEFAULT NULL,
    updated_by          VARCHAR(64) DEFAULT NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at          DATETIME(3) DEFAULT NULL,
    UNIQUE KEY uk_altoc_contract_payment_term_code (code),
    KEY idx_altoc_contract_payment_term_contract (contract_id, sort_no, id),
    KEY idx_altoc_contract_payment_term_line (contract_line_id),
    KEY idx_altoc_contract_payment_term_trigger (trigger_type, trigger_stage_type),
    CONSTRAINT fk_altoc_contract_payment_term_contract FOREIGN KEY (contract_id) REFERENCES altoc_contract(id) ON DELETE CASCADE,
    CONSTRAINT fk_altoc_contract_payment_term_line FOREIGN KEY (contract_line_id) REFERENCES altoc_contract_line(id),
    CONSTRAINT ck_altoc_contract_payment_term_amount CHECK (amount >= 0 AND (ratio IS NULL OR (ratio >= 0 AND ratio <= 100))),
    CONSTRAINT fk_altoc_contract_payment_term_obligation FOREIGN KEY (trigger_obligation_id) REFERENCES altoc_contract_obligation(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='合同付款条款（商务约定；结算计划由条款派生）';

CREATE TABLE altoc_contract_project_link (
    id                      BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    contract_id             BIGINT UNSIGNED NOT NULL,
    project_code            VARCHAR(64)  NOT NULL COMMENT 'aims_projects.project_code（跨域键，不建 FK）',
    project_name_snapshot   VARCHAR(200) DEFAULT NULL,
    project_role            VARCHAR(30)  NOT NULL DEFAULT 'delivery' COMMENT 'delivery/service/presales/internal',
    plan_key                VARCHAR(100) DEFAULT NULL COMMENT '履约启动项目计划键',
    link_mode               VARCHAR(30)  NOT NULL DEFAULT 'created_from_contract' COMMENT 'created_from_contract/linked_existing',
    status                  VARCHAR(30)  NOT NULL DEFAULT 'active' COMMENT 'planned/active/closed/cancelled',
    source_job_id           BIGINT UNSIGNED DEFAULT NULL,
    row_version             INT UNSIGNED NOT NULL DEFAULT 1,
    created_by              VARCHAR(64) DEFAULT NULL,
    updated_by              VARCHAR(64) DEFAULT NULL,
    created_at              DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at              DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at              DATETIME(3) DEFAULT NULL,
    UNIQUE KEY uk_altoc_contract_project_link (contract_id, project_code, project_role),
    KEY idx_altoc_contract_project_contract (contract_id, status),
    KEY idx_altoc_contract_project_plan (contract_id, plan_key),
    KEY idx_altoc_contract_project_code (project_code),
    CONSTRAINT fk_altoc_contract_project_contract FOREIGN KEY (contract_id) REFERENCES altoc_contract(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='合同—Aims 项目关联（多项目）；行/义务覆盖由两张 rel 表表达，不再使用 *_codes_json';

CREATE TABLE altoc_contract_project_obligation_rel (
    id                          BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    contract_project_link_id    BIGINT UNSIGNED NOT NULL,
    obligation_id               BIGINT UNSIGNED NOT NULL,
    created_by                  VARCHAR(64) DEFAULT NULL,
    created_at                  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at                  DATETIME(3) DEFAULT NULL,
    UNIQUE KEY uk_altoc_contract_project_obligation_rel (contract_project_link_id, obligation_id),
    KEY idx_altoc_cpor_obligation (obligation_id),
    CONSTRAINT fk_altoc_cpor_link FOREIGN KEY (contract_project_link_id) REFERENCES altoc_contract_project_link(id),
    CONSTRAINT fk_altoc_cpor_obligation FOREIGN KEY (obligation_id) REFERENCES altoc_contract_obligation(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='项目关联—履约义务结构化关系';

CREATE TABLE altoc_contract_stage (
    id              BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    code            VARCHAR(64) NOT NULL,
    contract_id     BIGINT UNSIGNED NOT NULL,
    stage_type      VARCHAR(30) NOT NULL COMMENT 'contract_signed/delivery/acceptance/service_end',
    stage_name      VARCHAR(100) NOT NULL,
    status          VARCHAR(30) NOT NULL DEFAULT 'completed' COMMENT 'pending/completed',
    stage_date      DATE DEFAULT NULL,
    evidence_note   VARCHAR(1000) DEFAULT NULL,
    document_uuid   CHAR(36) DEFAULT NULL,
    handled_by      VARCHAR(64) DEFAULT NULL,
    handled_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_altoc_contract_stage_type (contract_id, stage_type),
    UNIQUE KEY uk_altoc_contract_stage_code (code),
    CONSTRAINT fk_altoc_contract_stage_contract FOREIGN KEY (contract_id) REFERENCES altoc_contract(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='合同级履约环节事实（合同级付款条款的触发源）';

CREATE TABLE altoc_billing_schedule (
    id                          BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    code                        VARCHAR(64)  NOT NULL COMMENT 'BS-xxxxxx；Finance / Aims 跨域引用键（替代 receivable_plan_code）',
    contract_id                 BIGINT UNSIGNED NOT NULL,
    contract_line_id            BIGINT UNSIGNED DEFAULT NULL,
    obligation_id               BIGINT UNSIGNED DEFAULT NULL,
    payment_term_id             BIGINT UNSIGNED DEFAULT NULL COMMENT '派生来源条款',
    direction                   VARCHAR(20)  NOT NULL DEFAULT 'receivable' COMMENT 'receivable/payable',
    name                        VARCHAR(200) NOT NULL,
    plan_type                   VARCHAR(20)  DEFAULT NULL COMMENT 'advance/milestone/acceptance/retention/recurring/one_time',
    trigger_type                VARCHAR(50)  NOT NULL COMMENT 'contract_signed/stage_completed/obligation_completed/obligation_accepted/milestone_accepted/date/recurring/manual',
    trigger_ref_code            VARCHAR(100) DEFAULT NULL COMMENT '触发对象编码：stage_type / obligation_code / Aims milestone 键',
    amount                      DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    currency_code               CHAR(3) NOT NULL DEFAULT 'CNY',
    ratio                       DECIMAL(8,4)  DEFAULT NULL,
    planned_invoice_date        DATE DEFAULT NULL,
    due_date                    DATE DEFAULT NULL COMMENT '计划回款/到期日（原 planned_payment_date / due_date）',
    recurrence_rule_json        JSON DEFAULT NULL,
    recurrence_period           CHAR(7) DEFAULT NULL COMMENT '周期性结算的期间 YYYY-MM（唯一键的一部分）',
    invoice_required            TINYINT(1) NOT NULL DEFAULT 1,
    status                      VARCHAR(30)  NOT NULL DEFAULT 'planned' COMMENT 'planned/billable/invoicing/invoiced/partially_received/received/bad_debt/cancelled',
    invoiced_amount             DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT 'Finance 正式发票累计（共享事务回写）',
    received_amount             DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT 'Finance 核销分配累计（共享事务回写）',
    unreceived_amount           DECIMAL(18,2) GENERATED ALWAYS AS (GREATEST(amount - received_amount, 0)) STORED,
    overdue_days                INT NOT NULL DEFAULT 0 COMMENT '扫描任务维护；不改变 status',
    is_overdue                  TINYINT(1) NOT NULL DEFAULT 0,
    risk_level                  VARCHAR(20)  DEFAULT NULL COMMENT 'high/medium/low',
    owner_uid                   VARCHAR(64)  DEFAULT NULL,
    collection_responsible_uid  VARCHAR(64)  DEFAULT NULL COMMENT '应收催收唯一直接责任人；不从合同负责人推导',
    collection_due_at           DATETIME(3)  DEFAULT NULL,
    billable_at                 DATETIME(3)  DEFAULT NULL,
    billable_source             VARCHAR(50)  DEFAULT NULL COMMENT 'obligation/stage/aims_milestone/manual；谁触发了 billable',
    finance_synced_at           DATETIME(3)  DEFAULT NULL COMMENT '最近一次 Finance 共享事务回写时间',
    source_type                 VARCHAR(50)  DEFAULT NULL COMMENT 'payment_term/contract_line/manual',
    source_ref_code             VARCHAR(100) DEFAULT NULL,
    snapshot_json               JSON DEFAULT NULL,
    remark                      VARCHAR(500) DEFAULT NULL,
    row_version                 INT UNSIGNED NOT NULL DEFAULT 1,
    created_by                  VARCHAR(64) DEFAULT NULL,
    updated_by                  VARCHAR(64) DEFAULT NULL,
    created_at                  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at                  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at                  DATETIME(3) DEFAULT NULL,
    UNIQUE KEY uk_altoc_billing_schedule_code (code),
    UNIQUE KEY uk_altoc_billing_schedule_term_period (payment_term_id, recurrence_period, obligation_id),
    KEY idx_altoc_billing_schedule_contract (contract_id, due_date, id),
    KEY idx_altoc_billing_schedule_line (contract_line_id),
    KEY idx_altoc_billing_schedule_obligation (obligation_id),
    KEY idx_altoc_billing_schedule_status (status, due_date, id),
    KEY idx_altoc_billing_schedule_collection (collection_responsible_uid, status, due_date),
    KEY idx_altoc_billing_schedule_owner (owner_uid, status),
    CONSTRAINT fk_altoc_billing_schedule_contract FOREIGN KEY (contract_id) REFERENCES altoc_contract(id),
    CONSTRAINT fk_altoc_billing_schedule_line FOREIGN KEY (contract_line_id) REFERENCES altoc_contract_line(id),
    CONSTRAINT fk_altoc_billing_schedule_obligation FOREIGN KEY (obligation_id) REFERENCES altoc_contract_obligation(id),
    CONSTRAINT fk_altoc_billing_schedule_term FOREIGN KEY (payment_term_id) REFERENCES altoc_contract_payment_term(id),
    CONSTRAINT ck_altoc_billing_schedule_amounts CHECK (amount >= 0 AND invoiced_amount >= 0 AND received_amount >= 0),
    CONSTRAINT ck_altoc_billing_schedule_collection CHECK (
      collection_responsible_uid IS NULL OR (
        collection_responsible_uid = TRIM(collection_responsible_uid) AND collection_responsible_uid <> ''
        AND LOWER(collection_responsible_uid) <> '@all' AND collection_responsible_uid NOT REGEXP '[[:cntrl:]]'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='合同结算计划（应收/应付节点；原 contract_billing_schedule + receivable_plan）';

CREATE TABLE altoc_contract_project_line_rel (
    id                          BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    contract_project_link_id    BIGINT UNSIGNED NOT NULL,
    contract_line_id            BIGINT UNSIGNED NOT NULL,
    relation_type               VARCHAR(30)  NOT NULL DEFAULT 'delivery' COMMENT 'delivery/customization/training/warranty/maintenance/change/other',
    allocation_method           VARCHAR(30)  NOT NULL DEFAULT 'unallocated' COMMENT 'unallocated/direct/ratio/amount/workdays',
    allocation_ratio            DECIMAL(8,4)  DEFAULT NULL,
    allocated_amount            DECIMAL(18,2) DEFAULT NULL,
    planned_workdays            DECIMAL(10,2) DEFAULT NULL,
    created_by                  VARCHAR(64) DEFAULT NULL,
    updated_by                  VARCHAR(64) DEFAULT NULL,
    created_at                  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at                  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at                  DATETIME(3) DEFAULT NULL,
    UNIQUE KEY uk_altoc_contract_project_line_rel (contract_project_link_id, contract_line_id, relation_type),
    KEY idx_altoc_cplr_line (contract_line_id),
    CONSTRAINT fk_altoc_cplr_link FOREIGN KEY (contract_project_link_id) REFERENCES altoc_contract_project_link(id),
    CONSTRAINT fk_altoc_cplr_line FOREIGN KEY (contract_line_id) REFERENCES altoc_contract_line(id),
    CONSTRAINT ck_altoc_cplr_nonneg CHECK ((allocation_ratio IS NULL OR allocation_ratio >= 0) AND (allocated_amount IS NULL OR allocated_amount >= 0) AND (planned_workdays IS NULL OR planned_workdays >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='项目关联—合同行结构化关系（多行多项目分摊）';
