-- Repeatable/idempotent source lifecycle for People caller-owned dead-letter actionables.
-- This table is intentionally restricted by data-runtime to the People
-- Directory→Console and People→Assets operation-code allowlist.
CREATE TABLE IF NOT EXISTS integration_operation_dead_letter_actionable (
  operation_id CHAR(36) NOT NULL,
  generation_no BIGINT UNSIGNED NOT NULL,
  tenant_code VARCHAR(100) NOT NULL,
  deployment_code VARCHAR(100) NOT NULL,
  source_app VARCHAR(64) NOT NULL,
  target_app VARCHAR(64) NOT NULL,
  operation_code VARCHAR(191) NOT NULL,
  source_biz_type VARCHAR(64) NOT NULL,
  source_biz_code VARCHAR(191) NOT NULL,
  attempt_count INT UNSIGNED NOT NULL,
  max_attempts INT UNSIGNED NOT NULL,
  last_error_code VARCHAR(100) DEFAULT NULL,
  last_error_class VARCHAR(50) DEFAULT NULL,
  dead_lettered_at DATETIME(3) NOT NULL,
  original_actor_uid VARCHAR(100) DEFAULT NULL,
  source_operation_version BIGINT UNSIGNED NOT NULL,
  actionable_key VARCHAR(191) NOT NULL,
  publish_object_version VARCHAR(191) NOT NULL,
  notification_id VARCHAR(64) DEFAULT NULL,
  recipient_uids JSON DEFAULT NULL COMMENT 'Console ACK returned normalized explicit recipient UID array',
  publish_acked_at DATETIME(3) DEFAULT NULL,
  closure_state VARCHAR(16) DEFAULT NULL COMMENT 'resolved/cancelled',
  closure_object_version VARCHAR(191) DEFAULT NULL,
  closure_pending_at DATETIME(3) DEFAULT NULL,
  closure_acked_at DATETIME(3) DEFAULT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (operation_id, generation_no),
  UNIQUE KEY uk_people_iopdla_actionable (tenant_code, deployment_code, source_app, actionable_key),
  UNIQUE KEY uk_people_iopdla_notification (tenant_code, deployment_code, source_app, notification_id),
  INDEX idx_people_iopdla_publish (tenant_code, deployment_code, source_app, publish_acked_at, dead_lettered_at),
  INDEX idx_people_iopdla_closure (tenant_code, deployment_code, source_app, closure_acked_at, closure_pending_at),
  CONSTRAINT fk_people_iopdla_operation FOREIGN KEY (operation_id) REFERENCES integration_operation(operation_id) ON DELETE RESTRICT,
  CONSTRAINT chk_people_iopdla_closure CHECK (closure_state IS NULL OR closure_state IN ('resolved','cancelled')),
  CONSTRAINT chk_people_iopdla_recipient CHECK (recipient_uids IS NULL OR JSON_TYPE(recipient_uids) = 'ARRAY')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='People dead-letter actionable generation evidence';
