-- Finance caller-owned reliable-operation outbox for reconciliation -> Altoc summary delivery.
-- Additive, secret-free and safe to rerun. Not executed by this change.

CREATE TABLE IF NOT EXISTS integration_operation (
  operation_id CHAR(36) PRIMARY KEY,
  operation_key VARCHAR(191) NOT NULL,
  correlation_key VARCHAR(191) NOT NULL,
  sequence_no INT UNSIGNED NOT NULL DEFAULT 1,
  depends_on_operation_key VARCHAR(191) DEFAULT NULL,
  tenant_code VARCHAR(100) NOT NULL,
  deployment_code VARCHAR(100) NOT NULL,
  source_app VARCHAR(50) NOT NULL,
  target_app VARCHAR(50) NOT NULL,
  operation_code VARCHAR(191) NOT NULL,
  required_capability VARCHAR(191) NOT NULL,
  source_biz_type VARCHAR(100) NOT NULL,
  source_biz_code VARCHAR(191) NOT NULL,
  target_receipt_id CHAR(36) DEFAULT NULL,
  target_biz_type VARCHAR(100) DEFAULT NULL,
  target_biz_code VARCHAR(191) DEFAULT NULL,
  idempotency_key VARCHAR(191) NOT NULL,
  command_schema_version VARCHAR(30) NOT NULL DEFAULT 'v1',
  command_json JSON NOT NULL,
  command_sha256 CHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
  max_attempts INT UNSIGNED NOT NULL DEFAULT 8,
  next_attempt_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  last_attempt_at DATETIME(3) DEFAULT NULL,
  locked_by VARCHAR(100) DEFAULT NULL,
  locked_until DATETIME(3) DEFAULT NULL,
  fencing_token BIGINT UNSIGNED NOT NULL DEFAULT 0,
  version_no BIGINT UNSIGNED NOT NULL DEFAULT 1,
  original_request_id VARCHAR(100) DEFAULT NULL,
  correlation_id VARCHAR(100) DEFAULT NULL,
  original_actor_uid VARCHAR(100) DEFAULT NULL,
  service_client_id VARCHAR(100) DEFAULT NULL,
  replay_count INT UNSIGNED NOT NULL DEFAULT 0,
  last_replay_actor_uid VARCHAR(100) DEFAULT NULL,
  last_replay_reason VARCHAR(500) DEFAULT NULL,
  last_replay_at DATETIME(3) DEFAULT NULL,
  last_http_status SMALLINT UNSIGNED DEFAULT NULL,
  last_error_code VARCHAR(100) DEFAULT NULL,
  last_error_class VARCHAR(50) DEFAULT NULL,
  last_error_summary VARCHAR(1000) DEFAULT NULL,
  last_error_at DATETIME(3) DEFAULT NULL,
  response_summary_sha256 CHAR(64) DEFAULT NULL,
  failure_notified_at DATETIME(3) DEFAULT NULL,
  failure_notification_id VARCHAR(64) DEFAULT NULL,
  succeeded_at DATETIME(3) DEFAULT NULL,
  failed_permanent_at DATETIME(3) DEFAULT NULL,
  dead_lettered_at DATETIME(3) DEFAULT NULL,
  cancelled_at DATETIME(3) DEFAULT NULL,
  created_by VARCHAR(100) DEFAULT NULL,
  updated_by VARCHAR(100) DEFAULT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uk_iop_identity (tenant_code, deployment_code, source_app, target_app, operation_code, idempotency_key),
  UNIQUE KEY uk_iop_operation_key (tenant_code, deployment_code, source_app, operation_key),
  UNIQUE KEY uk_iop_chain_sequence (tenant_code, deployment_code, source_app, correlation_key, sequence_no),
  INDEX idx_iop_due (status, next_attempt_at, locked_until),
  INDEX idx_iop_lock (status, locked_until),
  INDEX idx_iop_source_biz (tenant_code, deployment_code, source_app, source_biz_type, source_biz_code),
  INDEX idx_iop_target_biz (tenant_code, deployment_code, target_app, target_biz_type, target_biz_code),
  INDEX idx_iop_dependency (tenant_code, deployment_code, source_app, depends_on_operation_key),
  INDEX idx_iop_failure_notification (tenant_code, deployment_code, source_app, status, failure_notified_at, dead_lettered_at, operation_id),
  CONSTRAINT chk_fin_iop_cross_app CHECK (source_app <> target_app),
  CONSTRAINT chk_fin_iop_status CHECK (status IN ('pending','processing','retry_wait','partial_unknown','succeeded','failed_permanent','dead_letter','cancelled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Finance caller-owned cross-app command outbox';

CREATE TABLE IF NOT EXISTS integration_operation_attempt (
  attempt_id CHAR(36) PRIMARY KEY,
  operation_id CHAR(36) NOT NULL,
  operation_code VARCHAR(191) NOT NULL,
  attempt_no INT UNSIGNED NOT NULL,
  trigger_type VARCHAR(32) NOT NULL,
  request_id VARCHAR(100) DEFAULT NULL,
  correlation_id VARCHAR(100) DEFAULT NULL,
  locked_by VARCHAR(100) DEFAULT NULL,
  fencing_token BIGINT UNSIGNED NOT NULL,
  result_status VARCHAR(32) NOT NULL DEFAULT 'processing',
  http_status SMALLINT UNSIGNED DEFAULT NULL,
  error_code VARCHAR(100) DEFAULT NULL,
  error_class VARCHAR(50) DEFAULT NULL,
  error_summary VARCHAR(1000) DEFAULT NULL,
  target_biz_type VARCHAR(100) DEFAULT NULL,
  target_biz_code VARCHAR(191) DEFAULT NULL,
  response_summary_sha256 CHAR(64) DEFAULT NULL,
  started_at DATETIME(3) NOT NULL,
  finished_at DATETIME(3) DEFAULT NULL,
  duration_ms BIGINT UNSIGNED DEFAULT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY uk_fin_ioa_operation_attempt (operation_id, attempt_no),
  INDEX idx_fin_ioa_operation_created (operation_id, created_at),
  INDEX idx_fin_ioa_result (result_status, created_at),
  CONSTRAINT fk_fin_ioa_operation FOREIGN KEY (operation_id) REFERENCES integration_operation(operation_id) ON DELETE RESTRICT,
  CONSTRAINT chk_fin_ioa_result CHECK (result_status IN ('processing','succeeded','retry_wait','partial_unknown','failed_permanent','dead_letter','cancelled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Finance reliable-operation append-only attempts';
