-- HZY Platform SQL Migration v2.10: deployment bootstrap secrets.
-- Date: 2026-05-01
-- Purpose:
--   Persist Console deployment bootstrap secrets generated by Platform delivery
--   artifacts. The first use case is HZY_CONSOLE_VAULT_MASTER_KEY, which must
--   stay stable after Console starts storing db_encrypted vault credentials.

SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `deployment_bootstrap_secrets` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `deployment_id` BIGINT UNSIGNED NOT NULL,
  `tenant_code` VARCHAR(64) NOT NULL,
  `app_code` VARCHAR(64) NOT NULL,
  `secret_code` VARCHAR(128) NOT NULL,
  `secret_name` VARCHAR(255) NOT NULL,
  `secret_value` TEXT NOT NULL COMMENT '交付材料可恢复密钥；仅用于生成 runtime env，不进入普通部署配置 API',
  `secret_last4` VARCHAR(8) NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'active',
  `created_by_account_id` BIGINT UNSIGNED NULL COMMENT '跨域→platform_accounts，无 FK',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_deployment_bootstrap_secrets_code` (`deployment_id`, `secret_code`),
  KEY `idx_deployment_bootstrap_secrets_tenant_app` (`tenant_code`, `app_code`, `status`),
  KEY `idx_deployment_bootstrap_secrets_status` (`status`, `updated_at`),
  CONSTRAINT `fk_deployment_bootstrap_secrets_deployment`
    FOREIGN KEY (`deployment_id`) REFERENCES `deployments` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
