-- Presentation preferences only; these rows never grant access to roadmap data.
CREATE TABLE IF NOT EXISTS product_roadmap_saved_views (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 biz_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 product_code VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 cycle_id BIGINT UNSIGNED NOT NULL,
 owner_uid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 title VARCHAR(200) NOT NULL,
 audience VARCHAR(32) COLLATE utf8mb4_bin NOT NULL,
 visibility VARCHAR(16) COLLATE utf8mb4_bin NOT NULL,
 roadmap_year SMALLINT UNSIGNED NOT NULL,
 roadmap_quarter TINYINT UNSIGNED NOT NULL,
 unscheduled BOOLEAN NOT NULL DEFAULT FALSE,
 revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
 created_by VARCHAR(64) NOT NULL,
 updated_by VARCHAR(64) NOT NULL,
 created_at DATETIME(3) NOT NULL,
 updated_at DATETIME(3) NOT NULL,
 PRIMARY KEY(id),
 UNIQUE KEY uk_pc_saved_view_biz(biz_id),
 KEY idx_pc_saved_view_owner(product_code,owner_uid,id),
 KEY idx_pc_saved_view_shared(product_code,visibility,id),
 CONSTRAINT fk_pc_saved_view_cycle FOREIGN KEY(cycle_id,product_code) REFERENCES product_planning_cycles(id,product_code),
 CONSTRAINT ck_pc_saved_view_audience CHECK(audience IN ('planning','delivery','stakeholder')),
 CONSTRAINT ck_pc_saved_view_visibility CHECK(visibility IN ('personal','product')),
 CONSTRAINT ck_pc_saved_view_window CHECK(roadmap_year BETWEEN 1000 AND 9999 AND roadmap_quarter BETWEEN 1 AND 4),
 CONSTRAINT ck_pc_saved_view_unscheduled CHECK(unscheduled IN (0,1)),
 CONSTRAINT ck_pc_saved_view_revision CHECK(revision>0),
 CONSTRAINT ck_pc_saved_view_title CHECK(CHAR_LENGTH(TRIM(title))>0),
 CONSTRAINT ck_pc_saved_view_actors CHECK(CHAR_LENGTH(TRIM(owner_uid))>0 AND CHAR_LENGTH(TRIM(created_by))>0 AND CHAR_LENGTH(TRIM(updated_by))>0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
