-- Preserve weighted assessments and store RICE-specific fields without fabricated value dimensions.
SET @pc_rice_assessment_sql = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='product_priority_assessments' AND column_name='model_method'), 'SELECT 1', 'ALTER TABLE product_priority_assessments ADD COLUMN model_method VARCHAR(32) COLLATE utf8mb4_bin NOT NULL DEFAULT ''weighted-value-effort''');
PREPARE pc_rice_assessment_stmt FROM @pc_rice_assessment_sql;
EXECUTE pc_rice_assessment_stmt;
DEALLOCATE PREPARE pc_rice_assessment_stmt;
SET @pc_rice_assessment_sql = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='product_priority_assessments' AND column_name='rice_impact'), 'SELECT 1', 'ALTER TABLE product_priority_assessments ADD COLUMN rice_impact DECIMAL(3,2) NULL');
PREPARE pc_rice_assessment_stmt FROM @pc_rice_assessment_sql;
EXECUTE pc_rice_assessment_stmt;
DEALLOCATE PREPARE pc_rice_assessment_stmt;
SET @pc_rice_assessment_sql = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='product_priority_assessments' AND column_name='reach_observation_id'), 'SELECT 1', 'ALTER TABLE product_priority_assessments ADD COLUMN reach_observation_id BIGINT UNSIGNED NULL');
PREPARE pc_rice_assessment_stmt FROM @pc_rice_assessment_sql;
EXECUTE pc_rice_assessment_stmt;
DEALLOCATE PREPARE pc_rice_assessment_stmt;
SET @pc_rice_assessment_sql = IF(EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='product_rice_reach_observations' AND index_name='uk_pc_rice_observation_item'), 'SELECT 1', 'ALTER TABLE product_rice_reach_observations ADD UNIQUE KEY uk_pc_rice_observation_item(id,planning_item_id)');
PREPARE pc_rice_assessment_stmt FROM @pc_rice_assessment_sql;
EXECUTE pc_rice_assessment_stmt;
DEALLOCATE PREPARE pc_rice_assessment_stmt;
SET @pc_rice_assessment_sql = IF(EXISTS(SELECT 1 FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='product_priority_assessments' AND constraint_name='fk_pc_assessment_reach'), 'SELECT 1', 'ALTER TABLE product_priority_assessments ADD CONSTRAINT fk_pc_assessment_reach FOREIGN KEY(reach_observation_id,planning_item_id) REFERENCES product_rice_reach_observations(id,planning_item_id)');
PREPARE pc_rice_assessment_stmt FROM @pc_rice_assessment_sql;
EXECUTE pc_rice_assessment_stmt;
DEALLOCATE PREPARE pc_rice_assessment_stmt;
SET @pc_rice_assessment_sql = IF(EXISTS(SELECT 1 FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='product_priority_assessments' AND constraint_name='ck_pc_assessment_method'), 'SELECT 1', 'ALTER TABLE product_priority_assessments ADD CONSTRAINT ck_pc_assessment_method CHECK(model_method IN (''weighted-value-effort'',''rice''))');
PREPARE pc_rice_assessment_stmt FROM @pc_rice_assessment_sql;
EXECUTE pc_rice_assessment_stmt;
DEALLOCATE PREPARE pc_rice_assessment_stmt;
SET @pc_rice_assessment_sql = IF(EXISTS(SELECT 1 FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='product_priority_assessments' AND constraint_name='ck_pc_assessment_rice_impact'), 'SELECT 1', 'ALTER TABLE product_priority_assessments ADD CONSTRAINT ck_pc_assessment_rice_impact CHECK(rice_impact IN (0.25,0.50,1.00,2.00,3.00))');
PREPARE pc_rice_assessment_stmt FROM @pc_rice_assessment_sql;
EXECUTE pc_rice_assessment_stmt;
DEALLOCATE PREPARE pc_rice_assessment_stmt;
SET @pc_rice_assessment_sql = IF(EXISTS(SELECT 1 FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='product_priority_assessments' AND constraint_name='ck_pc_assessment_method_fields'), 'SELECT 1', 'ALTER TABLE product_priority_assessments ADD CONSTRAINT ck_pc_assessment_method_fields CHECK((model_method=''weighted-value-effort'' AND rice_impact IS NULL AND reach_observation_id IS NULL) OR (model_method=''rice'' AND strategic IS NULL AND user_value IS NULL AND business IS NULL AND risk IS NULL AND value_score IS NULL))');
PREPARE pc_rice_assessment_stmt FROM @pc_rice_assessment_sql;
EXECUTE pc_rice_assessment_stmt;
DEALLOCATE PREPARE pc_rice_assessment_stmt;
SET @pc_rice_assessment_sql = IF(EXISTS(SELECT 1 FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='product_priority_assessments' AND constraint_name='ck_pc_assessment_model_complete'), 'SELECT 1', 'ALTER TABLE product_priority_assessments ADD CONSTRAINT ck_pc_assessment_model_complete CHECK(priority_score IS NULL OR (confidence IS NOT NULL AND effort_person_days IS NOT NULL AND ((model_method=''weighted-value-effort'' AND strategic IS NOT NULL AND user_value IS NOT NULL AND business IS NOT NULL AND risk IS NOT NULL AND value_score IS NOT NULL) OR (model_method=''rice'' AND rice_impact IS NOT NULL AND reach_observation_id IS NOT NULL))))');
PREPARE pc_rice_assessment_stmt FROM @pc_rice_assessment_sql;
EXECUTE pc_rice_assessment_stmt;
DEALLOCATE PREPARE pc_rice_assessment_stmt;
SET @pc_rice_assessment_sql = IF(NOT EXISTS(SELECT 1 FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='product_priority_assessments' AND constraint_name='ck_pc_assessment_complete'), 'SELECT 1', 'ALTER TABLE product_priority_assessments DROP CHECK ck_pc_assessment_complete');
PREPARE pc_rice_assessment_stmt FROM @pc_rice_assessment_sql;
EXECUTE pc_rice_assessment_stmt;
DEALLOCATE PREPARE pc_rice_assessment_stmt;
