<script setup lang="ts">
import { useAimsModule } from '../useAimsModule'
type Document = Record<string, unknown> & { id:number,title?:string,documentSource?:string,codocsUuid?:string|null }
const route=useRoute(); const {moduleUrl}=useAimsModule(); const projectId=computed(()=>String(route.params.id||'')); const documentId=computed(()=>String(route.params.documentId||'')); const item=ref<Document|null>(null); const loading=ref(true); const error=ref('')
function value(...keys:string[]){for(const key of keys){const v=item.value?.[key];if(v!==undefined&&v!==null&&String(v).trim())return String(v)}return '-'}
async function refresh(){loading.value=true;error.value='';try{const r=await $fetch<{code?:number,data?:Document}>(moduleUrl(`/api/v1/projects/${projectId.value}/documents/${documentId.value}`));if(r.code!==0||!r.data)throw Error('文档详情暂不可用');item.value=r.data}catch(cause){error.value=cause instanceof Error?cause.message:'文档详情暂不可用'}finally{loading.value=false}}
watch([projectId,documentId],refresh);onMounted(refresh)
</script>
<template><section class="space-y-5"><UButton :to="moduleUrl(`/projects/${projectId}/documents`)" variant="link" color="neutral" icon="i-lucide-arrow-left">返回项目文档</UButton><UAlert v-if="error" color="error" title="无法读取文档" :description="error"/><USkeleton v-else-if="loading" class="h-48 w-full"/><template v-else-if="item"><div class="flex items-center justify-between gap-3"><div><h1 class="text-2xl font-semibold text-highlighted">{{ item.title||'文档详情' }}</h1><p class="text-sm text-muted">{{ value('docCategory') }}</p></div><UButton v-if="value('documentSource')==='codocs'&&value('codocsUuid')!=='-'" :to="moduleUrl(`/projects/${projectId}/documents/${documentId}/open`)" icon="i-lucide-book-open">安全打开</UButton></div><UCard><dl class="grid gap-5 sm:grid-cols-2"><div><dt class="text-sm text-muted">来源</dt><dd>{{ value('documentSource') }}</dd></div><div><dt class="text-sm text-muted">创建人</dt><dd>{{ value('createdBy') }}</dd></div><div><dt class="text-sm text-muted">创建时间</dt><dd>{{ value('createdAt') }}</dd></div><div><dt class="text-sm text-muted">Codocs 标识</dt><dd>{{ value('codocsUuid') }}</dd></div></dl></UCard></template></section></template>
