<script setup lang="ts">
import { useAimsModule } from '../useAimsModule'
type Requirement = { id: number, req_code?: string, reqCode?: string, title?: string, type?: string, priority?: string, status?: string }
const route = useRoute(); const { moduleUrl } = useAimsModule(); const projectId = computed(() => String(route.params.id || ''))
const search = ref(''); const items = ref<Requirement[]>([]); const loading = ref(false); const error = ref('')
async function refresh() { loading.value = true; error.value = ''; try { const response = await $fetch<{ code?: number, data?: { items?: Requirement[] } | Requirement[] }>(moduleUrl(`/api/v1/projects/${projectId.value}/requirements`), { query: search.value.trim() ? { search: search.value.trim() } : {} }); if (response.code !== 0) throw Error('项目需求暂不可用'); items.value = Array.isArray(response.data) ? response.data : (response.data?.items || []) } catch (cause) { error.value = cause instanceof Error ? cause.message : '项目需求暂不可用' } finally { loading.value = false } }
watch(projectId, refresh); onMounted(refresh)
</script>
<template><section class="space-y-5"><div><UButton :to="moduleUrl(`/projects/${projectId}`)" variant="link" color="neutral" icon="i-lucide-arrow-left">返回项目</UButton><h1 class="mt-1 text-2xl font-semibold text-highlighted">项目需求</h1><p class="mt-1 text-sm text-muted">保留源系统中的产品规划关联语义，仅提供只读查看。</p></div><div class="flex gap-2"><UInput v-model="search" placeholder="搜索编号或标题" @keyup.enter="refresh" /><UButton :loading="loading" @click="refresh">查询</UButton></div><UAlert v-if="error" color="error" title="无法读取需求" :description="error" /><UTable :data="items" :loading="loading" :columns="[{ accessorKey: 'reqCode', header: '编号' }, { accessorKey: 'title', header: '标题' }, { accessorKey: 'type', header: '类型' }, { accessorKey: 'priority', header: '优先级' }, { accessorKey: 'status', header: '状态' }]" ><template #reqCode-cell="{ row }"><NuxtLink class="font-medium text-primary hover:underline" :to="moduleUrl(`/projects/${projectId}/requirements/${row.original.id}`)">{{ row.original.reqCode || row.original.req_code || row.original.id }}</NuxtLink></template><template #empty><CommonEmptyState icon="i-lucide-list-checks" title="暂无项目需求" description="当前条件下没有可访问需求。" /></template></UTable></section></template>
