<script setup lang="ts">
import { useAimsModule } from '../useAimsModule'
import { useAccountDepartments, useBusinessDomains } from '@hzy/foundation/app/composables/useAccount'
const route=useRoute(),router=useRouter(),{moduleUrl}=useAimsModule(),id=computed(()=>String(route.params.id||'')),loading=ref(true),saving=ref(false),error=ref(''),operationKey=ref('')
const { departments }=useAccountDepartments(),{ domains }=useBusinessDomains()
const form=reactive({expectedVersion:'',name:'',shortName:'',internalCode:'',description:'',methodology:'PIVR',portfolioId:null as number|null,domainCode:'',deptCode:'',leaderUid:'',startDate:'',endDate:''})
const selectedLeader=computed({get:()=>form.leaderUid?[form.leaderUid]:[],set:(uids:string[])=>{form.leaderUid=uids[0]||''}})
const departmentName=computed(()=>departments.value.find(d=>d.deptCode===form.deptCode)?.name||'未设置')
const domainName=computed(()=>domains.value.find(d=>d.domainCode===form.domainCode)?.domainName||'未设置')
const nameError=computed(()=>form.name&&!/^[\u4e00-\u9fa5a-zA-Z0-9]+(?:[vV]\d+)?$/.test(form.name)?'只能包含汉字、英文和数字，不允许空格和特殊字符':'')
async function load(){loading.value=true;error.value='';try{const r=await $fetch<{code?:number,data?:Record<string,any>}>(moduleUrl(`/api/v1/projects/${id.value}`));if(r.code!==0||!r.data?.editVersion)throw Error('项目资料版本暂不可用');const p=r.data;Object.assign(form,{expectedVersion:p.editVersion,name:p.name||'',shortName:p.shortName||'',internalCode:p.internalCode||'',description:p.description||'',methodology:p.methodology||'PIVR',portfolioId:p.portfolioId||null,domainCode:p.domainCode||'',deptCode:p.deptCode||'',leaderUid:p.leaderUid||'',startDate:String(p.startDate||'').slice(0,10),endDate:String(p.endDate||'').slice(0,10)})}catch(e){error.value=e instanceof Error?e.message:'项目资料暂不可用'}finally{loading.value=false}}
async function save(){if(nameError.value)return;saving.value=true;error.value='';operationKey.value||=crypto.randomUUID();try{const r=await $fetch<{code?:number}>(moduleUrl(`/api/v1/projects/${id.value}`),{method:'PUT',headers:{'Idempotency-Key':operationKey.value},body:form});if(r.code!==0)throw Error('项目编辑响应无效');operationKey.value='';await router.push(moduleUrl(`/projects/${id.value}`))}catch(e){error.value=e instanceof Error?e.message:'保存失败，可使用相同操作标识重试'}finally{saving.value=false}}
onMounted(load)
</script>
<template><section class="mx-auto max-w-3xl space-y-5"><div><UButton :to="moduleUrl(`/projects/${id}`)" variant="link" color="neutral" icon="i-lucide-arrow-left">返回项目</UButton><h1 class="mt-1 text-2xl font-semibold text-highlighted">编辑项目基本信息</h1></div><UAlert v-if="error" color="error" title="操作失败" :description="error"/><USkeleton v-if="loading" class="h-64"/><UCard v-else><div class="grid gap-4 sm:grid-cols-2"><UFormField label="项目名称" required :error="nameError"><UInput v-model="form.name"/></UFormField><UFormField label="项目简称" required><UInput v-model="form.shortName"/></UFormField><UFormField label="内部代号"><UInput v-model="form.internalCode"/></UFormField><UFormField label="负责人" required><UserTreeSelector v-model="selectedLeader" selection-mode="single" :scope-dept-code="form.deptCode"/></UFormField><div><p class="text-sm text-muted">所属部门</p><p class="mt-1">{{ departmentName }}</p></div><div><p class="text-sm text-muted">业务领域</p><p class="mt-1">{{ domainName }}</p></div><UFormField label="开始日期"><UInput v-model="form.startDate" type="date"/></UFormField><UFormField label="结束日期"><UInput v-model="form.endDate" type="date"/></UFormField><UFormField label="说明" class="sm:col-span-2"><UTextarea v-model="form.description"/></UFormField></div><div class="mt-5 flex justify-end"><UButton :loading="saving" :disabled="!form.name.trim()||!form.shortName.trim()||!form.leaderUid.trim()||!!nameError" @click="save">保存基本信息</UButton></div></UCard></section></template>
