<script setup lang="ts">
import{useAimsModule}from'../useAimsModule'
const route=useRoute(),router=useRouter(),{moduleUrl}=useAimsModule(),creating=computed(()=>Boolean(route.params.projectId)),projectId=ref(String(route.params.projectId||'')),itemId=computed(()=>String(route.params.id||'')),category=ref(''),milestones=ref<{id:number,name:string}[]>([]),loading=ref(true),saving=ref(false),error=ref(''),key=ref(''),version=ref(''),form=reactive({title:'',description:'',priority:'P2',assigneeUid:'',startDate:'',dueDate:'',estimatedHours:null as number|null,type:'task',tier:'matter',milestoneId:null as number|null})
const selected=computed({get:()=>form.assigneeUid?[form.assigneeUid]:[],set:(uids:string[])=>{form.assigneeUid=uids[0]||''}})
async function load(){try{if(!creating.value){const r=await $fetch<{data?:{editVersion?:string,editSnapshot?:Record<string,any>}}>(moduleUrl(`/api/v1/work-items/${itemId.value}`));const p=r.data?.editSnapshot;if(!p||!r.data?.editVersion)throw Error('工作项内容版本不可用');version.value=r.data.editVersion;projectId.value=String(p.project_id);Object.assign(form,{title:p.title||'',description:p.description||'',priority:p.priority||'P2',assigneeUid:p.assignee_uid||'',startDate:String(p.start_date||'').slice(0,10),dueDate:String(p.due_date||'').slice(0,10),estimatedHours:p.estimated_hours==null?null:Number(p.estimated_hours)})}const p=await $fetch<{data?:{category?:string}}>(moduleUrl(`/api/v1/projects/${projectId.value}`));category.value=p.data?.category||'';if(creating.value&&category.value!=='routine'){const r=await $fetch<{data?:{milestones?:{id:number,name:string}[]}}>(moduleUrl(`/api/v1/projects/${projectId.value}/plan`));milestones.value=r.data?.milestones||[]}}catch(e){error.value=e instanceof Error?e.message:'工作项暂不可用'}finally{loading.value=false}}
async function save(){saving.value=true;error.value='';key.value||=crypto.randomUUID();try{const input=creating.value?{...form,...(category.value==='routine'?{type:'task',tier:'matter',milestoneId:null}:{})}:{projectId:projectId.value,expectedVersion:version.value,title:form.title,description:form.description,priority:form.priority,assigneeUid:form.assigneeUid,startDate:form.startDate,dueDate:form.dueDate,estimatedHours:form.estimatedHours};const r=await $fetch<{code?:number,data?:{result?:{id?:string}}}>(moduleUrl(creating.value?`/api/v1/projects/${projectId.value}/work-items`:`/api/v1/work-items/${itemId.value}`),{method:creating.value?'POST':'PUT',headers:{'Idempotency-Key':key.value},body:input});if(r.code!==0||!r.data?.result?.id)throw Error('工作项操作回执无效');key.value='';await router.push(moduleUrl(`/work-items/${r.data.result.id}`))}catch(e){error.value=e instanceof Error?e.message:'保存失败，可使用相同操作标识重试'}finally{saving.value=false}}
onMounted(load)
</script>
<template><section class="mx-auto max-w-3xl space-y-5"><UButton :to="moduleUrl(creating?`/projects/${projectId}`:`/work-items/${itemId}`)" variant="link" color="neutral">返回</UButton><h1 class="text-2xl font-semibold">{{creating?'创建工作项':'编辑工作项基本信息'}}</h1><UAlert title="当前支持范围" description="支持创建及基本信息编辑；产品版本关联请使用详情页专用入口；状态流转、类型层级调整、父子结构与里程碑移动将在后续迁移。"/><UAlert v-if="error" color="error" title="操作失败" :description="error"/><USkeleton v-if="loading" class="h-64"/><UCard v-else><div class="grid gap-4 sm:grid-cols-2"><UFormField label="标题" required class="sm:col-span-2"><UInput v-model="form.title" class="w-full"/></UFormField><UFormField label="负责人"><UserTreeSelector v-model="selected" selection-mode="single"/></UFormField><UFormField label="优先级"><USelect v-model="form.priority" :items="['P0','P1','P2','P3']"/></UFormField><UFormField v-if="creating&&category!=='routine'" label="里程碑" required><USelectMenu v-model="form.milestoneId" :items="milestones.map(m=>({label:m.name,value:m.id}))" value-key="value"/></UFormField><UFormField label="开始日期"><UInput v-model="form.startDate" type="date"/></UFormField><UFormField label="截止日期"><UInput v-model="form.dueDate" type="date"/></UFormField><UFormField label="预计工时"><UInput v-model="form.estimatedHours" type="number" min="0"/></UFormField><UFormField label="说明" class="sm:col-span-2"><UTextarea v-model="form.description" class="w-full"/></UFormField></div><UButton class="mt-5" :loading="saving" :disabled="!form.title.trim()||(creating&&category!=='routine'&&!form.milestoneId)" @click="save">保存</UButton></UCard></section></template>
