-- Migration 029: Contract activation orchestration
-- Run in hzy_altoc or the target Altoc tenant database.
--
-- P1A adds contract-project links and recoverable activation jobs/steps.
-- It reuses the existing domain_event_outbox table for published domain
-- events instead of introducing a second outbox fact source.

CREATE TABLE IF NOT EXISTS contract_project_link (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  contract_id BIGINT NOT NULL COMMENT '合同ID',
  contract_line_id BIGINT DEFAULT NULL COMMENT '合同行ID',
  obligation_id BIGINT DEFAULT NULL COMMENT '履约义务ID',
  project_code VARCHAR(64) NOT NULL COMMENT 'Aims项目编号',
  project_name_snapshot VARCHAR(200) DEFAULT NULL COMMENT '项目名称快照',
  project_role VARCHAR(30) NOT NULL DEFAULT 'delivery' COMMENT '项目角色：primary/delivery/development/implementation/maintenance/operation/subcontract',
  plan_key VARCHAR(100) DEFAULT NULL COMMENT '履约启动项目计划键',
  line_codes_json JSON DEFAULT NULL COMMENT '覆盖合同行编码JSON',
  obligation_codes_json JSON DEFAULT NULL COMMENT '覆盖履约义务编码JSON',
  link_mode VARCHAR(30) NOT NULL DEFAULT 'created_from_contract' COMMENT '关联方式：created_from_contract/linked_existing',
  status VARCHAR(30) NOT NULL DEFAULT 'active' COMMENT '状态：planned/active/closed/cancelled',
  source_job_id BIGINT DEFAULT NULL COMMENT '来源编排作业ID',
  created_by VARCHAR(50) DEFAULT NULL COMMENT '创建人',
  updated_by VARCHAR(50) DEFAULT NULL COMMENT '更新人',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted_at DATETIME DEFAULT NULL COMMENT '软删除时间',
  UNIQUE KEY uk_contract_project_link (contract_id, project_code, project_role),
  INDEX idx_contract_project_contract (contract_id, status),
  INDEX idx_contract_project_plan (contract_id, plan_key),
  INDEX idx_contract_project_line (contract_line_id),
  INDEX idx_contract_project_obligation (obligation_id),
  INDEX idx_contract_project_code (project_code),
  INDEX idx_contract_project_source_job (source_job_id),
  CONSTRAINT fk_contract_project_contract FOREIGN KEY (contract_id) REFERENCES contract(id) ON DELETE CASCADE,
  CONSTRAINT fk_contract_project_line FOREIGN KEY (contract_line_id) REFERENCES contract_line(id) ON DELETE SET NULL,
  CONSTRAINT fk_contract_project_obligation FOREIGN KEY (obligation_id) REFERENCES contract_obligation(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='合同项目关联表';

CREATE TABLE IF NOT EXISTS contract_orchestration_job (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  code VARCHAR(64) NOT NULL COMMENT '编排作业编号',
  job_type VARCHAR(50) NOT NULL DEFAULT 'activation' COMMENT '作业类型：activation/contract_change',
  contract_id BIGINT NOT NULL COMMENT '合同ID',
  source_contract_code VARCHAR(64) NOT NULL COMMENT '来源合同编号快照',
  idempotency_key VARCHAR(200) NOT NULL COMMENT '幂等键',
  requested_by VARCHAR(50) DEFAULT NULL COMMENT '请求人',
  status VARCHAR(30) NOT NULL DEFAULT 'planned' COMMENT '状态：planned/running/partially_failed/completed/cancelled',
  tenant_code VARCHAR(100) DEFAULT NULL COMMENT '租户编码快照',
  deployment_code VARCHAR(100) DEFAULT NULL COMMENT '部署编码快照',
  feature_flag_snapshot JSON DEFAULT NULL COMMENT '特性开关快照',
  plan_snapshot_json JSON NOT NULL COMMENT '启动计划快照',
  started_at DATETIME DEFAULT NULL COMMENT '开始时间',
  finished_at DATETIME DEFAULT NULL COMMENT '结束时间',
  cancel_reason VARCHAR(500) DEFAULT NULL COMMENT '取消原因',
  last_error TEXT DEFAULT NULL COMMENT '最后错误',
  created_by VARCHAR(50) DEFAULT NULL COMMENT '创建人',
  updated_by VARCHAR(50) DEFAULT NULL COMMENT '更新人',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted_at DATETIME DEFAULT NULL COMMENT '软删除时间',
  UNIQUE KEY uk_contract_orchestration_job_code (code),
  UNIQUE KEY uk_contract_orchestration_idempotency (idempotency_key),
  INDEX idx_contract_orchestration_contract (contract_id, created_at),
  INDEX idx_contract_orchestration_status (status, updated_at),
  INDEX idx_contract_orchestration_type (job_type),
  CONSTRAINT fk_contract_orchestration_contract FOREIGN KEY (contract_id) REFERENCES contract(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='合同编排作业表';

CREATE TABLE IF NOT EXISTS contract_orchestration_step (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  job_id BIGINT NOT NULL COMMENT '编排作业ID',
  contract_id BIGINT NOT NULL COMMENT '合同ID',
  step_key VARCHAR(100) NOT NULL COMMENT '步骤稳定键',
  step_name VARCHAR(100) NOT NULL COMMENT '步骤名称',
  sort_no INT NOT NULL DEFAULT 0 COMMENT '排序',
  depends_on_step_keys JSON DEFAULT NULL COMMENT '前置步骤键',
  idempotency_key VARCHAR(240) NOT NULL COMMENT '步骤幂等键',
  target_app VARCHAR(50) NOT NULL COMMENT '目标应用',
  target_action VARCHAR(100) NOT NULL COMMENT '目标动作',
  request_snapshot JSON NOT NULL COMMENT '请求快照',
  result_snapshot JSON DEFAULT NULL COMMENT '结果快照',
  status VARCHAR(30) NOT NULL DEFAULT 'planned' COMMENT '状态：planned/running/succeeded/failed/skipped/cancelled/needs_manual_action',
  retry_count INT NOT NULL DEFAULT 0 COMMENT '重试次数',
  max_retries INT NOT NULL DEFAULT 3 COMMENT '最大重试次数',
  last_error TEXT DEFAULT NULL COMMENT '最后错误',
  next_retry_at DATETIME DEFAULT NULL COMMENT '下次重试时间',
  locked_by VARCHAR(100) DEFAULT NULL COMMENT '执行锁持有人',
  locked_until DATETIME DEFAULT NULL COMMENT '执行锁过期时间',
  heartbeat_at DATETIME DEFAULT NULL COMMENT '执行心跳时间',
  created_by VARCHAR(50) DEFAULT NULL COMMENT '创建人',
  updated_by VARCHAR(50) DEFAULT NULL COMMENT '更新人',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted_at DATETIME DEFAULT NULL COMMENT '软删除时间',
  UNIQUE KEY uk_contract_orchestration_step (job_id, step_key),
  INDEX idx_contract_orchestration_step_idempotency (idempotency_key),
  INDEX idx_contract_orchestration_step_contract (contract_id, sort_no),
  INDEX idx_contract_orchestration_step_status (status, next_retry_at),
  INDEX idx_contract_orchestration_step_target (target_app, target_action),
  INDEX idx_contract_orchestration_step_lock (locked_until),
  CONSTRAINT fk_contract_orchestration_step_job FOREIGN KEY (job_id) REFERENCES contract_orchestration_job(id) ON DELETE CASCADE,
  CONSTRAINT fk_contract_orchestration_step_contract FOREIGN KEY (contract_id) REFERENCES contract(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='合同编排步骤表';
