-- Migration 030: Contract delivery asset placeholders and service agreements
-- Run in hzy_altoc or the target Altoc tenant database.
--
-- These tables are Altoc-side planning/read models for P1-3/P1-4 while
-- Assets customer-delivery-assets contracts are not frozen. They do not
-- replace the Assets asset master.

CREATE TABLE IF NOT EXISTS contract_delivery_asset_plan (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  code VARCHAR(64) NOT NULL COMMENT '计划交付资产编号',
  contract_id BIGINT NOT NULL COMMENT '合同ID',
  contract_line_id BIGINT DEFAULT NULL COMMENT '合同行ID',
  obligation_id BIGINT DEFAULT NULL COMMENT '履约义务ID',
  customer_code VARCHAR(100) DEFAULT NULL COMMENT '客户编码',
  name VARCHAR(200) NOT NULL COMMENT '计划资产名称',
  product_code VARCHAR(100) DEFAULT NULL COMMENT '产品编码',
  product_version VARCHAR(100) DEFAULT NULL COMMENT '产品版本',
  catalog_item_code VARCHAR(100) DEFAULT NULL COMMENT '目录项编码',
  product_origin VARCHAR(30) DEFAULT NULL COMMENT '产品来源',
  source_contract_code VARCHAR(64) NOT NULL COMMENT '来源合同编号',
  source_contract_line_code VARCHAR(64) DEFAULT NULL COMMENT '来源合同行编号',
  source_obligation_code VARCHAR(64) DEFAULT NULL COMMENT '来源义务编号',
  source_project_code VARCHAR(64) DEFAULT NULL COMMENT '来源项目编号',
  external_asset_code VARCHAR(100) DEFAULT NULL COMMENT 'Assets资产编码',
  deployment_mode VARCHAR(50) DEFAULT NULL COMMENT '部署模式',
  instance_key VARCHAR(100) DEFAULT NULL COMMENT '实例键',
  tenant_key VARCHAR(100) DEFAULT NULL COMMENT '租户键',
  environment_code VARCHAR(100) DEFAULT NULL COMMENT '环境编码',
  license_model VARCHAR(50) DEFAULT NULL COMMENT '授权模型',
  license_quantity DECIMAL(18,4) DEFAULT NULL COMMENT '授权数量',
  capacity DECIMAL(18,4) DEFAULT NULL COMMENT '容量',
  unit VARCHAR(30) DEFAULT NULL COMMENT '单位',
  status VARCHAR(30) NOT NULL DEFAULT 'planned' COMMENT '状态：planned/provisioning/delivered/online/accepted/suspended/expired/terminated',
  planned_delivery_at DATETIME DEFAULT NULL COMMENT '计划交付时间',
  delivered_at DATETIME DEFAULT NULL COMMENT '交付时间',
  go_live_at DATETIME DEFAULT NULL COMMENT '上线时间',
  accepted_at DATETIME DEFAULT NULL COMMENT '验收时间',
  expired_at DATETIME DEFAULT NULL COMMENT '到期时间',
  terminated_at DATETIME DEFAULT NULL COMMENT '终止时间',
  warranty_start_at DATETIME DEFAULT NULL COMMENT '质保开始时间',
  warranty_end_at DATETIME DEFAULT NULL COMMENT '质保结束时间',
  support_expiry_at DATETIME DEFAULT NULL COMMENT '支持到期时间',
  source_job_id BIGINT DEFAULT NULL COMMENT '来源编排作业ID',
  created_by VARCHAR(50) DEFAULT NULL COMMENT '创建人',
  updated_by VARCHAR(50) DEFAULT NULL COMMENT '更新人',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted_at DATETIME DEFAULT NULL COMMENT '软删除时间',
  UNIQUE KEY uk_contract_delivery_asset_plan_code (code),
  UNIQUE KEY uk_contract_delivery_asset_plan_line (contract_id, contract_line_id, instance_key),
  INDEX idx_contract_delivery_asset_contract (contract_id, status),
  INDEX idx_contract_delivery_asset_line (contract_line_id),
  INDEX idx_contract_delivery_asset_customer (customer_code),
  INDEX idx_contract_delivery_asset_external (external_asset_code),
  INDEX idx_contract_delivery_asset_source_job (source_job_id),
  CONSTRAINT fk_contract_delivery_asset_contract FOREIGN KEY (contract_id) REFERENCES contract(id) ON DELETE CASCADE,
  CONSTRAINT fk_contract_delivery_asset_line FOREIGN KEY (contract_line_id) REFERENCES contract_line(id) ON DELETE SET NULL,
  CONSTRAINT fk_contract_delivery_asset_obligation FOREIGN KEY (obligation_id) REFERENCES contract_obligation(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='合同计划交付资产表';

CREATE TABLE IF NOT EXISTS service_agreement (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  code VARCHAR(64) NOT NULL COMMENT '服务协议编号',
  contract_id BIGINT NOT NULL COMMENT '合同ID',
  contract_line_id BIGINT DEFAULT NULL COMMENT '合同行ID',
  customer_code VARCHAR(100) DEFAULT NULL COMMENT '客户编码',
  name VARCHAR(200) NOT NULL COMMENT '服务协议名称',
  service_level VARCHAR(50) DEFAULT NULL COMMENT '服务等级',
  service_start_date DATE DEFAULT NULL COMMENT '服务开始日期',
  service_end_date DATE DEFAULT NULL COMMENT '服务结束日期',
  service_window VARCHAR(100) DEFAULT NULL COMMENT '服务窗口',
  billing_mode VARCHAR(50) DEFAULT NULL COMMENT '计费方式',
  renewal_policy VARCHAR(100) DEFAULT NULL COMMENT '续约策略',
  response_minutes INT DEFAULT NULL COMMENT '默认响应时限(分钟)',
  resolution_minutes INT DEFAULT NULL COMMENT '默认解决时限(分钟)',
  included_quota DECIMAL(10,2) DEFAULT NULL COMMENT '包含工单额度',
  quota_unit VARCHAR(30) DEFAULT NULL COMMENT '额度单位：ticket/hour/day',
  consumed_quota DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '已消耗额度',
  renewal_remind_at DATE DEFAULT NULL COMMENT '续约提醒日期',
  status VARCHAR(30) NOT NULL DEFAULT 'planned' COMMENT '状态：planned/active/suspended/expired/terminated/cancelled',
  owner_user_id VARCHAR(50) DEFAULT NULL COMMENT '负责人',
  maintenance_contract_id BIGINT DEFAULT NULL COMMENT '来源维保合同ID',
  source_job_id BIGINT DEFAULT NULL COMMENT '来源编排作业ID',
  created_by VARCHAR(50) DEFAULT NULL COMMENT '创建人',
  updated_by VARCHAR(50) DEFAULT NULL COMMENT '更新人',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted_at DATETIME DEFAULT NULL COMMENT '软删除时间',
  UNIQUE KEY uk_service_agreement_code (code),
  UNIQUE KEY uk_service_agreement_line (contract_id, contract_line_id),
  INDEX idx_service_agreement_contract (contract_id, status),
  INDEX idx_service_agreement_customer (customer_code),
  INDEX idx_service_agreement_line (contract_line_id),
  INDEX idx_service_agreement_maintenance (maintenance_contract_id),
  INDEX idx_service_agreement_renewal (renewal_remind_at, status),
  INDEX idx_service_agreement_source_job (source_job_id),
  CONSTRAINT fk_service_agreement_contract FOREIGN KEY (contract_id) REFERENCES contract(id) ON DELETE CASCADE,
  CONSTRAINT fk_service_agreement_line FOREIGN KEY (contract_line_id) REFERENCES contract_line(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='服务协议表';

CREATE TABLE IF NOT EXISTS service_agreement_asset (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  service_agreement_id BIGINT NOT NULL COMMENT '服务协议ID',
  delivery_asset_code VARCHAR(100) NOT NULL COMMENT '计划或正式交付资产编码',
  coverage_type VARCHAR(50) NOT NULL DEFAULT 'planned_asset' COMMENT '覆盖类型：planned_asset/customer_delivery_asset/pending_asset/legacy_delivery',
  coverage_start_date DATE DEFAULT NULL COMMENT '覆盖开始日期',
  coverage_end_date DATE DEFAULT NULL COMMENT '覆盖结束日期',
  included TINYINT NOT NULL DEFAULT 1 COMMENT '是否包含',
  exclusion_note VARCHAR(500) DEFAULT NULL COMMENT '排除说明',
  created_by VARCHAR(50) DEFAULT NULL COMMENT '创建人',
  updated_by VARCHAR(50) DEFAULT NULL COMMENT '更新人',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted_at DATETIME DEFAULT NULL COMMENT '软删除时间',
  UNIQUE KEY uk_service_agreement_asset (service_agreement_id, delivery_asset_code),
  INDEX idx_service_agreement_asset_code (delivery_asset_code),
  CONSTRAINT fk_service_agreement_asset_agreement FOREIGN KEY (service_agreement_id) REFERENCES service_agreement(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='服务协议覆盖资产表';
