-- Candidate only. Runtime stopped, migration lock, reviewed plan and backup required.
-- Prefer ForAltocSales Plan/Apply/Verify/Rollback; do not execute this file blindly.
CREATE TABLE altoc_opportunity_stage (
    id                  BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    code                VARCHAR(50) NOT NULL COMMENT '阶段编码',
    pipeline_code       VARCHAR(50) NOT NULL DEFAULT 'default' COMMENT '销售管线模板：default/solution/tog_project',
    name                VARCHAR(100) NOT NULL COMMENT '阶段名称',
    stage_kind          VARCHAR(30) DEFAULT 'normal' COMMENT '阶段类型：normal/won/lost/paused',
    sort_no             INT DEFAULT 0 COMMENT '排序号',
    win_rate            DECIMAL(5,2) DEFAULT 0.00 COMMENT '默认赢率(%)',
    is_closed           TINYINT DEFAULT 0 COMMENT '是否关闭阶段：1是 0否',
    is_won              TINYINT DEFAULT 0 COMMENT '是否赢单阶段：1是 0否',
    is_lost             TINYINT DEFAULT 0 COMMENT '是否输单阶段：1是 0否',
    required_fields_json JSON DEFAULT NULL COMMENT '必填字段JSON',
    exit_criteria_json  JSON DEFAULT NULL COMMENT '退出标准JSON',
    is_enabled          TINYINT DEFAULT 1 COMMENT '是否启用：1启用 0禁用',
    created_at          DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at          DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',

    row_version INT UNSIGNED NOT NULL DEFAULT 1,
    UNIQUE KEY uk_code (code),
    INDEX idx_pipeline_sort (pipeline_code, sort_no, id),
    INDEX idx_stage_kind (stage_kind)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商机阶段配置表';

CREATE TABLE altoc_lead (
    id                      BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    code                    VARCHAR(30) NOT NULL COMMENT '线索编号(LE-xxxxxx)',
    name                    VARCHAR(200) NOT NULL COMMENT '线索名称',
    org_name                VARCHAR(200) DEFAULT NULL COMMENT '组织/公司名称',
    source_type             VARCHAR(50) DEFAULT NULL COMMENT '来源类型：marketing/referral/visit/tender/partner/website/other',
    source_detail           VARCHAR(200) DEFAULT NULL COMMENT '来源详情',
    need_summary            VARCHAR(1000) DEFAULT NULL COMMENT '真实需求或客户问题摘要',
    project_type            VARCHAR(30) DEFAULT NULL COMMENT '项目类型：tob/tog/renewal/upsell/channel',
    budget_status           VARCHAR(30) DEFAULT NULL COMMENT '预算状态：unknown/applying/approved/allocated',
    estimated_budget        DECIMAL(18,2) DEFAULT NULL COMMENT '初步预算',
    procurement_mode        VARCHAR(50) DEFAULT NULL COMMENT '采购方式：direct/competitive_consultation/open_tender/framework/other',
    expected_procurement_date DATE DEFAULT NULL COMMENT '预计采购时间',
    source_evidence_url     VARCHAR(500) DEFAULT NULL COMMENT '来源证据链接',
    qualification_result    VARCHAR(30) DEFAULT NULL COMMENT '资格判定：passed/nurture/invalid/duplicate',
    qualification_reason_code VARCHAR(50) DEFAULT NULL COMMENT '资格判定原因编码',
    contact_name            VARCHAR(50) DEFAULT NULL COMMENT '联系人姓名',
    contact_mobile          VARCHAR(30) DEFAULT NULL COMMENT '联系人手机',
    contact_email           VARCHAR(100) DEFAULT NULL COMMENT '联系人邮箱',
    status                  VARCHAR(20) DEFAULT 'new' COMMENT '状态：new/pending_assign/following/converted/closed_invalid',
    owner_uid           VARCHAR(50) DEFAULT NULL COMMENT '负责人',
    owner_dept_code         VARCHAR(50) DEFAULT NULL COMMENT '归属部门编码',
    score                   INT DEFAULT NULL COMMENT '线索评分(0-100，可由规则或AI生成)',
    next_action             VARCHAR(500) DEFAULT NULL COMMENT '下一步动作',
    next_action_due_at      DATETIME DEFAULT NULL COMMENT '下一步动作截止时间',
    last_follow_up_at       DATETIME DEFAULT NULL COMMENT '最近跟进时间',
    invalid_reason_code     VARCHAR(50) DEFAULT NULL COMMENT '结构化无效原因编码',
    invalid_reason          VARCHAR(500) DEFAULT NULL COMMENT '无效原因',
    converted_customer_id   BIGINT UNSIGNED DEFAULT NULL COMMENT '转化后客户ID',
    converted_opportunity_id BIGINT UNSIGNED DEFAULT NULL COMMENT '转化后商机ID',
    converted_at            DATETIME DEFAULT NULL COMMENT '转化时间',
    remark                  VARCHAR(500) DEFAULT NULL COMMENT '备注',
    created_by              VARCHAR(50) DEFAULT NULL COMMENT '创建人',
    updated_by              VARCHAR(50) DEFAULT NULL COMMENT '更新人',
    created_at              DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at              DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at              DATETIME DEFAULT NULL COMMENT '软删除时间',

    row_version INT UNSIGNED NOT NULL DEFAULT 1,
    UNIQUE KEY uk_code (code),
    INDEX idx_status (status),
    INDEX idx_owner_uid (owner_uid),
    INDEX idx_source_type (source_type),
    INDEX idx_qualification_result (qualification_result),
    INDEX idx_expected_procurement_date (expected_procurement_date),
    INDEX idx_invalid_reason_code (invalid_reason_code),
    INDEX idx_last_follow_up_at (last_follow_up_at),
    INDEX idx_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='线索表';

CREATE TABLE altoc_opportunity (
    id                          BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    code                        VARCHAR(30) NOT NULL COMMENT '商机编号(OP-xxxxxx)',
    name                        VARCHAR(200) NOT NULL COMMENT '商机名称',
    customer_id                 BIGINT UNSIGNED NOT NULL COMMENT '所属客户ID',
    lead_id                     BIGINT UNSIGNED DEFAULT NULL COMMENT '来源线索ID',
    source_type                 VARCHAR(50) DEFAULT NULL COMMENT '商机来源：customer_visit/existing_customer_revisit/telemarketing/online_promotion/referral/other',
    source_detail               VARCHAR(500) DEFAULT NULL COMMENT '商机来源详细说明',
    stage_id                    BIGINT UNSIGNED NOT NULL COMMENT '当前阶段ID',
    forecast_category           VARCHAR(20) DEFAULT 'pipeline' COMMENT '预测分类：pipeline/best_case/commit',
    status                      VARCHAR(20) DEFAULT 'active' COMMENT '状态：active/won/lost/paused',
    amount_tax_inclusive        DECIMAL(18,2) DEFAULT NULL COMMENT '预计金额(含税)',
    amount_tax_exclusive        DECIMAL(18,2) DEFAULT NULL COMMENT '预计金额(不含税)',
    currency_code               VARCHAR(10) DEFAULT 'CNY' COMMENT '币种',
    expected_sign_date          DATE DEFAULT NULL COMMENT '预计签约日期',
    expected_payment_date       DATE DEFAULT NULL COMMENT '预计回款日期',
    win_rate                    DECIMAL(5,2) DEFAULT NULL COMMENT '赢率(%)',
    owner_uid               VARCHAR(50) NOT NULL COMMENT '商机负责人',
    owner_dept_code             VARCHAR(50) DEFAULT NULL COMMENT '归属部门编码',
    pre_sales_user_id           VARCHAR(50) DEFAULT NULL COMMENT '售前负责人',
    delivery_user_id            VARCHAR(50) DEFAULT NULL COMMENT '交付负责人',
    next_action                 VARCHAR(500) DEFAULT NULL COMMENT '下一步动作',
    next_action_due_at          DATETIME DEFAULT NULL COMMENT '下一步动作截止时间',
    last_follow_up_at           DATETIME DEFAULT NULL COMMENT '最近跟进时间',
    risk_level                  VARCHAR(20) DEFAULT NULL COMMENT '风险等级：high/medium/low',
    risk_reason                 VARCHAR(500) DEFAULT NULL COMMENT '风险原因',
    competitor_info             TEXT DEFAULT NULL COMMENT '竞品信息',
    key_contact_complete_rate   DECIMAL(5,2) DEFAULT NULL COMMENT '关键人完整度(%)',
    won_at                      DATETIME DEFAULT NULL COMMENT '赢单时间',
    won_reason_code             VARCHAR(50) DEFAULT NULL COMMENT '结构化赢单原因编码',
    won_reason                  VARCHAR(500) DEFAULT NULL COMMENT '赢单原因',
    lost_at                     DATETIME DEFAULT NULL COMMENT '输单时间',
    lost_reason_code            VARCHAR(50) DEFAULT NULL COMMENT '结构化输单原因编码',
    lost_reason                 VARCHAR(500) DEFAULT NULL COMMENT '输单原因',
    pause_reason_code           VARCHAR(50) DEFAULT NULL COMMENT '结构化暂停原因编码',
    pause_reason                VARCHAR(500) DEFAULT NULL COMMENT '暂停原因',
    remark                      VARCHAR(500) DEFAULT NULL COMMENT '备注',
    version_no                  INT DEFAULT 1 COMMENT '版本号',
    last_status_changed_at      DATETIME DEFAULT NULL COMMENT '最后状态变更时间',
    last_status_changed_by      VARCHAR(50) DEFAULT NULL COMMENT '最后状态变更人',
    created_by                  VARCHAR(50) DEFAULT NULL COMMENT '创建人',
    updated_by                  VARCHAR(50) DEFAULT NULL COMMENT '更新人',
    created_at                  DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at                  DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at                  DATETIME DEFAULT NULL COMMENT '软删除时间',

    row_version INT UNSIGNED NOT NULL DEFAULT 1,
    UNIQUE KEY uk_code (code),
    UNIQUE KEY uk_opportunity_lead_id (lead_id),
    INDEX idx_customer_id (customer_id),
    INDEX idx_source_type (source_type),
    INDEX idx_owner_uid (owner_uid),
    INDEX idx_stage_id (stage_id),
    INDEX idx_forecast_category (forecast_category),
    INDEX idx_expected_sign_date (expected_sign_date),
    INDEX idx_status (status),
    INDEX idx_last_follow_up_at (last_follow_up_at),
    INDEX idx_won_reason_code (won_reason_code),
    INDEX idx_lost_reason_code (lost_reason_code),
    INDEX idx_pause_reason_code (pause_reason_code),
    INDEX idx_deleted_at (deleted_at),
    CONSTRAINT fk_opp_customer FOREIGN KEY (customer_id) REFERENCES altoc_customer(id),
    CONSTRAINT fk_opp_stage FOREIGN KEY (stage_id) REFERENCES altoc_opportunity_stage(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商机表';

CREATE TABLE altoc_lead_conversion (
    id                          BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    lead_id                     BIGINT UNSIGNED NOT NULL COMMENT '线索ID',
    customer_id                 BIGINT UNSIGNED NOT NULL COMMENT '转化客户ID',
    contact_id                  BIGINT UNSIGNED DEFAULT NULL COMMENT '转化联系人ID',
    opportunity_id              BIGINT UNSIGNED NOT NULL COMMENT '转化商机ID',
    converted_by                VARCHAR(50) DEFAULT NULL COMMENT '转化人',
    converted_at                DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '转化时间',
    idempotency_key             VARCHAR(100) DEFAULT NULL COMMENT '幂等键',
    conversion_snapshot_json    JSON DEFAULT NULL COMMENT '转化请求与结果快照',

    row_version INT UNSIGNED NOT NULL DEFAULT 1,
    UNIQUE KEY uk_lead_conversion_lead (lead_id),
    UNIQUE KEY uk_lead_conversion_idempotency (idempotency_key),
    INDEX idx_customer_id (customer_id),
    INDEX idx_contact_id (contact_id),
    INDEX idx_opportunity_id (opportunity_id),
    CONSTRAINT fk_lc_lead FOREIGN KEY (lead_id) REFERENCES altoc_lead(id),
    CONSTRAINT fk_lc_customer FOREIGN KEY (customer_id) REFERENCES altoc_customer(id),
    CONSTRAINT fk_lc_contact FOREIGN KEY (contact_id) REFERENCES altoc_contact(id),
    CONSTRAINT fk_lc_opportunity FOREIGN KEY (opportunity_id) REFERENCES altoc_opportunity(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='线索转化记录表';

CREATE TABLE altoc_opportunity_contact_role (
    id                  BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    opportunity_id      BIGINT UNSIGNED NOT NULL COMMENT '商机ID',
    contact_id          BIGINT UNSIGNED NOT NULL COMMENT '联系人ID',
    role                VARCHAR(50) NOT NULL COMMENT '角色：decision_maker/economic_buyer/sponsor/procurement/technical_influencer/end_user/competitor_supporter',
    influence_level     VARCHAR(20) DEFAULT 'medium' COMMENT '影响力：high/medium/low',
    attitude            VARCHAR(20) DEFAULT 'neutral' COMMENT '态度：supportive/neutral/resistant/unknown',
    is_primary          TINYINT DEFAULT 0 COMMENT '是否主要联系人：1是 0否',
    remark              VARCHAR(500) DEFAULT NULL COMMENT '备注',
    created_by          VARCHAR(50) DEFAULT NULL COMMENT '创建人',
    updated_by          VARCHAR(50) DEFAULT NULL COMMENT '更新人',
    created_at          DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at          DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at          DATETIME DEFAULT NULL COMMENT '软删除时间',

    row_version INT UNSIGNED NOT NULL DEFAULT 1,
    UNIQUE KEY uk_opportunity_contact (opportunity_id, contact_id),
    INDEX idx_opportunity_id (opportunity_id),
    INDEX idx_contact_id (contact_id),
    INDEX idx_role (role),
    INDEX idx_is_primary (is_primary),
    CONSTRAINT fk_ocr_opportunity FOREIGN KEY (opportunity_id) REFERENCES altoc_opportunity(id) ,
    CONSTRAINT fk_ocr_contact FOREIGN KEY (contact_id) REFERENCES altoc_contact(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商机联系人角色表';

CREATE TABLE altoc_opportunity_stage_log (
    id              BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    opportunity_id  BIGINT UNSIGNED NOT NULL COMMENT '商机ID',
    from_stage_id   BIGINT UNSIGNED DEFAULT NULL COMMENT '原阶段ID',
    to_stage_id     BIGINT UNSIGNED NOT NULL COMMENT '目标阶段ID',
    changed_by      VARCHAR(50) NOT NULL COMMENT '操作人',
    changed_at      DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '变更时间',
    change_reason   VARCHAR(500) DEFAULT NULL COMMENT '变更原因',
    amount_snapshot DECIMAL(18,2) DEFAULT NULL COMMENT '变更后金额快照',
    forecast_category_snapshot VARCHAR(20) DEFAULT NULL COMMENT '变更后预测分类快照',
    expected_sign_date_snapshot DATE DEFAULT NULL COMMENT '变更后预计签约日期快照',
    win_rate_snapshot DECIMAL(5,2) DEFAULT NULL COMMENT '变更后赢率快照',
    version_no      INT DEFAULT NULL COMMENT '变更后商机版本号',

    row_version INT UNSIGNED NOT NULL DEFAULT 1,
    INDEX idx_opportunity_id (opportunity_id),
    INDEX idx_changed_at (changed_at),
    CONSTRAINT fk_stage_log_opp FOREIGN KEY (opportunity_id) REFERENCES altoc_opportunity(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商机阶段流转日志表';

CREATE TABLE altoc_sales_activity (
    id                  BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    code                VARCHAR(30) NOT NULL COMMENT '活动编号',
    activity_type       VARCHAR(20) NOT NULL COMMENT '活动类型：visit/call/demo/meeting/tender/memo',
    subject             VARCHAR(200) NOT NULL COMMENT '活动主题',
    lead_id             BIGINT UNSIGNED DEFAULT NULL COMMENT '关联线索ID',
    customer_id         BIGINT UNSIGNED DEFAULT NULL COMMENT '关联客户ID',
    contact_id          BIGINT UNSIGNED DEFAULT NULL COMMENT '关联联系人ID',
    opportunity_id      BIGINT UNSIGNED DEFAULT NULL COMMENT '关联商机ID',
    activity_at         DATETIME NOT NULL COMMENT '活动时间',
    participants_json   JSON DEFAULT NULL COMMENT '参与人JSON',
    content             TEXT DEFAULT NULL COMMENT '活动内容/纪要',
    result_summary      VARCHAR(500) DEFAULT NULL COMMENT '结果摘要',
    next_action         VARCHAR(500) DEFAULT NULL COMMENT '下一步动作',
    next_action_due_at  DATETIME DEFAULT NULL COMMENT '下一步截止时间',
    owner_uid       VARCHAR(50) NOT NULL COMMENT '记录人',
    status              VARCHAR(20) DEFAULT 'active' COMMENT '状态：active/canceled',
    created_by          VARCHAR(50) DEFAULT NULL COMMENT '创建人',
    updated_by          VARCHAR(50) DEFAULT NULL COMMENT '更新人',
    created_at          DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at          DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at          DATETIME DEFAULT NULL COMMENT '软删除时间',

    row_version INT UNSIGNED NOT NULL DEFAULT 1,
    UNIQUE KEY uk_code (code),
    INDEX idx_lead_id (lead_id),
    INDEX idx_customer_id (customer_id),
    INDEX idx_opportunity_id (opportunity_id),
    INDEX idx_owner_uid (owner_uid),
    INDEX idx_activity_at (activity_at),
    CONSTRAINT fk_activity_lead FOREIGN KEY (lead_id) REFERENCES altoc_lead(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='销售活动表';

CREATE TABLE altoc_sales_task (
    id                  BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    code                VARCHAR(30) NOT NULL COMMENT '任务编号',
    name                VARCHAR(200) NOT NULL COMMENT '任务名称',
    related_type        VARCHAR(30) DEFAULT NULL COMMENT '关联对象类型：customer/opportunity/lead/contract/quotation',
    related_id          BIGINT UNSIGNED DEFAULT NULL COMMENT '关联对象ID',
    assignee_uid    VARCHAR(50) NOT NULL COMMENT '责任人',
    due_at              DATETIME DEFAULT NULL COMMENT '截止时间',
    status              VARCHAR(20) DEFAULT 'todo' COMMENT '状态：todo/doing/done/canceled/overdue',
    priority            VARCHAR(10) DEFAULT 'medium' COMMENT '优先级：high/medium/low',
    content             TEXT DEFAULT NULL COMMENT '任务描述',
    completed_at        DATETIME DEFAULT NULL COMMENT '完成时间',
    created_by          VARCHAR(50) DEFAULT NULL COMMENT '创建人',
    updated_by          VARCHAR(50) DEFAULT NULL COMMENT '更新人',
    created_at          DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at          DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at          DATETIME DEFAULT NULL COMMENT '软删除时间',

    row_version INT UNSIGNED NOT NULL DEFAULT 1,
    UNIQUE KEY uk_code (code),
    INDEX idx_assignee_uid (assignee_uid),
    INDEX idx_status (status),
    INDEX idx_due_at (due_at),
    INDEX idx_related (related_type, related_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='销售任务表';
