-- Candidate only; stage initialization needs a separately approved installation window.
-- New empty B2 stage table only; stop if any row already exists. Do not overwrite existing pipeline configuration.
INSERT INTO altoc_opportunity_stage (code, pipeline_code, stage_kind, name, sort_no, win_rate, is_closed, is_won, is_lost, required_fields_json, exit_criteria_json) VALUES
('initial_contact', 'default', 'normal', '初步接触', 1, 10.00, 0, 0, 0, NULL, '{"description": "确认客户有初步需求意向并安排下一步", "fields": ["next_action", "next_action_due_at"]}'),
('requirement_confirmed', 'default', 'normal', '需求确认', 2, 25.00, 0, 0, 0, '["customer_id", "amount_tax_inclusive"]', '{"description": "客户需求已明确，可以输出方案", "fields": ["amount_tax_inclusive", "next_action", "next_action_due_at"]}'),
('proposal_quotation', 'default', 'normal', '方案报价', 3, 50.00, 0, 0, 0, '["amount_tax_inclusive", "competitor_info"]', '{"description": "方案/报价已提交客户并约定反馈", "fields": ["amount_tax_inclusive", "competitor_info", "next_action", "next_action_due_at"]}'),
('negotiation', 'default', 'normal', '商务谈判', 4, 70.00, 0, 0, 0, '["amount_tax_inclusive", "expected_sign_date"]', '{"description": "完成商务条件谈判并明确签约计划", "fields": ["amount_tax_inclusive", "expected_sign_date", "next_action", "next_action_due_at"]}'),
('pending_sign', 'default', 'normal', '待签约', 5, 90.00, 0, 0, 0, '["amount_tax_inclusive", "expected_sign_date"]', '{"description": "合同条款已确认，等待签署", "fields": ["amount_tax_inclusive", "expected_sign_date"]}'),
('won', 'default', 'won', '赢单', 6, 100.00, 1, 1, 0, '["amount_tax_inclusive", "expected_sign_date", "won_reason_code", "won_reason"]', NULL),
('lost', 'default', 'lost', '输单', 7, 0.00, 1, 0, 1, '["lost_reason_code", "lost_reason", "competitor_info"]', NULL),
('paused', 'default', 'paused', '暂停', 8, 0.00, 0, 0, 0, '["pause_reason_code", "pause_reason"]', NULL),
('solution_discovery', 'solution', 'normal', '线索确认', 1, 10.00, 0, 0, 0, NULL, '{"description": "确认客户业务痛点、预算可能性和下一步调研安排", "fields": ["next_action", "next_action_due_at"]}'),
('solution_requirements', 'solution', 'normal', '需求调研', 2, 25.00, 0, 0, 0, NULL, '{"description": "完成关键干系人访谈并形成需求范围", "fields": ["next_action", "next_action_due_at"]}'),
('solution_design', 'solution', 'normal', '方案设计', 3, 45.00, 0, 0, 0, '["amount_tax_inclusive", "expected_sign_date"]', '{"description": "完成方案、范围和初步报价假设", "fields": ["amount_tax_inclusive", "expected_sign_date", "next_action", "next_action_due_at"]}'),
('solution_poc', 'solution', 'normal', 'POC/试点', 4, 60.00, 0, 0, 0, '["amount_tax_inclusive", "competitor_info"]', '{"description": "完成验证计划或试点反馈，明确成败标准", "fields": ["competitor_info", "next_action", "next_action_due_at"]}'),
('solution_negotiation', 'solution', 'normal', '商务谈判', 5, 75.00, 0, 0, 0, '["amount_tax_inclusive", "expected_sign_date"]', '{"description": "商务条件、范围和实施节奏已进入谈判", "fields": ["amount_tax_inclusive", "expected_sign_date", "next_action", "next_action_due_at"]}'),
('solution_pending_sign', 'solution', 'normal', '待签约', 6, 90.00, 0, 0, 0, '["amount_tax_inclusive", "expected_sign_date"]', '{"description": "合同条款已确认，等待签署", "fields": ["amount_tax_inclusive", "expected_sign_date"]}'),
('solution_won', 'solution', 'won', '赢单', 7, 100.00, 1, 1, 0, '["amount_tax_inclusive", "expected_sign_date", "won_reason_code", "won_reason"]', NULL),
('solution_lost', 'solution', 'lost', '输单', 8, 0.00, 1, 0, 1, '["lost_reason_code", "lost_reason", "competitor_info"]', NULL),
('solution_paused', 'solution', 'paused', '暂停', 9, 0.00, 0, 0, 0, '["pause_reason_code", "pause_reason"]', NULL),
('tog_intelligence', 'tog_project', 'normal', '项目信息', 1, 5.00, 0, 0, 0, NULL, '{"description": "识别项目背景、主管单位和采购窗口", "fields": ["next_action", "next_action_due_at"]}'),
('tog_budget_approval', 'tog_project', 'normal', '立项/预算', 2, 15.00, 0, 0, 0, '["expected_sign_date"]', '{"description": "跟进立项、预算和采购方式，确认推进路径", "fields": ["expected_sign_date", "next_action", "next_action_due_at"]}'),
('tog_tender_tracking', 'tog_project', 'normal', '招标跟进', 3, 30.00, 0, 0, 0, '["amount_tax_inclusive", "competitor_info"]', '{"description": "跟进招标文件、评分办法和竞争格局", "fields": ["amount_tax_inclusive", "competitor_info", "next_action", "next_action_due_at"]}'),
('tog_bid_preparation', 'tog_project', 'normal', '投标准备', 4, 45.00, 0, 0, 0, '["amount_tax_inclusive", "expected_sign_date", "competitor_info"]', '{"description": "完成标书、授权、报价和投标排期", "fields": ["amount_tax_inclusive", "expected_sign_date", "competitor_info", "next_action", "next_action_due_at"]}'),
('tog_bid_submitted', 'tog_project', 'normal', '已投标', 5, 60.00, 0, 0, 0, '["amount_tax_inclusive", "expected_sign_date"]', '{"description": "已提交投标文件，等待评审或澄清", "fields": ["amount_tax_inclusive", "expected_sign_date", "next_action", "next_action_due_at"]}'),
('tog_pre_award', 'tog_project', 'normal', '中标候选', 6, 80.00, 0, 0, 0, '["amount_tax_inclusive", "expected_sign_date"]', '{"description": "中标候选或拟成交，仍需等待公告、预算或合同流程", "fields": ["amount_tax_inclusive", "expected_sign_date", "next_action", "next_action_due_at"]}'),
('tog_pending_contract', 'tog_project', 'normal', '待签合同', 7, 90.00, 0, 0, 0, '["amount_tax_inclusive", "expected_sign_date"]', '{"description": "中标后合同条款和签署流程推进中", "fields": ["amount_tax_inclusive", "expected_sign_date"]}'),
('tog_won', 'tog_project', 'won', '赢单', 8, 100.00, 1, 1, 0, '["amount_tax_inclusive", "expected_sign_date", "won_reason_code", "won_reason"]', NULL),
('tog_lost', 'tog_project', 'lost', '输单', 9, 0.00, 1, 0, 1, '["lost_reason_code", "lost_reason", "competitor_info"]', NULL),
('tog_paused', 'tog_project', 'paused', '暂停', 10, 0.00, 0, 0, 0, '["pause_reason_code", "pause_reason"]', NULL);
