-- Candidate only. The installer VerifyReceipt also checks reviewHash, Registry generation and existing-domain baseline.
-- Every result must be 1; no installation or repair occurs here.
SELECT COUNT(*)=16 AS verified_altoc_opportunity_stage FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='altoc_opportunity_stage' AND column_name IN ('id','code','pipeline_code','name','stage_kind','sort_no','win_rate','is_closed','is_won','is_lost','required_fields_json','exit_criteria_json','is_enabled','created_at','updated_at','row_version');
SELECT COUNT(*)=37 AS verified_altoc_lead FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='altoc_lead' AND column_name IN ('id','code','name','org_name','source_type','source_detail','need_summary','project_type','budget_status','estimated_budget','procurement_mode','expected_procurement_date','source_evidence_url','qualification_result','qualification_reason_code','contact_name','contact_mobile','contact_email','status','owner_uid','owner_dept_code','score','next_action','next_action_due_at','last_follow_up_at','invalid_reason_code','invalid_reason','converted_customer_id','converted_opportunity_id','converted_at','remark','created_by','updated_by','created_at','updated_at','deleted_at','row_version');
SELECT COUNT(*)=45 AS verified_altoc_opportunity FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='altoc_opportunity' AND column_name IN ('id','code','name','customer_id','lead_id','source_type','source_detail','stage_id','forecast_category','status','amount_tax_inclusive','amount_tax_exclusive','currency_code','expected_sign_date','expected_payment_date','win_rate','owner_uid','owner_dept_code','pre_sales_user_id','delivery_user_id','next_action','next_action_due_at','last_follow_up_at','risk_level','risk_reason','competitor_info','key_contact_complete_rate','won_at','won_reason_code','won_reason','lost_at','lost_reason_code','lost_reason','pause_reason_code','pause_reason','remark','version_no','last_status_changed_at','last_status_changed_by','created_by','updated_by','created_at','updated_at','deleted_at','row_version');
SELECT COUNT(*)=10 AS verified_altoc_lead_conversion FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='altoc_lead_conversion' AND column_name IN ('id','lead_id','customer_id','contact_id','opportunity_id','converted_by','converted_at','idempotency_key','conversion_snapshot_json','row_version');
SELECT COUNT(*)=14 AS verified_altoc_opportunity_contact_role FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='altoc_opportunity_contact_role' AND column_name IN ('id','opportunity_id','contact_id','role','influence_level','attitude','is_primary','remark','created_by','updated_by','created_at','updated_at','deleted_at','row_version');
SELECT COUNT(*)=13 AS verified_altoc_opportunity_stage_log FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='altoc_opportunity_stage_log' AND column_name IN ('id','opportunity_id','from_stage_id','to_stage_id','changed_by','changed_at','change_reason','amount_snapshot','forecast_category_snapshot','expected_sign_date_snapshot','win_rate_snapshot','version_no','row_version');
SELECT COUNT(*)=22 AS verified_altoc_sales_activity FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='altoc_sales_activity' AND column_name IN ('id','code','activity_type','subject','lead_id','customer_id','contact_id','opportunity_id','activity_at','participants_json','content','result_summary','next_action','next_action_due_at','owner_uid','status','created_by','updated_by','created_at','updated_at','deleted_at','row_version');
SELECT COUNT(*)=17 AS verified_altoc_sales_task FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='altoc_sales_task' AND column_name IN ('id','code','name','related_type','related_id','assignee_uid','due_at','status','priority','content','completed_at','created_by','updated_by','created_at','updated_at','deleted_at','row_version');
